### ISSUE TITLE
Enforced read-only mode for some viewers

### ISSUE THREAD

**Issue by comm2k** [audreyt/ethercalc#1]
We'd like to use ethercalc to provide real-time updates to people in different locations.

Scenario:
The original data (simple time-schedules) is copied from Excel and pasted into an ethercalc spreadsheet manually - everytime a change is made. However for certain 'viewers' in ethercalc we'd like to prevent them from being able to edit/manipulate the spreadsheet. 

In other words a very simple user/group or access rights system would enable us to allow some people ('planning team') to enter updates, whereas others (clients) just receive the updates via ethercalc.

Thanks :-)

**Comment by felixbecker2** [comment]
Can this be put _into_ the documentation? There should it go, instead of referring from the documentation to an issue ...
