### ISSUE TITLE
Ethercalc.org down

### ISSUE THREAD

**Issue by wargreen** [audreyt/ethercalc#104]
I don't know if it's the good place...

On ethercalc.org spreadsheets, all statics files (css, etc..) is serve, bus no dymnamics data, where I got 502 Bad Gateway or 504 Gateway Timeout.

Unfortunaly, I have important datas on this spreadsheet, and I forget make a backup...

**Comment by juliusverrel** [comment]
Hi, is it down again?

**Comment by eddyparkinson** [comment]
@audreyt looks to be down

**Comment by audreyt** [comment]
Thanks for the reminder, it's back online now.

**Comment by TobixDS** [comment]
Hi, it seems to be down again.
