### ISSUE TITLE
Import excel/csv file using ethercalc API

### ISSUE THREAD

**Issue by anvnguyen** [audreyt/ethercalc#112]
I want to import an excel/csv file into ethercalc using curl not drop file.
Which url of ethercalc I need to use to PUT a file to?

**Comment by audreyt** [comment]
As of today's version, EtherCalc 0.20150103.1 now supports importing multi-sheet Excel (and OpenDocument Spreadsheets) via this REST API:

```bash
curl -i -X PUT --data-binary @file.xlsx http://HOST/=file.xlsx
```

The leading `=` indicates multi-sheet; in the UI it's visible at `/=file` while individual sheets are visible as `/file.1` and `/file.2` etc.

If one only needs to import the first worksheet in the Excel file, this should also work:

```bash
curl -i -X PUT --data-binary @file.xlsx http://HOST/_/file
```
