### ISSUE TITLE
Ethercalc run in background ?

### ISSUE THREAD

**Issue by azg22** [audreyt/ethercalc#127]
Just wanted to first say this is an excellent piece of software and it works great! I did have one small issue though that may of been addressed in a previous report but I couldn't find it.

I run this software on linux (ubuntu 14.04 LTS server) and have been unable to figure out how to run it in the background. For instance if I SSH into my server, and run "ethercalc", I am unable to input anymore commands, unless I ctrl-C out of the application which will kill the app. To try to remedy this, I run "ethercalc&" but notice the service stops as soon as I terminate my SSH connection. Is there an alternate script or edit to the config that I can enable a background process such as running it like a daemon?

**Comment by cjresurreccion** [comment]
pm2 (https://github.com/Unitech/pm2) can also be used to run ethercalc in the background.

Start on background:
pm2 path_to_node_modules/ethercalc/bin/ethercalc -i 

List process status:
pm2 list

Stop process:
pm2 stop PROCESS_INDEX_NUMBER

Restart process:
pm2 restart PROCESS_INDEX_NUMBER

Remove from pm2:
pm2 delete PROCESS_INDEX_NUMBER

**Comment by poVoq** [comment]
This works for me on Ubuntu 16.04:
First install via 
`npm i -g ethercalc`

Then create a system user: 
`sudo adduser --system --no-create-home --group ethercalc`

Then go to /etc/systemd/system and open via 
`sudo nano ethercalc.service` 
and paste this:
```
[Unit]
Description=Run Etherpad-lite, the collaborative editor.
After=syslog.target network.target

[Service]
Type=simple
User=ethercalc
Group=ethercalc
ExecStart=/usr/bin/ethercalc --port 8000 --cors --expire 31104000

[Install]
WantedBy=multi-user.target
```
STRG+W to save and exit

Then enable start & check the service with:
```
sudo systemctl enable ethercalc
sudo systemctl start ethercalc
sudo systemctl status ethercalc
```
It will run on port 8000, have cors for cross domain use enabled and sheets are deleted after 360 days of inactivity. You might have to open port 8000 in the ufw firewall with: 
`sudo ufw allow 8000`
But I recommend to rather set up a reverse proxy with Nginx!

**Comment by eddyparkinson** [comment]
Restart every 24 hours
---

I think there is a memory leak as restarting every 24 hours tends to make it stable.

**Comment by poVoq** [comment]
Hmm, that is of course annoying. This seems to offer some options:
https://stackoverflow.com/questions/31055194/how-can-i-configure-a-systemd-service-to-restart-periodically

**Comment by poVoq** [comment]
Ok tested the automatic restart and this works to restart every 24h:
```
RuntimeMaxSec=86400
Restart=always
```

**Comment by MarioVilas** [comment]
Another option is to set up a cron job to restart the service at a specific time (so for example you don't restart the service in the middle of the day while people are using it).

**Comment by mbressman** [comment]
I would love to be able to get EtherCalc running as a service (so I can start and stop it easily from a cron job), but the two examples above (https://github.com/audreyt/ethercalc/issues/127#issuecomment-354604751 and https://github.com/audreyt/ethercalc/issues/127#issuecomment-61625172) didn't work for me on an Ubuntu Server 18.04.  If anyone can give me some hints or insight, it would be greatly appreciated!  Or even some troubleshooting or diagnostic steps to take.  Thanks!

**Comment by mbressman** [comment]
Per poVoq (https://github.com/audreyt/ethercalc/issues/703#issuecomment-593160265), here's the output I get when running 
`sudo systemctl status ethercalc`

```
root@Server2:/etc/systemd/system# sudo systemctl status ethercalc
● ethercalc.service - Run Ethercalc, the collaborative spreadsheet editor.
   Loaded: loaded (/etc/systemd/system/ethercalc.service; enabled; vendor preset
   Active: failed (Result: exit-code) since Sun 2020-03-01 18:10:57 EST; 4s ago
  Process: 1557 ExecStart=/usr/bin/ethercalc --port 8000 --cors --expire 3110400
 Main PID: 1557 (code=exited, status=203/EXEC)

Mar 01 18:10:57 Server2 systemd[1]: Started Run Ethercalc, the collaborative spr
Mar 01 18:10:57 Server2 systemd[1557]: ethercalc.service: Failed to execute comm
Mar 01 18:10:57 Server2 systemd[1557]: ethercalc.service: Failed at step EXEC sp
Mar 01 18:10:57 Server2 systemd[1]: ethercalc.service: Main process exited, code
Mar 01 18:10:57 Server2 systemd[1]: ethercalc.service: Failed with result 'exit-
lines 1-11/11 (END)
```

It seems to run off the terminal window but no idea how to capture the text that is running off the window.  Also, ultimately I'd like to remove the `RuntimeMaxSec` and `Restart` sections since I'll use a cron job to do the restart, and to remove the `--expire 31104000` since I don't want sheets to ever expire.

Thanks!

**Comment by poVoq** [comment]
Please confirm that the Ethercalc binary is installed at /usr/bin/ethercalc and working. Seems like you did something different during installation.

**Comment by mbressman** [comment]
It is not in that location.  When I did the installation, I pretty much followed these instructions:
https://ethercalc.net/
For installing for all users

So the install command I used was:
`npm install -g ethercalc`

**Comment by poVoq** [comment]
Looks to me like you didn't install it for all users, as otherwise the binary should be at that place. Try to figure out where the binary is and alter the systemd script accordingly, or resinstall with 'sudo' and confirm that the binary is in the right place.

**Comment by mbressman** [comment]
OK, will give it a try and post my results here.  Thanks for the help.

**Comment by mbressman** [comment]
Looks like it installed under /usr/local/bin/ethercalc - I did an uninstall and reinstall and it still put it there.  But modifying your script to point to /usr/local/bin/ethercalc seems to have worked!  Any issues you can foresee with running it in this location with your script modified to point to this location?

Also, if I get rid of `--expire 31104000` then presumably sheets should never be removed/deleted, right?

Thanks again for your help!

**Comment by poVoq** [comment]
Yes that should work AFAIK.

But please be aware that Ethercalc has no build in data security. Maybe think about setting this up in addition: https://framagit.org/framasoft/ert

**Comment by mbressman** [comment]
Thanks again for the assistance! 

And I know that EtherCalc is pretty insecure, but it's just being used internally from a few computers (basically to allow more than one person to collaborate and view changes on a spreadsheet) and I'm going to make sure I have ongoing backups of the Redis database also.  I'm not totally clear on what EthercalcRevisionTool that you linked to does exactly?  I read the description but it didn't give me a lot of info, and also not sure how it relates to data security.  Any info you can offer is, as always, appreciated.  

Thank you again very much!

**Comment by poVoq** [comment]
You can see the ERT in action here: https://accueil.framacalc.org/en/

It automatically saves snapshots and allows you to go back to those. I have not run thins myself though, so no tech support from me on that :)

**Comment by mbressman** [comment]
OK, I think I see what this does - and it does sound useful, but at this point I'll probably save it for another day.  Right now I'm just working on understanding and setting up backups of the Redis database (maybe once a day) so at least I'll be able to roll back (even just temporarily) if necessary.  But thanks for the info about ERT - I am going to add it to my to-do list at some point.  And thanks again for helping with the script!
