### ISSUE TITLE
Select whole row / column

### ISSUE THREAD

**Issue by gagern** [audreyt/ethercalc#135]
Comparing to desktop applications like Excel or LibeOffice Calc, it is confusing that in Ethercalc it apparently isn't possible to select a whole row or column. Particular since selecting all the cells in a row or column seems to be perfectly possible, it just takes a really long time. Can we please turn a click on a row or column header into a multi-cell selection of all cells in that row resp. column? That would be particularly important for formatting those cells.

**Comment by audreyt** [comment]
That makes sense — the place to look at is `socialcalctableeditor.js` where `SocialCalc.RangeExtend` (and the firing of `"rangechange"` event) is defined.

**Comment by audreyt** [comment]
To add a click handler please see `SocialCalc.ProcessEditorMouseDown` which calls `SocialCalc.GridMousePosition` to check the target of the click. e.g. the resize bar (rendered by `SocialCalc.RenderColHeaders` in `socialcalc-3.js`) is flagged as `result.colheader = true`; one can add another handler/flag there.

**Comment by joequant** [comment]
Thanks.  I'll take a look at this.

**Comment by joequant** [comment]
Also where do I get the width and height of the sheet.

**Comment by audreyt** [comment]
`window.spreadsheet.editor.width` and `window.spreadsheet.editor.height` respectively — see `socialcalctableeditor.js` line 12-ish (also `.tableheight` for the height minus the status bar)

**Comment by joequant** [comment]
Thanks.  Those seem to give the size in pixels?  How do I get the size in rows / columns?

**Comment by audreyt** [comment]
Each row and column has uneven size so you would need to iterate and
calculate the incremental sizes.

joequant <notifications@github.com> 於 2015年11月2日週一 19:59 寫道：

**Comment by joequant** [comment]
Can I just use the size of the array that has the row and column sizes, or will that break something?

**Comment by audreyt** [comment]
That will work.

joequant <notifications@github.com> 於 2015年11月2日週一 20:14 寫道：

**Comment by joequant** [comment]
Also what is the trick for getting ethercalc to load in non-ugified mode?  I'd like to be able to run the debugger directly on the source files.

**Comment by audreyt** [comment]
`rm static/ethercalc.js ; make DEBUG=1` will produce beautified code; I don't know how to add sourcemap though — help welcome

**Comment by joequant** [comment]
I just put in a pull request #256 to implement this.

Now to do sourcemaps :-)

**Comment by audreyt** [comment]
Awesome — thanks for the super fast implementation! Merged to master. :rainbow:

**Comment by ashishkataria** [comment]
The above feature only selects first 30-34 rows if i select entire column. Shouldn't it  select all rows of the column selected like MS Excel. I have a text written in row 100 of column A. When i select entire column A and pressed delete key on my keyboard. It just deleted first 30 rows of column A.

And if i select entire row, then also it selects only till H column.
