### ISSUE TITLE
☂: Multi-sheet support

### ISSUE THREAD

**Issue by audreyt** [audreyt/ethercalc#138]
Development is ongoing in the `multi` branch. Design follows, based on discussion with @EarlJS:

- [x] `/=foo` shows a multi-sheet UI, with content of the `foo` sheet serving as the index
 - [x] API endpoint is `/_/foo/csv.json`
- [x] Each text cell in the A column refers to a sub-sheet (subject to `encodeURIComponent`)
 - [x] `/=foo.1` is created by default
 - [x] Each sub-sheet is displayed in an iframe (à la Hackfoldr)
 - [x] The `=foo.` prefix for recalc is passed into the iframe to resolve `$Sheet1.A1` into `"foo.1"!A1`
- [x] Multi-sheet UI shows list of sub-sheet tabs in a bottom panel
 - [x] Add
 - [x] Rename
 - [x] Delete
 - [x] Export multiple sheets to XLSX (`/=foo.xlsx`)
 - [x] Import from XLSX to multiple sheets

**Comment by audreyt** [comment]
The `multi` branch is fully merged into `master` and released as of 0.20150103.0.

Drag-and-drop import in the opening screen now supports multiple sheets, and the upper-left download icon now exports Excel with multiple sheets.

Thanks @EarlJS again for proposing this feature.

**Comment by EarlJS** [comment]
Only a pleasure, the thanks goes all to you for making it possible Audrey

**Comment by iclems** [comment]
Beautiful @audreyt ! Is there any demo available? The "Try" spreadsheet on EtherCalc website doesn't seem to showcase multi-sheet. Thanks!

**Comment by audreyt** [comment]
Simply add a `=` to the randomly-generated path to try it, for example `/=multi` instead of `/multi`. :-)

**Comment by iclems** [comment]
So cool :-) where is the "=" intercepted to enable multi-sheet mode?

**Comment by audreyt** [comment]
https://github.com/audreyt/ethercalc/blob/master/src/main.ls#L159

**Comment by iclems** [comment]
Thanks!

**Comment by dessalines** [comment]
How do I enable this?

**Comment by audreyt** [comment]
Simply prepend a `=` to a sheet name should work, like `/=abcde`

**Comment by khawarjatoi** [comment]
When I create multi sheets and rename one of the sheet all other sheets disappears.

**Comment by eddyparkinson** [comment]
could not reproduce #635
