### ISSUE TITLE
Ethercalc doesn't use sandstorms user roles / permissions

### ISSUE THREAD

**Issue by JamborJan** [audreyt/ethercalc#146]
Hey @audreyt 

Just found out that ethercalcs sandstorm port doesn't use the user / permissions provided by sandstorm. This causes that grains are avaiable without login. Of course it is impossible to guess a grain id but it would be better from my point of view if it is not possible to edit or view a sheet if not at least logged in.

At the moment sandstorm has not much ready implemented for the user / permission management but there is the info of the user and it's role which is always admin at the moment.

Is this a thing to be checked in ethercalc? Other apps e.g. the wordpress app use these thing. When I open a wordpress app without being logged in I simply see the public page.

Let me know if I can do something here. I'm trying to figure out some more details about the user management and how to implement it for different app ports anyway.

JJ

**Comment by ocdtrekkie** [comment]
I think it'd make sense to wait for Sandstorm's permissions to actually work beyond "is owner"/"is not owner" before trying to work specifically with Sandstorm permissions, at least.

**Comment by JamborJan** [comment]
Thats true and the main reason why nothing yet happened here.

**Comment by ocdtrekkie** [comment]
This is actually fixed and can be closed.

**Comment by mitar** [comment]
For future reference: code is in the `sandstorm` branch.
