### ISSUE TITLE
bug after multisheet reload

### ISSUE THREAD

**Issue by bestian** [audreyt/ethercalc#152]
when i create a test multisheet with Sheet1 and Sheet2
after reload, Sheet 2 disappeared.
after click "add" again, view is good,
but when i go to "https://ethercalc.org/=g0vMulti" to see the data structure, there are duplicated Sheet1 and Sheet2 there.

~~~
https://ethercalc.org/=g0vMulti
~~~
	#title
	g0v0
	g0v1
	Sheet1
	H!H!
	Sheet1
	Sheet2
	Sheet2
~~~

**Comment by audreyt** [comment]
Thanks! It's now fixed and deployed to ethercalc.org.

BTW, the multisheet structure in https://ethercalc.org/g0vMulti would be something like this:

![2015-01-03 12 51 42](https://cloud.githubusercontent.com/assets/20723/5601625/533fc9d8-9347-11e4-9f96-68a1c389641e.png)

Somehow the #url column was gone (unrelated to this bug), so I fixed it manually and now https://ethercalc.org/=g0vMulti looks fine.

**Comment by newmanchen** [comment]
Hi there,

I add a new multiple sheet https://ethercalc.org/=AA5 and then ADD 5 sheets in a row.
Then reload the page and the first sheet is disappeared.

Go into https://ethercalc.org/AA5 and see as below.
![screenshot from 2015-01-15 15 00 29](https://cloud.githubusercontent.com/assets/2129069/5753662/525b4874-9cc7-11e4-96da-42b0126c9bc4.png)

/AA5.1 is gone and it works fine when adding it back like below manually.
![screenshot from 2015-01-15 15 03 59](https://cloud.githubusercontent.com/assets/2129069/5753684/c107335a-9cc7-11e4-8605-64a161383c0b.png)

**Comment by audreyt** [comment]
Reproduced. Thanks for the report! I'll look into it in this weekend's moedict hackathon.
