### ISSUE TITLE
Revision History

### ISSUE THREAD

**Issue by Neozaru** [audreyt/ethercalc#153]
Hello.
As user, I tested Ethercalc (ethercalc.net) this Week-End and used it to take notes.
Today, my Ethercalc is blank. Is there a feature to diagnose the problem and/or revert the "blanking" ?

Thank you.

**Comment by audreyt** [comment]
Hi, yes, the history is in https://ethercalc.org/static/history/test/ — please change "test" to your spreadsheet ID.

**Comment by audreyt** [comment]
If you need to restore to a specific revision, copy the `txt` content and use  Clipboard -> SocialCalc save format -> paste -> load SC clipboard with this -> back to A1 -> click paste in toolbar.

Or, in command line:

```bash
curl https://ethercalc.org/static/history/ID/TIMETAMP.txt | curl -i -X PUT --data-binary @- https://ethercalc.org/_/ID
```

**Comment by Neozaru** [comment]
Thank you for your response.
Strangely, my ID works for access (https://www.ethercalc.org/rfwp4znver) but doesn't for history (https://ethercalc.org/static/history/rfwp4znver/). Maybe history was not activated for my pad.

**Comment by audreyt** [comment]
It turns out that backup facility was broken from the introduction of 829be07db late November. Sorry about that!

The server's daily backup is intact though, so I'll work on restoring from that. It's late midnight in taiwan so I'll post back in 12 hours.

**Comment by teotr85** [comment]
I have the same problem, will it be restored for every ID? I would be happy if I could get my spreadsheet back ! Thanks.

**Comment by audreyt** [comment]
Yes, it will be restored for every ID; the full DB restoration would take some time, especially now that the underlying Linode Tokyo host is out of available instances.

I'll post an update within the next 11 hours. Sorry for the temporary inconvenience!

**Comment by audreyt** [comment]
The spreadsheet of @teotr85 has been restored from command logs. @Neozaru , please email me at audreyt@audreyt.org for your spreadsheet ID and I'll attempt the same restore. If both are successful, I'll restore all affected 325 spreadsheets in a batch.

**Comment by audreyt** [comment]
All affected spreadsheets should be recovered by now.

**Comment by ldidry** [comment]
@audreyt Excuse me to use this old thread, but how do you create history for the calcs? You talked about a "backup facility", what is it? Is it integrated in ethercalc or is it an other tool?

We would love having history for our [ethercalc public instance](https://framacalc.org)

**Comment by audreyt** [comment]
Hi, it's `misc/archive.ls` which I run every 5 minutes via a crontab.

**Comment by ldidry** [comment]
Thx a lot :+1:

**Comment by quentindeneyer** [comment]
Hey audreyt, 
I was filling an ethercalc spreadsheet today, and when I came back on it after a few hours it was all blank. I tried to restore preview version, but unsuccessfully. Is there a way to restore the content? I tried the above mentioned solutions, but nothing worked for me...
My spreadsheet ID is xjl3fuhld5u7
Thanks!
quentin

**Comment by eddyparkinson** [comment]
think you need @audreyt  

I can see https://ethercalc.org/_/xjl3fuhld5u7 show some values - but they look wrong

**Comment by audreyt** [comment]
Unfortunately the backup disk is full; I'm re-provisioning one but I'm afraid the backups has stopped.
