### ISSUE TITLE
Ethercalc.com spreadsheet restore

### ISSUE THREAD

**Issue by teotr85** [audreyt/ethercalc#154]
Hey,
I really liked ethercalc.com and used for a while, took important notes in my file.
Today something happened, and my spreadsheet became blank. This is very important for me to restore it somehow, I appreciate any help.
Cheers
Teodor

**Comment by audreyt** [comment]
Hi, yes, the history is in https://ethercalc.org/static/history/test/ — please change `test` to your spreadsheet ID and see if it is there?

If you need to restore to a specific revision, copy the txt content and use Clipboard -> SocialCalc save format -> paste -> load SC clipboard with this -> back to A1 -> click paste in toolbar.

Or, in command line:

```bash
curl https://ethercalc.org/static/history/ID/TIMESTAMP.txt \
| curl -i -X PUT --data-binary @- https://ethercalc.org/_/ID
```

**Comment by teotr85** [comment]
If I paste my ID, 404 page comes.
I used to use .com not .org.

**Comment by audreyt** [comment]
Hi, did you add an extra `/` to the end of URL?

https://ethercalc.org/static/history/test/ would be the history.
https://ethercalc.org/static/history/test would be 404.

**Comment by teotr85** [comment]
Still getting 404 even if I add / .This is the ID: 64f6kbg77k

Date: Mon, 12 Jan 2015 07:33:23 -0800
