### ISSUE TITLE
create a support forum for ethercalc

### ISSUE THREAD

**Issue by markum** [audreyt/ethercalc#155]
I would find it very usefull to have a support forum. I trying to get ethercalc to work in my Uberspace.de . Unfortunately I am unsuccessful with this. I do not believe these are bugs which belong here, so it would be good to have forum as a place where users can help each other.

**Comment by audreyt** [comment]
Perhaps use stackoverflow with the appropriate tags (`ethercalc` etc) for now?

https://stackoverflow.com/questions/26115464/import-excel-csv-file-using-ethercalc-api/27748384#27748384

I'm open to using GitHub issues here, too, with the `support` label.

**Comment by Artemisf** [comment]
I guess you don't need this anymore but I wrote a step by step tutorial on my blog, because I had the same problem. Its in german but the commands are the same. https://webbl0g.org/page/?id=56

**Comment by eddyparkinson** [comment]
@Artemisf  There is a wiki - https://github.com/audreyt/ethercalc/wiki
 
This is a common problem, sometimes people struggle to setup ethercalc. Every few months someone has install issues. It is not easy with some platforms. A wiki with details of install details for various platforms would make sense. ... if you set one up, we can ask people to post solutions there.
