### ISSUE TITLE
Allow copy/paste between sheets

### ISSUE THREAD

**Issue by stevel6868** [audreyt/ethercalc#157]
It seems each sheet has it's own copy/paste buffer. Is there a way to copy and paste between sheets and, if not, could there be?

Many thanks for a great tool!

**Comment by audreyt** [comment]
There is a way, rather roundabout though:
* Use the Toolbar to copy.
* In the "Clipboard" tab, click "SocialCalc-save format" and copy the text **from** the textbox.
* In the other sheet's "Clipboard" tab, click "SocialCalc-save format" and copy the text **into** the textbox.
* In the other sheet's main view, use the Toolbar to paste.

**Comment by furetto** [comment]
it looses formulas anyways

**Comment by eddyparkinson** [comment]
@furetto it should copy formulas as well.  You can also paste formatting using the paste formatting toolbar button.

**Comment by furetto** [comment]
I have in D2 this:
=SELECT("PT",A149:A161)
if i copy A1:F14 to another area (i need to duplicate it many times) i get:
=SELECT("PT",I168:I180)

That's what i mean with loosing formulas.
By the way, thanks a lot for replying.

**Comment by eddyparkinson** [comment]
You are right. The bug details are here https://github.com/audreyt/ethercalc/issues/491

This is top of my fix list when I get time. But will probably have time in Nov.

**Comment by brdelphus** [comment]
Not sure if this thread is still alive, but  from my experience with latest version of ethercalc, copy data from save to load in clipboard doesn't work. copy paste from toolbar sometimes will copy cell formats but wont show texts and wont copy formulas. still unable to use it with multi-sheet say sheets for yearly data

**Comment by eddyparkinson** [comment]
Re-create bug
---

@brdelphus Please can you describe the steps, so I can re-create the bug. 

Re: multi-sheet paste 
---

It will not update sheet names. You would need to manually update sheet names.
