### ISSUE TITLE
Save lock pane and view position when leaving a spread sheet

### ISSUE THREAD

**Issue by JamborJan** [audreyt/ethercalc#160]
I have longer lists in ethercalc where I also use the 'lock pane' feature.

It would be very useful if ethercalc would save the rows and columns I have locked and also the view I had before. E.g. line 136 was the first displayed on and column K the first displayed column.

This enhancement would save up to one minute of time every time a spread sheet is opened.

PS: I'm using the sandstorm port of ethercalc if this is of interest here

**Comment by samejack** [comment]
I think it has been resolved at #183
