### ISSUE TITLE
Question to finalize a french translation feature

### ISSUE THREAD

**Issue by renoproc** [audreyt/ethercalc#163]
I'm french and I've used the framacalc translation js file.
But because there are not only language differences between En and Fr versions,
I'm continuing the translation, ie 1 234.00 € instead of $1,234.00, 24h/day instead of 12PM/AM...

Dates are the only thing that aren't working, even if I change socialcalcconstants.js date patterns to something like d-mmm-yyyy the result is the english version mmm-d-yyyy.
May I  change this elsewhere than in socialcalcconstants.js file ?

Many Thanks,
Reno

**Comment by audreyt** [comment]
If I enter `2014/02/07` to a cell I see it formatted as `7-Feb-2014`, which is already `d-mmm-yyyy`. The place to change, if you'd like to change that, is `defaultFormatd` in line 188 of `socialcalcconstants.js`.

**Comment by renoproc** [comment]
Yes and thanks for this trick, I just saw the SCFormatNumberFormats values. 
But my problem is more that french users will enter their dates like dd/mm/yyyy (dd-mm-yyy) and not like mm/dd/yyyy or yyyy/mm/dd... 

Where can I change or add this feature ?
Thaks for your reply.

**Comment by audreyt** [comment]
I think swapping `matches[1]` and `matches[2]` in https://github.com/audreyt/ethercalc/blob/master/socialcalc-3.js#L5539 would do it.

**Comment by renoproc** [comment]
Nope swapping the two matches values don't do the trick...
By the way what the use of ```defaultFormatc: "[$$]#,##0.00"``` in ethercalc.js,
may I change it for ```defaultFormatc: "[€€]# ##0.00"``` ?

**Comment by audreyt** [comment]
Sure!

**Comment by renoproc** [comment]
Ok I did that.

About socialcalc-3.js, I did the suggested permutations but nothing change.
Even I've commented lines of this file to see which errors will be generated. 
From line 5536 to line 5547 and restarted ethercalc, result : no errors, nothing, ethercalc works like a charm (!?!)... Same thing if I delete the socialcalc-3.js file!
Then...did I miss something, is there a cache out of dump.json ?

Thanks for your explanations and time.

**Comment by audreyt** [comment]
`make depends manifest` should refresh both the server side `SocialCalcModule.js` and the client side `static/ethercalc.js` as well as the application cache file `manifest.appcache`.

Note: You might need to install `closure-compiler` for this to work; I'd happily accept a pull request to change it to `uglifyjs`.

**Comment by renoproc** [comment]
Thanks, 
ok so I've installed ```closure-compiler``` from Google Code, works well but a make depends manifest executed in ethercalc folder return 
```make: nothing to be done for "depends"
perl -pi -e 's/# [A-Z].*\n/# @{[`date`]}/m' manifest.appcache```

**Comment by audreyt** [comment]
Hi, we have since switched to Uglifyjs and made `make depend` more sane.

Also, to change localization now it's sufficient to checkout this GitHub repo, change files under `l10n/` and restart the server with `make`.

**Comment by arnaudlecam** [comment]
Hi,
Thank you for this issue, renoproc !
I think that changing "defaultFormatc" is useless...
Swapping "matches[1]" and "matches[2]"  in https://github.com/audreyt/ethercalc/blob/master/socialcalc-3.js#L5702, then running make on the terminal simply did the trick for me:

![2015-12-01_00-02-10](https://cloud.githubusercontent.com/assets/12881960/11487357/dd9cd950-97be-11e5-8be7-369af597b3c0.png)

But I'm not a coder, and I suppose forking is not a good idea (am I wrong ?) : so, audreyt, do you think there's a way to work on that issue in l10n/ ?
Should I read more about Perl ?

**Comment by audreyt** [comment]
Forking is always a good idea. :-) Please push your fork first!

One way is to test `navigator.language` like we did in `index.html` line 37 and conditionally swap `matches[1]` and `matches[2]` — this means for the same spreadsheet we will respond differently for a French user entering dates. Does that make sense?

**Comment by arnaudlecam** [comment]
yes it makes sense, and I will try forking in that way
thank you for your encouragement !

**Comment by arnaudlecam** [comment]
first I made a fork, and then I commited on socialcalc-3.js
anything else to do now ?

**Comment by audreyt** [comment]
Next up, please make a pull request from https://github.com/audreyt/ethercalc/compare/master...arnaudlecam:master so I can incorporate your changes.
