### ISSUE TITLE
Restrict Acess to /edit spreedsheet.

### ISSUE THREAD

**Issue by ThiagoEmanoel92** [audreyt/ethercalc#166]
Hi , Andrey how are u ? 

I 'm from Brazil , and i must say there so many Guys from I.T are using EtherCalc , and this is Amazing . 
 I am trying use EtherCalc , but i 'am having a problem .

i want make that , when someone try access my spreedsheet , he must insert User and Password , like Issue #4  .

I wanna make this at my Apache , is possible ?

My virtual host is like this : 

```
<VirtualHost *:80>	
	ServerName localhost
	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/
<Directory /var/www/phpmyadmin>
Order allow,deny
allow from all
</Directory>
<Directory /var/www/phpipam>
Options FollowSymLinks
AllowOverride all
Require all granted
</Directory>
	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```

I am running EtherCalc from port 8000 , and my Apache run at port 80.

Thanks for your attention.

**Comment by audreyt** [comment]
I've not worked with Apache for the past 10 years, though https://httpd.apache.org/docs/2.4/howto/auth.html#gettingitworking and https://httpd.apache.org/docs/current/mod/mod_proxy.html describes a general process of password-protecting a given URL, such as `/edit`.

Please post here when you (or another helpful folk) have a recipe ; I'd be happy to add the worked example into the ethercalc repository.

**Comment by ThiagoEmanoel92** [comment]
Hey Audrey , thanks for the fast reply .

Guy i was reading the documentation from Apache.org , and now is Working very amazing . 

Thank you for this Great Application man , i'ill try put .htpasswd at URL "/view" , can i make like "/edit"

Ciao .

**Comment by pjrobertson** [comment]
Incase it helps, here's part of my Apache conf file (in `/etc/apache2/sites-enabled/`)

To view any spreadsheets, you need to be logged in as any user. To edit spreadsheets you have to be logged in as `asdanadmin`

```
        ProxyPass /sheets/ http://127.0.0.1:8000/
        ProxyPassReverse /sheets/ http://127.0.0.1:8000/
        <LocationMatch "^/sheets/">
                AuthType Basic
                AuthName "Viewer"
                AuthUserFile "/etc/apache2/htpasswd"
                Require valid-user
                Order allow,deny
                Allow from all
        </LocationMatch>
        
        <LocationMatch ^/sheets/(.*)/edit$>
                AuthType Basic
                AuthName "Viewer"
                AuthUserFile "/etc/apache2/htpasswd"
                Require user asdanadmin
                Order allow,deny
                Allow from all
        </LocationMatch>
```

I think you can probably close this issue :-)

**Comment by audreyt** [comment]
Yup. Thanks! :rainbow:

**Comment by pjrobertson** [comment]
谢谢 ：-）
