### ISSUE TITLE
Enable CORS for multiple domains

### ISSUE THREAD

**Issue by harshithkashyap** [audreyt/ethercalc#168]
Hi there,
I'm trying to enable CORS for a predefined set of domains. By default, the origin is set to ' * ' on main.js file. Replacing '*' with mydomain.com works but i cannot specify more than one domain.
Looking into the enabling CORS for multiple origins, the request header host is checked with the white listed domains and rejects the rest. But there is no req object within the main.js file. How do i specify the same?

**Comment by audreyt** [comment]
The request object is available as `req` as well as `this.request` at the line of `main.js` you described.
