### ISSUE TITLE
about EtherCalc: documentation : passing data client <--> server

### ISSUE THREAD

**Issue by pablo3p** [audreyt/ethercalc#171]
Hi there,
I recently discovered EtherCalc.
I found enough info to install EtherCalc.
But I want to be able to pass data from the spreadsheet GUI to the backend to the database.
How can one do this.
My backend is in Python.
Is there a Rest-Interface?
If yes, where can I find documentation, or tutorial on EtherCalc.
I could not find this on the main page.
Hope you can help.

Regards,

P

**Comment by audreyt** [comment]
Yes, please see http://docs.ethercalc.apiary.io/ for the API.
