### ISSUE TITLE
about retrieving previous spreadsheet

### ISSUE THREAD

**Issue by pablo3p** [audreyt/ethercalc#176]
Hi,
When I run a URL like: localhost:8000/_new, I can get a new spreadsheet instance.
I get a URL for the new spreadsheet like this: http://localhost:8000/og3b17y15x.
BUT once this spreadsheet is closed down, how can a user get back their original spreadsheet.
Is the user somehow supposed to remember this URL with the  random characters "og3b17y15x".

My Question:
Is there some way when a user generates a spreadsheet that they can put a NAME they want for the spreadsheet.

Regards,

P

**Comment by audreyt** [comment]
Yes, simply type http://localhost:8000/yournamehere would make a new sheet too.
