### ISSUE TITLE
Ether Calc and CSS files 

### ISSUE THREAD

**Issue by pablo3p** [audreyt/ethercalc#178]
Hi there,
I am having difficulty finding ways to change the theme of the spreadsheet.
I have made modifications in the CSS files that are on disc, but it has no effect when I run the
ethercalc app.
When I run the app in the browser, and then I using Firebug to make virtual changes, I am able to make the effect I want.
When I look at the source code in the browser of the ethercalc spreadsheet, the HTML has inline
CSS, and this is the code that I was changing. So this seems to indicate to me that the external CSS is somehow not used, or at least not used for styling.

SO really hope to get your input.
Regards,

P

**Comment by audreyt** [comment]
Sorry for the rather late reply. That's probably because `manifest.appcache` is causing a browser cache.

You can either work from a Git checkout, or manually remove the `manifest.appcache` file during development.
