### ISSUE TITLE
Add a preconfigured default format with comma as decimal mark

### ISSUE THREAD

**Issue by liquidat** [audreyt/ethercalc#181]
Currently the default format is very US centered: besides the dollar sign for sums, the decimal mark is a dot. In other languages - notably German - the decimal mark is a comma.

Please add a preconfigured default format including the comma as a decimal mark (and also the euro sign as currency symbol).

**Comment by audreyt** [comment]
Hi, this can be fixed by adding a `de.json` in `l10n/` with appropriate values. See:

https://github.com/audreyt/ethercalc/blob/master/l10n/en.json#L319-L321
https://github.com/audreyt/ethercalc/blob/master/l10n/zh-TW.json#L319-L321

Pull requests welcome!

**Comment by liquidat** [comment]
I'm on it. I slowly try to translate the given english json file - would you like to have multiple pull request, or one big one when I am done with everything I can translate to my best knowledge?

**Comment by audreyt** [comment]
Either one is good. :-)

**Comment by liquidat** [comment]
As mentioned in the pull request, that is a rather limited, first set of translated strings. It does not cover all the strings, it for sure needs some review by other people using Ethercalc, but it creates a base for German users.
