### ISSUE TITLE
Restore using log

### ISSUE THREAD

**Issue by HeathLee** [audreyt/ethercalc#186]
when  I using  log to recover a file, the page can not response and all the data  won't display, but  I can see them if I export the file

**Comment by audreyt** [comment]
Hi, assuming this is from ethercalc.org, would you like to email the spreadsheet ID?

Also if you're using Chrome, try open the spreadsheet in an Incognito mode. Or Firefox in Private Browsing mode — perhaps it was caching the wrong version.
