### ISSUE TITLE
Sandstorm: Feature request: Implement read-only sharing

### ISSUE THREAD

**Issue by kentonv** [audreyt/ethercalc#188]
Sandstorm now supports sharing with permissions, and Ethercalc should be extended to support a read-only "viewer" role.

For example, kentonv/etherpad-lite@1c306d4 added roles to Etherpad. This hooked into Etherpad's existing read-only bit, but notice that there's no need to implement any notion of user accounts; Sandstorm takes care of that.

(Note: I used the role name "editor" and "reader" there, forgetting that "viewer" is the preferred term rather than "reader". I'll fix that at some point, but in the meantime don't copy me.)

Or for another example, dwrensha/groovebasin@b6ec045 added roles to Groovebasin.

**Comment by audreyt** [comment]
Sure! EtherCalc also has a read-only bit ( e.g. https://ethercalc.org/test/view versus the editable ethercalc.org/test ) so it should be straightforward.

**Comment by audreyt** [comment]
Implemented as of https://github.com/sandstorm-io/sandstorm-website/pull/70.

**Comment by ocdtrekkie** [comment]
Awesome. Already using it. Thank you!
