### ISSUE TITLE
view/edit not working for multi sheets

### ISSUE THREAD

**Issue by pjrobertson** [audreyt/ethercalc#189]
If you insert `=` at the start of the sheet name to create a multi sheet (as per #138), then the URLs ending in /view and /edit do not work.

It seems that anybody can edit multi sheet pages

**Comment by pjrobertson** [comment]
Also, opening up any multi sheet page (e.g. by dragging/dropping a multi-sheet XLSX file to the home page) doesn't display properly when edit/view permissions are set.

Reproduce:

* Start ethercalc with: `ethercalc --key mykey`
* Go to 127.0.0.1:8000
* Drag/drop a multi sheet Excel spreadsheet to the home page
* View the generated page. You get a sheet with the URLs to the individual sheets, but no tabs etc.

**Comment by audreyt** [comment]
Reproduced. Thank you for the report, will look into it during the weekend.

**Comment by pjrobertson** [comment]
@audreyt - is this something you'd be able to work on, or either give me some pointers on how to fix it?
It's probably the no.1 priority for our use of the spreadsheets right now :-)

**Comment by audreyt** [comment]
I did look into it — it will involve these changes:

- [ ] Modify `src/main.ls` line 171 and 174 to add similar checks to line 165 (`if KEY then`).
- [ ] Modify `multi/main.ls` to add similar checks to `src/player.ls` line 8 (`if /\?auth=/.test window.location.search`).
- [ ] Somehow pass the `?auth=` parameter into the sub-sheets, or (maybe easier) the `/view` / `/edit` mode, in `multi/main.ls` line 78.

Please feel free to work on some of these and I'll follow up after coming back from the http://modernweb.tw/ conference this weekend.

**Comment by audreyt** [comment]
Hi @pjrobertson — Would you like to give the `master` branch a try and see if it works for you?

**Comment by pjrobertson** [comment]
Great, thanks. I'll give it a try later on today.

**Comment by pjrobertson** [comment]
OK, if I go to http://example.com/=nameofsheet/edit it still just redirects me to the view page. I cannot seem to get the edit buttons to work

**Comment by pjrobertson** [comment]
Thanks for fixing it! :-)
You've meant I haven't had to figure out LiveScript just yet... :-)
