### ISSUE TITLE
Vertical split not visible

### ISSUE THREAD

**Issue by pjrobertson** [audreyt/ethercalc#210]
If you drag the lock pane slider for the columns out (bottom left of the editor) to split the columns, there is no 'thick' line between the fixed and moving columns.

If you do the same for the lock pane slider for rows, you will see a thick line separating the fixed and moving rows. This is what should happen for the columns.

![ethercalc](https://cloud.githubusercontent.com/assets/150431/7805652/b398661a-03a8-11e5-87c3-0d59e49d9fe6.png)

**Comment by audreyt** [comment]
Hmm I do see a think line in https://ethercalc.org/test (both Chrome and Firefox):

```html
<td style="font-size: small; background-color: rgb(192, 192, 192); padding: 0px;" width="2">
  <div style="width: 2px; overflow: hidden;"></div>
</td>
```

What is your browser/OS combination?

**Comment by pjrobertson** [comment]
Hmm... OK. I see it in Firefox, but not in Chrome on Ubuntu. I will look into it further
