### ISSUE TITLE
Ethercalc Icon sets / Theme / Skin

### ISSUE THREAD

**Issue by sank64** [audreyt/ethercalc#218]
Alternative theme for Ethercalc
=============================
![preview](https://cloud.githubusercontent.com/assets/9414077/7932929/d7070e26-091b-11e5-89f7-fd45931e11e4.png)

Key features:
1- Beautiful, high quality icons
---
2- Easy to read for anyone
---
3- Light, modern design
---

You will find the icon sets in png and gif at 24 and 32 pixels resolutions here: https://github.com/sank64/ethercalc_theme.git

If you want to have the complete theme which include a thourough work on the css and js properties, you should go there: https://github.com/sank64/ethercalc_theme_green.git

All my work is released under MIT License to thanks everyone who developped Ethercalc, and to encourage even more people to keep doing such a good work!

Kévin
contact at sanouiller dot fr

**Comment by pjrobertson** [comment]
@audreyt should this be merged into master?
If you want to keep the old style perhaps we should go down the route of creating a 'config.js' file where people can set their own config params
@sank64 fancy making a pull request?

**Comment by audreyt** [comment]
I'm fine with merging this to master — please help creating a PR :rainbow:

**Comment by ocdtrekkie** [comment]
I would be kinda shocked if the icon on the top left didn't open you up to trademark infringement though.

**Comment by audreyt** [comment]
Yeah. As for that we can use the Sandstorm designer's contributed icon:

<img width="204" alt="screen shot 2015-10-13 at 10 04 19 am" src="https://cloud.githubusercontent.com/assets/20723/10443842/cd4ec53e-7191-11e5-9716-2b4c7e771267.png">

**Comment by pjrobertson** [comment]
I've just looked at this iconset/theme, and I actually prefer the current
one. Maybe it should just be referenced somewhere in the docs.

**Comment by audreyt** [comment]
Good to know — But still please make a PR so we can make it customizable

**Comment by sank64** [comment]
@ocdtrekkie: The logo is not part of the release.
I'll make a PR.

**Comment by sank64** [comment]
PR is sent with green theme set. Maybe this could be kept as a separate branch so as anyone can make their own choice about which them to use.

**Comment by rugk** [comment]
PR is: https://github.com/audreyt/ethercalc/pull/320

Actually this issue can be closed, can't it?

**Comment by poVoq** [comment]
So how would one actually go about switching the theme? I am looking for somewhat smaller buttons as currently (when resizing the window for iframe embedding) the editor icons overapp quite badly with the formular row.

**Comment by eddyparkinson** [comment]
@poVoq I added to an iframe. I only added for the viewer. So no buttons. But it was not easy, I needed to re-write several sections of code.  I expect it would be a few days task.

**Comment by poVoq** [comment]
I would like to retain the button, but just have them use less space. I guess with a smaller icon set that might be possible? Or is the relative size of the buttons hard-coded?

**Comment by eddyparkinson** [comment]
Try changing the 26
https://github.com/audreyt/ethercalc/blob/master/static/makeup.css#L208

https://i.imgur.com/qxzMEAU.png

**Comment by poVoq** [comment]
Oh, but that file is really difficult to modify in the Docker image. Even just temporary :(

**Comment by codecowboy** [comment]
Did anyone get this working? The original links to the theme are dead

**Comment by ocdtrekkie** [comment]
@codecowboy Did you look at #320 ?
