### ISSUE TITLE
CPAL license question

### ISSUE THREAD

**Issue by JohnMcLear** [audreyt/ethercalc#22]
Hey @Audreyt, are you aware that CPAL requires attribution information to be displayed to the users UI?

http://en.wikipedia.org/wiki/Common_Public_Attribution_License

I wasn't aware of this, is it something you wish to enforce?

**Comment by audreyt** [comment]
FYI, the 16x16 logo issue that @JohnMcLear  find issues with in `socialcalctableeditor.js` can be worked around altogether with a new editor frontend, while keeping the rest of EtherCalc (formula engine, import/export and collaboration).

I've started working on such a frontend in https://github.com/audreyt/500lines/tree/master/spreadsheet#online-demo (again in the public domain as CC0) and if folks are interested I'd be happy to offer it as an alternative frontend. Other UI frontend suggestions are welcome, too.
