### ISSUE TITLE
Removing obsolete files

### ISSUE THREAD

**Issue by sank64** [audreyt/ethercalc#222]
It seems that the following files are not affecting any behaviour for ethercalc (same parameters are read from ethercalc.js if I am right) so they should be moved in a "source" directory or simply removed:

player-graph.js
SocialCalcModule.js

**Comment by audreyt** [comment]
`SocialCalcModule.js` is used by `src/sc.ls` (= `sc.js`).

`player-graph.js` is included by `src/main.ls` (= `main.js`).
