### ISSUE TITLE
French l10n

### ISSUE THREAD

**Issue by amarandon** [audreyt/ethercalc#227]
Hello,

I've read #181 and would like to do the same for French. It turns out that the biggest part of the job has been done already by Framasoft, a French non-profit that promotes opensource software: https://framacalc.org/static/ethercalc.fr.js Example spreadsheet at https://framacalc.org/cGeGx9OCL1
I'm not sure why it's not been merged into this repository, but I can contact them to ask permission to use their file, add the decimal and currency characters and do the pull request.

By the way, how can I enable a given l10n file for my EtherCalc instance?

**Comment by audreyt** [comment]
Hi @amarandon , please do contact them and also modify `l10n/fr.json` as you see fit.

As of GitHub `master` branch in c0f0229, should just work without requiring any special configuration.

**Comment by sank64** [comment]
Merci Amarando & Audreyt !
