### ISSUE TITLE
How to autostart from system settings 'Session and Startup'?

### ISSUE THREAD

**Issue by maqueen** [audreyt/ethercalc#235]
Latest stable installed and working from command line using suggested node.js/npm, Redis, etc. method.

Can't autostart at boot using Debian Xfce 'Session and Startup' using: '/mypath/ethercalc/npm start app.js'.

I'm assuming I'm doing something wrong with syntax above. Any suggestions (...and don't tell me I have to write a script for init.d, rc.local, etc.... (as if all novices just magically have these skills and know all the nuances))?

**Comment by audreyt** [comment]
Try: `/mypath/ethercalc/bin/ethercalc` instead?

**Comment by maqueen** [comment]
Did the trick thank you!

唐鳳:
