### ISSUE TITLE
App Graphics for Sandstorm

### ISSUE THREAD

**Issue by neynah** [audreyt/ethercalc#236]
Hi @audreyt 

I'm Nena Nguyen, designer at Sandstorm. I'm reaching out to you about graphics because we're currently developing an app market and working on UI improvements to the existing Sandstorm shell design. See: https://groups.google.com/d/msg/sandstorm-dev/VRkPqX61cRs/Ts37SbqqKAAJ

As a part of this redesign, existing and new apps will need to submit 3 graphics (as a part of their SPK) for aesthetic and functional purposes.

I went ahead and created a set of graphics for you. If you think these are suitable, I can create a pull request with the appropriate sizes for when you'll need to add these to the SPK(soonish). If not, I'm happy to make adjustments.

I can also send you the files for tweaking or you can choose to create your own set.

Thanks!

:)

![ethercalc-preview1](https://cloud.githubusercontent.com/assets/855341/9285617/9ac11532-429c-11e5-917c-60cd8865ab5d.png)

**Comment by audreyt** [comment]
There are great, thank you!

Audrey
> Néna Nguyễn <notifications@github.com> 於 2015年8月15日 上午6:54 寫道：
> 
> I went ahead and created a set of graphics for you. If you think these are suitable, I can create a pull request with the appropriate sizes for when you'll need to add these to the SPK(soonish). If not, I'm happy to make adjustments.
> 
>

**Comment by ocdtrekkie** [comment]
Can close this issue, methinks.
