### ISSUE TITLE
Data Validation List?

### ISSUE THREAD

**Issue by chayden73** [audreyt/ethercalc#239]
Is it possible to have a data validation list in the spreadsheet

**Comment by audreyt** [comment]
Would you like to elaborate on a use case, or link to a similar functionality in other spreadsheet software?

**Comment by chayden73** [comment]
I am interested in having a dropdown list in a cell where users can only select values for that cell from the dropdown list. An example can be seen at the link below.
http://www.contextures.com/xlDataVal01.html

**Comment by audreyt** [comment]
Understood. Thanks for the clarification!

**Comment by chayden73** [comment]
Hi,
I noticed you have labeled the request as an enhancement. Is there anything  I can do or can you point me in a direction to achieve this.

**Comment by audreyt** [comment]
EtherCalc has the concept of Named Ranges (see the "Names" tab) so we're halfway there.

What remains is to make a format that refers to a Name as valid inputs. A new `textvalueformat` `text-validated` (or some such) may be used for this purpose, perhaps making the Name as part of the value format and render the input box differently (say, as a `<select>` box) .

https://ethercalc.net/#ch4 has some related details. I'm currently traveling and so cannot work on it personally, but I'd happy to see if someone interested takes this task in a pullreq or a branch.

**Comment by amir-zeldes** [comment]
Hi - did this get implemented? I know the Named Ranges, but I haven't seen a simple way to restrict a column to values from some named range. This would be a very useful feature for data integrity.

**Comment by eddyparkinson** [comment]
**Restrict to values**

creates a selection list in a cell:

`=SELECT("Return",D329:D330)
`

*Example*  in cell D45 of 
http://sheet.cellmaster.com.au/carbonoffset

Web app http://sheet.cellmaster.com.au/carbonoffset/app

** Functions **
For docs for the functions
see the "fx" button next to the input box on the spreadsheet

**Comment by amir-zeldes** [comment]
Excellent! EtherCalc rocks

**Comment by amir-zeldes** [comment]
OK, I spoke too soon - I can't seem to get =SELECT() to work - I updated EtherCalc via npm, and it's saying `ethercalc@0.20160612.0` but that function is not showing up for me (even tough I can see it in the list at the instance you linked to). @eddyparkinson Am I running an older version than you? If so how can I upgrade to have SELECT? Any hints would be appreciated! 

I'd rather keep the link a bit covert, but you can find my instance and a test sheet for this at: http://corpling.uis.georgetown.edu slash ethercalc slash test_list

**Comment by eddyparkinson** [comment]
Sounds like your static/ethercalc.js is old, Or maybe a JQuery-ui issue.  

static/ethercalc.js should contain FunctionList.SELECT
https://github.com/audreyt/ethercalc/blob/master/static/ethercalc.js

Did you clear your browser cache? 

FYI  The make command creates ethercalc.js from  https://github.com/marcelklehr/socialcalc

Or maybe a JQuery-ui issue, as there are 2 JQuery-ui files in https://github.com/audreyt/ethercalc/tree/master/static

My version is
https://github.com/eddyparkinson/cellmaster/tree/website
but all the formulas should be the same.

**Comment by amir-zeldes** [comment]
I tried clearing the cache, and just tried overwriting static/ethercalc.js with the source you pointed to (though the file does say `// Auto-generated from "make depends"; ALL CHANGES HERE WILL BE LOST!`). These steps don't make the UI recognize the SELECT function sadly. I'm not sure what the solution to the possible jquery issue would be - would I need to delete one of them and replace all references with the other? If so, which one?

Do I need to 're-build' ethercalc in some sense manually from a github clone? I just used `npm update -g --unsafe-perm ethercalc`, which visibly updated some aspects of the UI and put me at the 20160612 version, but didn't get the SELECT function to work so far. Is npm not the preferred way of upgrading?

Thanks for your help!

**Comment by eddyparkinson** [comment]
Maybe pull the code using git?

This says the npm version is 4 month old https://www.npmjs.com/package/ethercalc
You need July 18 2016 or later.

This version works - https://ethercalc.org/ytjs0whc5l1g

**Comment by amir-zeldes** [comment]
OK, that explains it - I'm just using the npm version, which seems to be from June. I'll try pulling directly from the repo instead. Thanks!

**Comment by audreyt** [comment]
I've published the current version to npm as: ethercalc@0.20161029.0

**Comment by amir-zeldes** [comment]
Perfect, works like a charm. Thanks so much for all this great support!
