### ISSUE TITLE
Links should open _blank

### ISSUE THREAD

**Issue by neynah** [audreyt/ethercalc#240]
When clicking on a link in the spreadsheet, it currently loads in Sandstorm in the iframe (I can see the "Sheet 1" UI at the bottom).

**Comment by audreyt** [comment]
Agreed. Is it possible to set `target="_blank"` at the `<iframe>` level? Perhaps as a Sandstorm config?

**Comment by ocdtrekkie** [comment]
@audreyt From a non-Sandstorm standpoint, I kinda imagine most people opening links in spreadsheets would rather not close the spreadsheet.

**Comment by audreyt** [comment]
OK — I can see that. Anyone relying on the current open-in-same-window behavior before we change it?

**Comment by neynah** [comment]
Not that I know of, although @paulproteus would probably have a better idea. At the moment I also can't think of a scenario where having a link (in the spreadsheet) opening in the same window would be preferred.

**Comment by paulproteus** [comment]
I don't think anyone is relying on the open-in-same-tab behavior, fwiw.

I don't know of a way to set this at the Sandstorm platform level, but http://stackoverflow.com/a/2656798 might be useful to avoid having to rework every `<a href=...>`.

**Comment by paulproteus** [comment]
Which is to say:

In EtherCalc on Sandstorm, consider adding:

```
<base target="_blank" />
```

in the grain's HTML.

**Comment by audreyt** [comment]
OK then! Seems we have consensus.

**Comment by paulproteus** [comment]
Also, this `<base target="_blank_">` thing should go somewhere in `docs.sandstorm.io`. @audreyt if you decide you want to look into that at any time, I would mega appreciate it. I think that listing usability-oriented porting concerns somewhere, with common Sandstorm pitfalls and how to avoid them in an app, would make a super-great part of the docs.

The way the docs work is that they live in the `doc/` directory in the main Sandstorm repo now. https://github.com/sandstorm-io/sandstorm/wiki says a little more about that.

But that's optional @audreyt , and a separate issue; I'm just rambling aloud here.

**Comment by audreyt** [comment]
Done and done! Thanks folks. :-)
