### ISSUE TITLE
[support] how to import csv

### ISSUE THREAD

**Issue by ckhung** [audreyt/ethercalc#244]
Hi I am new to ethercalc. I need to import (or paste) from a csv file into ethercalc. I see there is a clipboard tab. I clicked "display as csv", pasted the cav, and clicked "load socialcalc clipboard with this". I was taken to the main edting tab, but nothing was pasted or imported. Am I doing something wrong? I have searched the issues but didn't see similar questions. Thanks!

**Comment by ocdtrekkie** [comment]
CSV files can be drag-dropped into EtherCalc, have you tried that? There is both a manner to import into a fresh sheet (see ethercalc.org for example), and to overwrite an existing sheet while it's open, though I forgot how you do that.

**Comment by audreyt** [comment]
Hi @ckhung — in the main editing tab you can click "paste" in the toolbar which populates the editing area of internal clipboard.

**Comment by ckhung** [comment]
@ocdtrekkie : thanks! I didn't try drag-n-drop since @audreyt 's answer already worked for me. Today I finally tried d-n-d and found out that it didn't work for me. Or maybe I am not doing it right. On lubuntu 15.04 I d-n-d from pcmanfm to an ethercalc page in firefox. If the ethercalc page is in the editing tab, the browser just asks me whether I want to open it using a local app (gnumeric/LibreOffice) or save it to disk. If the ethercalc page is in the clipboard tab, only a string like file:///home/ckhung/test.csv is pasted into the clipboard. Can you give more details about pasting? Thanks!
