### ISSUE TITLE
Countif() error: matches on prefix of the criteria

### ISSUE THREAD

**Issue by iomartin** [audreyt/ethercalc#248]
countif(range, criteria), when "criteria" is text, matches on any string that starts with "criteria".

For example, countif(range, "x") matches on x, xx or xfoo.

**Comment by audreyt** [comment]
This is intentional and conforms to http://docs.oasis-open.org/office/v1.2/os/OpenDocument-v1.2-os-part2.html#Criterion

Please use `countif(range, "=x")` for the equivalence test.
