### ISSUE TITLE
multiple copy/paste formula has weird results

### ISSUE THREAD

**Issue by joequant** [audreyt/ethercalc#261]
create formula in 

c8 = c6 \* c5

Copy the formula and the paste into three vertical cells.  The second cell has the formula correctly shifted, but the third cell copies the formula in the second cell (i.e. c9 = c7 \* c6) rather than (c10 = c8 \* c7)

**Comment by eddyparkinson** [comment]
To re-create:
 copy the formula in  cell C8 `=C6*C5` (ctrl+c or toolbar icon)
 Select cells C9 and C10 and paste (ctrl+v or toolbar icon)
cell C10 contains `=C7*C6`

workaround - use drag handles rather than selecting paste range

**Comment by eddyparkinson** [comment]
fixed
