### ISSUE TITLE
Ethercalc version history

### ISSUE THREAD

**Issue by speendo** [audreyt/ethercalc#271]
Hi!
I and thank you for this great project!
I hope this is not a stupid question, but I don't get how to handle the version history on my own installation.

On ethercalc.orgthere is this greenish button that gets me to https://ethercalc.org/log/?<name>. However, this does not work for files with multiple sheets (when the sheet is called https://ethercalc.org/=multisheet, the green button brings me to https://ethercalc.org/log/? instead of https://ethercalc.org/log/?=multisheet, same holds for entering the address manually).

Also on my own installation, I don't have that button and http://domain/ethercalc/log/?<name> does not work.

How can I access the history
1. for multi-sheet-documents
2. on my own server (for single- and multi-sheet-documents)?

Thank you in advance!

**Comment by audreyt** [comment]
Hi! The greenish button issue with individual sheets in a multisheet is now fixed — https://ethercalc.org/log/?multi.2 now works. Thanks for the feedback!

The ethercalc-log codebase is currently not yet production-grade — it creates each revision as a file and puts undue strain on the filesystem.

I’ll rework the ethercalc-log backend to use Git only and let you know when it’s ready for installation.

**Comment by speendo** [comment]
I see. Thank you very much!

**Comment by bkuehhnle** [comment]
Any progress here?  I'd love to see the history!  Will help if possible.

**Comment by audreyt** [comment]
Hi — The log functionality is now a separate project EthercalcRevisionTool maintained by Framasoft. Please see https://git.framasoft.org/framasoft/ert for details. :-)

**Comment by bkuehhnle** [comment]
Thank you Audrey! I'll check it out.
