### ISSUE TITLE
Customize Startpage

### ISSUE THREAD

**Issue by xshadow** [audreyt/ethercalc#277]
Hey @audreyt, 

thanks for this amazing piece of software. 

I'm writing an [ansible role](http://www.ansible.com/) for it and I will opensource it when I'm done. So users can do automated installs on dedicated systems. 

Is there a way to customize the start page? 

I edited start.html with my own text, but changes aren't honored in any way.

**Comment by audreyt** [comment]
Please change the timestamp using `make manifest` (or manually change `manifest.appcache`) after making a change. Thanks!

**Comment by xshadow** [comment]
I tried both. Did not have any effect on the cached startpage. Any clues? 

I did the following:
> edited ethercalc/start.html
> make manifest

**Comment by audreyt** [comment]
...and restarted the node server?

**Comment by xshadow** [comment]
On 02.12.2015 16:12, 唐鳳 wrote:
> ...and restarted the node server?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/audreyt/ethercalc/issues/277#issuecomment-161328026>.
> 

Yes, I did but my changes are only present if I run the application via
nodeserver aka node server.js

if I do an, when the content is altered,

service ethercalc restart

The old content comes present again. Sorry if my questions are stupid.

-- 
best regards | viele Gruesse, shadow@systemli.org

receive my key:
gpg --keyserver zimmermann.mayfirst.org --recv-keys 0x5C6B6ED4248C1F32

**Comment by audreyt** [comment]
Then maybe `manifest.appcache` is served from somewhere else, e.g. from a static directory?

Try removing `manifest.appcache` from disk altogether?

Alternately disable caching in the browser and see if it helps?

**Comment by xshadow** [comment]
On 02.12.2015 16:55, 唐鳳 wrote:
> Then maybe |manifest.appcache| is served from somewhere else, e.g. from
> a static directory?
> 
> Try removing |manifest.appcache| from disk altogether?
> 
> Alternately disable caching in the browser and see if it helps?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/audreyt/ethercalc/issues/277#issuecomment-161342825>.
> 

Thanks for your help.

I found my mistake.

Had to update the page, recreate the appcache.manifest and after that
install the npm package.

I'll let you know when I'm done with porting the install to ansible. I
will open source the role soon :)

yours shadow

-- 
best regards | viele Gruesse, shadow@systemli.org

receive my key:
gpg --keyserver zimmermann.mayfirst.org --recv-keys 0x5C6B6ED4248C1F32

**Comment by xshadow** [comment]
Thanks for your help.

As I promised I created an ansible-role:

https://github.com/systemli/ansible-ethercalc
https://galaxy.ansible.com/detail#/role/6657


cheers shadow // systemli.org

-- 
best regards | viele Gruesse, shadow@systemli.org

receive my key:
gpg --keyserver zimmermann.mayfirst.org --recv-keys 0x5C6B6ED4248C1F32
