### ISSUE TITLE
Add option to not display the warning

### ISSUE THREAD

**Issue by dest4131** [audreyt/ethercalc#278]
Dear community,
when sharing a spreadsheet with other people, on first launch, they get the same warning popup the creator of the sheet had (e.g. "your calc will be deleted after a year..."). It's a puzzling and unpleasing experience. The warning should not be modal in my opinion. An icon somewhere with an exclamation mark would be fine.

**Comment by audreyt** [comment]
Thanks for your report. This is a @framasoft specific addition; EtherCalc has no such modal warning. Please file an issue at:

https://git.framasoft.org/framasoft/framacalc/issues
