### ISSUE TITLE
export function does not work properly when /edit & /view is on

### ISSUE THREAD

**Issue by JaaZC** [audreyt/ethercalc#281]
Hi, it seems that when I turn on the edit/view option the export function adds /[name of sheet].(html, csv,xlsx) to the request instead of just adding the extension. Don't know if I'm the only one who's experiencing this. Thanks

**Comment by eddyparkinson** [comment]
Fixed in #451 
All looks to work correctly.

e.g
http://sheet.cellmaster.com.au/examples/view
produces
http://sheet.cellmaster.com.au/examples.html
