### ISSUE TITLE
Ethercalc doesn't produce valid and/or usable Excel sheets.

### ISSUE THREAD

**Issue by noci2012** [audreyt/ethercalc#285]
It produces something that can be downloaded, Both Excel and Libreoffice don't understand the files produced.

**Comment by audreyt** [comment]
Is this a multiple-sheet (with tabs at the bottom) case with just one "Sheet1"?

If so please try a workaround of renaming Sheet1 to something else with the bottom-right "Rename..." function. If not so please attach an example URL

**Comment by noci2012** [comment]
both

**Comment by noci2012** [comment]
Any news?

**Comment by audreyt** [comment]
Indeed they seem to be corrupt — even in individual .xlsx downloads — but I'm not yet able to figure out why. Let me take another look this Sunday; thanks for your patience!

**Comment by noci2012** [comment]
Any progress? anything i can do?

**Comment by audreyt** [comment]
Hi, this should be fixed in http://ethercalc.net/ethercalc-201601226.spk which I’ve just submitted to the App Market.

Cheers,
Audrey

**Comment by noci2012** [comment]
When do you expect it to become available? The sept. 1st version is still there.

**Comment by audreyt** [comment]
You can download the `.spk` and manually upgrade your Sandstorm instance with "Upload SPK" in the Apps tab.

As for its availability in the App Marketplace — cc @kentonv

**Comment by noci2012** [comment]
I tried the spk. the grain is updated, now i dont get any data from the sheets.
After download and reading the resulting .xlsx into LibreOffice 5.0.3.2 there is no error,
but also no data. i tried both a single page as well as a multi page sheet.

**Comment by noci2012** [comment]
I unpacked an .xlsx  and none of the data from the sheet can be found

**Comment by kentonv** [comment]
(Sorry for the delay, new .spk has been approved in the app market.)

**Comment by noci2012** [comment]
Tried it using Excel, still produces an invalid fail that cannot be opened ( how to reopen the issue?)

**Comment by audreyt** [comment]
Would you like to try creating a new spreadsheet and carry over the original data from the existing grain? (I too have problems upgrading existing grains — it seems they keep using the old code.) — the "Clipboard" tab can be used to transfer data.

**Comment by noci2012** [comment]
hm. If i backup the grain and then restore it..
Excel: Error message about problems in sheets all formula's & formatting are missing.  and NaN is for formula's shown, name of first sheet changed to sheet1
LibreOffice 5: No error message, Formatting gone, formula's changed to NaN. Name of first sheet changed to Sheet1

All other sheets retained their original name.

**Comment by audreyt** [comment]
Would you mind sending the backup to audreyt@audreyt.org ? I can take a
look tonight.

noci2012 <notifications@github.com> 於 2016年1月25日週一 16:59 寫道：

> hm. If i backup the grain and then restore it..
> Excel: Error message about problems in sheets all formula's & formatting
> are missing. and NaN is for formula's shown, name of first sheet changed to
> sheet1
> LibreOffice 5: No error message, Formatting gone, formula's changed to
> NaN. Name of first sheet changed to Sheet1
>
> All other sheets retained their original name.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/audreyt/ethercalc/issues/285#issuecomment-174553966>.
>
-- 

Cheers,
Audrey

**Comment by noci2012** [comment]
Sent a mail

**Comment by noci2012** [comment]
The behaviour of a restored grain and an upgraded grain is the same.
The same holds for copy/pasted sheets to a new grain. After download they all produce the same result.  Nan in the place of String resulting fomula's and plain values for numeric formula's

**Comment by audreyt** [comment]
@noci2012 I had not receive the mail yet. Perhaps paste a URL to a backup here if you don't mind...

**Comment by noci2012** [comment]
https://noci.sandcats.io/shared/4PSs92Swg_qk3Cze1B_CeadswUSMikXVof5EpZi6lqm

**Comment by noci2012** [comment]
In recent versions: excel Errormessage about errors (one per sheet)  and all formula's & formatting gone. 
In LibreOffice Calc: no errors, and also no formula's. (I think formula's have their own store in the result.

**Comment by noci2012** [comment]
inactive, closing old stuff
