### ISSUE TITLE
CSS and inline CSS

### ISSUE THREAD

**Issue by willhallonline** [audreyt/ethercalc#290]
Hey. Great work on the repo. I was wondering how much of the CSS we could strip out of being inline and move it to static/socialcalc.css?

I am also looking at doing this to fork of the original socialcalc repo https://github.com/infojunkie/socialcalc which is hopefully going to make socialcalc easier to "style". Would I be better doing it here, or on the fork or looking at getting it onto the original socialcalc repo https://github.com/DanBricklin/socialcalc?

**Comment by audreyt** [comment]
The SocialCalc side is the same, so if you fork the original we should still be able to merge, and vice versa. Thanks for looking into this!

**Comment by willhallonline** [comment]
OK... What I am trying to judge is whether it is better to do it on the original (DanBricklin)? Or the most recently used fork (infojunkie/ethercalc) or a new fork?

**Comment by audreyt** [comment]
If you can make it work at the original, please do, and paste also the pull request URL here (or reference to this issue) and I'll take care of merging it to ethercalc.
