### ISSUE TITLE
Freezing Top Row while scrolling through the rest of the worksheet

### ISSUE THREAD

**Issue by ashishkataria** [audreyt/ethercalc#315]
Comparing to Microsoft Excel, we can Freeze Top Row.
Keep the top row visible while scrolling through the rest of the worksheet.
This would be very important in usage as:
When scroll down to some ROW, the Header ROW doesn’t remain visible and after typing in row cell one has to come to the Top Row to confirm whether it is the correct column.  The option available in EXCEL sheets to  Freeze the  top row  when one scrolls down.

**Comment by audreyt** [comment]
This is already implemented, please simply drag the splitter on the top of
vertical sctollbar downward.

Ashish Kataria <notifications@github.com> 於 2016年2月24日週三 01:57 寫道：

> Comparing to Microsoft Excel, we can Freeze Top Row.
> Keep the top row visible while scrolling through the rest of the worksheet.
> This would be very important in usage as:
> When scroll down to some ROW, the Header ROW doesn’t remain visible and
> after typing in row cell one has to come to the Top Row to confirm whether
> it is the correct column. The option available in EXCEL sheets to Freeze
> the top row when one scrolls down.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/audreyt/ethercalc/issues/315>.
>
-- 

Cheers,
Audrey

**Comment by ashishkataria** [comment]
Thanks.

**Comment by leafcutterant** [comment]
> please simply drag the splitter on the top of vertical sctollbar downward.

I drag it down, I release it where I want the frozen range to end, but it simply doesn't freeze it. It all moves when scrolling down. What am I doing wrong?

**Comment by eddyparkinson** [comment]
@leafcutterant 
Have you a screenshot or something? It works fine for me.

**Comment by leafcutterant** [comment]
@eddyparkinson 
Sorry, now it works for me too. I don't know what stopped me back then, it was clearly not working, now I can freeze easily.
