### ISSUE TITLE
how to create multiple sheets

### ISSUE THREAD

**Issue by menglu628** [audreyt/ethercalc#316]
I want to create multiple sheets,I see there are serveral issues about multi-sheet,so I think it can create,which parameter I need set or other methods?

**Comment by audreyt** [comment]
Just add a `=` before the name of the sheet like `/=foobar` , or drag-and-drop to upload a multisheet file.

**Comment by menglu628** [comment]
I don't know the version I download can create multiple-sheets or not,but I can't write the name of the sheet,there just can write the name or value of the cell.
![1](https://cloud.githubusercontent.com/assets/17695019/13562207/d10b60ea-e470-11e5-9061-e0dcdaf3e426.png)

**Comment by audreyt** [comment]
I do not recognize this version, maybe it is re-packaged, in which case please contact your operator.

**Comment by RainerBielefeld** [comment]
Unfortunately in Comment [Mar 7, 2016](https://github.com/audreyt/ethercalc/issues/316#issuecomment-193120064)a hint is missing where to add that name. 

Can someone please explain how to add a sheet to [this ethercalc spreadsheet](https://ethercalc.net/3cxew10za0u3)? 
I know that Ethercalc CAN handle multiple sheets from [this spreadsheet](https://ethercalc.net/=4eo2j7v6l2), which has been created by upload of an existing .ods.. But in a newly created spreadsheet I have no Idea where and how to create new sheets.

**Comment by SarahFdL** [comment]
> Unfortunately in Comment [Mar 7, 2016](https://github.com/audreyt/ethercalc/issues/316#issuecomment-193120064)a hint is missing where to add that name.
> 
> Can someone please explain how to add a sheet to [this ethercalc spreadsheet](https://ethercalc.net/3cxew10za0u3)? 

You have to write = in the url

**Comment by RainerBielefeld** [comment]
@SarahFdL
Can you please contribute a step by step instruction how to add a second sheet to <https://ethercalc.net/3cxew10za0u3>?  
I did some tests:
a) https://ethercalc.net/=3cxew10za0u3 creates a new (or opens an existing?) spreadsheet document with sheets "Sheet1", "2.99", "4.99"
b) (https://ethercalc.net/=) opens an existing spreadsheet with 4 sheets.

So: How can I add a Sheet to  <https://ethercalc.net/3cxew10za0u3>? 

CU

Rainer

**Comment by SarahFdL** [comment]
Hi, yes, it seams like there are some bugs (but I see there is no more contributions)...
1/ create a new spreadsheet with a random free name, beginning with =
2/ copy your content from 3cxew10za0u3 to the new one, which has the possibility to add sheets

I do not have test a lot for the moment

**Comment by eddyparkinson** [comment]
https://ethercalc.net/=   is multi sheet mode.  This was an addition that groups sheets. But regardless of mode, all sheets can reference each other. All sheets can reference each other regardless of if they are multi sheet style or not. 

If you hunt around, you can find details of how multi sheets and referencing other sheets is done.

**Comment by RainerBielefeld** [comment]
All I wanted is an step by step instruction how to add a second sheet to https://ethercalc.net/3cxew10za0u3

Nothing else!

**Comment by eddyparkinson** [comment]
Sorry, that is not possible.

Why do you want to add another sheet? What is the problem you want to solve. Just add a new sheet and add references as you would normally. You should get the same result. Or do you need to export? 

You can create a new sheet with any name you want, you don't need to use a randomly generated sheet name.

**Comment by RainerBielefeld** [comment]
Well, that's why I dropped ethercalc: Yoh never get an answer.

**Comment by SarahFdL** [comment]
> Well, that's why I dropped ethercalc: Yoh never get an answer.

You have the answer : it is not possible. But we gave to you another way to do what you want

**Comment by eddyparkinson** [comment]
I understand you are not impressed. Open source is tough, often it is unpaid people who have a passion. With enough enough demotivating comments, I expect the passion will dwindle and people will walk away.

**Comment by mythsmith** [comment]
- Select the region with the data
-  Copy the region
- Create a new empty ethercalc
- Add = sign before the unique identifier in the url, so that you have many sheets
- Paste the data you previously copied
