### ISSUE TITLE
Set a cell background color with a formula

### ISSUE THREAD

**Issue by sank64** [audreyt/ethercalc#319]
Is it possible to set one cell's background color with a formula taking an rgb or hexa value?

Eg. `=set.bgcolor(foobar)`

**Comment by sank64** [comment]
Combined with a if function, it will make possible to a conditional formatting.

**Comment by audreyt** [comment]
This can already be done with a `html` text formatted cell that uses `=IF` conditioning that outputs different CSS styles, though the background would be limiting to the cell content, not the entire cell.

**Comment by sank64** [comment]
Could you give me an example /or/ tell me where this is documentated /or/ which script do that ?

**Comment by sank64** [comment]
Found it! This is amazing !!

**Comment by sank64** [comment]
I found it Audrey! This is amazing!

**Comment by audreyt** [comment]
https://ethercalc.org/issue-319

**Comment by sank64** [comment]
I am going to edit the wiki

**Comment by sank64** [comment]
https://github.com/audreyt/ethercalc/wiki#color-a-cell-depending-of-its-value-aka-conditional-formating-
