### ISSUE TITLE
Do not split words while resizing a cell

### ISSUE THREAD

**Issue by maloy-ghosh** [audreyt/ethercalc#322]
If we resize a cell (by dragging), the contents in the cell gets oriented to justify new size. However during this new orientation, words are splitted at the edge. Won't it be nice not to split the words at the edges?

**Comment by audreyt** [comment]
Well, that was responding to #32 and #26... Ideas welcome on how to reconcile the two needs.

**Comment by eddyparkinson** [comment]
Use the google docs solution? 

 - **clip long words** and wrap short words without splitting
 - offer cell: **wrap, clip and span** as cell formatting options.

**Comment by eddyparkinson** [comment]
Remove "break-all" ?

#te_fullgrid td {
    overflow: hidden;
    word-break: break-all;
    word-wrap: break-word;
}

I will remove the word-break: break-all; 
On chrome  - this results in: it splits long words and wraps short words without splitting
