### ISSUE TITLE
Negative sign improperly implemented?

### ISSUE THREAD

**Issue by zipspeed** [audreyt/ethercalc#323]
=-1>1 yields FALSE
=1>-1 yields Error in formula (two operators inappropriately in a row)

**Comment by audreyt** [comment]
Reproduced, thanks for the report. The error is near formula1.js line 405 — it probably needs a similar treatment for unary minus like in line 374. Pull reqs welcome.

**Comment by eddyparkinson** [comment]
fixed & tested - looks to work ok now. Closing issue.
