### ISSUE TITLE
Separate repo and npm package for socialcalc?

### ISSUE THREAD

**Issue by marcelklehr** [audreyt/ethercalc#324]
Hey,

I'd like to use socialcalc separately from ethercalc and don't want to just copy the files.
In my opinion it would make sense to put socialcalc into its own repository and npm package.
What do you think?

**Comment by audreyt** [comment]
Sure. We forked from https://github.com/DanBricklin/socialcalc initially. Feel free to re-fork that, sync the EtherCalc changes, and package to npm, and let us know here, so I can start depending on you as the upstream. :-)

**Comment by ocdtrekkie** [comment]
With recent demonstrations of the risks inherent to using a lot of dependencies, I'd be inclined to suggest moving a large portion of fundamental code out of this project to a dependency managed by someone else is maybe not ideal.

**Comment by audreyt** [comment]
We're all contributors here, so we can also share commit rights to the new socialcalc repo if needed.

Also the `npm unpublish` bug is fixed, so as long as ethercalc depends on a version-specific `socialcalc` package there shouldn't be the same risk occuring again.

**Comment by marcelklehr** [comment]
I'll gladly add you as contributors. Which version should I give it?

**Comment by audreyt** [comment]
Internally we used to call this `SocialCalc 2.0` so maybe `2.x.y` where x.y is anything that makes sense to you (Semver-wise)?

**Comment by marcelklehr** [comment]
Ok, then I'll just use `2.0.0` as it'll be the first version with a version number.

**Comment by marcelklehr** [comment]
[Published!](https://www.npmjs.com/package/socialcalc) Thanks for your help.

**Comment by marcelklehr** [comment]
I think player-broadcast would also be useful. Do you think adding it to the socialcalc package is a good idea? Alternatively, it could go in a separate package, of course.

**Comment by audreyt** [comment]
Let's keep `socialcalc` to the engine as people may wish to use it in the backend. Feel free to start moving the other parts into separate npm packages and repors.
