### ISSUE TITLE
insert carriage return in cell

### ISSUE THREAD

**Issue by pyg77** [audreyt/ethercalc#329]
Hello, I looked in the docs and in the issues lists but couldn't find the answer: is it possible to add a carriage return (newline) in a cell?

**Comment by audreyt** [comment]
Yes, click the multi line input toggle bext to the input box and formula
button.

Pierre-Yves Gosset <notifications@github.com> 於 2016年4月15日週五 17:02 寫道：

> Hello, I looked in the docs and in the issues lists but couldn't find the
> answer: is it possible to add a carriage return (newline) in a cell?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/audreyt/ethercalc/issues/329>
>
-- 

Cheers,
Audrey

**Comment by eddyparkinson** [comment]
**HTML new line** 
You can use HTML to show a newline in a cell

e.g.
'hello<br>line 2

and set the cell format to HTML

e.g. http://sheet.cellmaster.com.au/example_html

**Comment by GMTSE** [comment]
Hi thanks for the answer, 
But I'm already formatting my text as [WikiText](https://en.wikipedia.org/wiki/Help:Wikitext#Lists), which is supposed to be an accepted Cell format in Ethercal , but which needs \n for interpreting correctly the formatting.
For instance, if I want my * to be interpreted correctly as items, I need to put them at the beginning of the line. How can I do that ?

**Comment by eddyparkinson** [comment]
I don't think it is possible with WikiText.  HTML is the simplest work around https://www.w3schools.com/html/html_lists.asp


https://github.com/audreyt/ethercalc/blob/master/third-party/wikiwyg/lib/Document/Parser/Wikitext.js#L81
this suggests it checks of \n

you could swap the \n for anther char maybe.   e.g. \ or $ 


https://github.com/DanBricklin/socialcalc/blob/master/socialcalctableeditor.js
or edit this code to allow alt+enter to store \n like other spreadsheets do.
