### ISSUE TITLE
Importing/Exporting Heavily Formatted xlsx File

### ISSUE THREAD

**Issue by juandiegopalomino** [audreyt/ethercalc#330]
Hi there,

So I have this xlsx template file that I would like to import to ethercalc (which is working fine otherwise). The file has several different colors, formulas, merged cells, and a couple of fonts. After the import however, the formatting all-but vanishes. Similarly, if I try to export a formatted file (e.g. with merged rows and colors), the formats there also vanishes. Is there anyway to counteract this? Thank you!

**Comment by audreyt** [comment]
That is a limitation of our current conversion technology from SheetJS: https://github.com/SheetJS/js-harb — improvement from the upstream is automagically available here — or we can switch to a more comprehensive conversion layer if it exists — which are outside ethercalc scope so I'd have to close this ticket, but please feel free to share discussion and links etc here.

**Comment by Felzomah** [comment]
It seems the professional version of sheetjs supports formattings.
Can ethercalc work with the professional version of sheetjs?

**Comment by eddyparkinson** [comment]
@Felzomah I don't know, you would need to try it. There is a good chance it would work. They have a good set of tests to ensure everything is in good working order, so I would assume it is compatible.

Also this version has support for formatting https://github.com/orgs/quilt-js/people/pietersv
He may know the differences between the versions.
