### ISSUE TITLE
Route to delete Room

### ISSUE THREAD

**Issue by Higor1104** [audreyt/ethercalc#331]
How does the "DELETE" method works to delete a Room? because i've tryied once with almost the same structure of GET to create a page but using the DELETE method, i got a 404 Not Found.

**Comment by audreyt** [comment]
DELETE `/_/room` is the API. Is that not working? Would you like to paste the curl command (browser -> network -> copy as cURL)?

**Comment by Higor1104** [comment]
hmm. i've forgotten the underscore before the last slash. i was typing http://localhost:8000/<room_id>.
