### ISSUE TITLE
How can I make my sheet on readony mode from an url ?

### ISSUE THREAD

**Issue by hamdijmii1992** [audreyt/ethercalc#332]
Can I make my sheet on read only mode by passing some specific attributes to the url sheet ?
For example . http://X.X.X.X/id_sheet [specific attributes ...]

**Comment by audreyt** [comment]
Add /view to it. Example: https://ethercalc.org/test/view
On 2016年4月20日 週三 at 16:17 hamdijmii1992 <notifications@github.com> wrote:

> Can I make my sheet on read only mode by passing some specific attributes
> to the url sheet ?
> For example . http://X.X.X.X/id_sheet [specific attributes ...]
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/audreyt/ethercalc/issues/332>
>
-- 

Cheers,
Audrey

**Comment by hamdijmii1992** [comment]
Thank you very much @audreyt

**Comment by PhilLAL** [comment]
Hi Audrey,
however, it seems however one can delete /view" to modify it. 
Isn't it ?

**Comment by eddyparkinson** [comment]
I understand sandstorm supports sharing as read only https://apps.sandstorm.io/app/a0n6hwm32zjsrzes8gnjg734dh6jwt7x83xdgytspe761pe2asw0

but yes, ethercalc could do with something like https://github.com/jaredhanson/passport adding to it.

**Comment by kevev** [comment]
How would I do text actually verticle. Example: https://stackoverflow.com/questions/6759870/tcpdf-rotate-text-cell-in-table-header
