### ISSUE TITLE
broken /view suffix for installations into non-root (non-standard) directories

### ISSUE THREAD

**Issue by ckhung** [audreyt/ethercalc#333]
I am running the pre-built docker version of ethercalc on lubuntu 15.04. I need apache for other tasks. So I have these in my /etc/apache2/conf-enabled/ethercalc.conf : 
```
ProxyPass /ecalc http://localhost:8000
ProxyPassReverse /ecalc http://localhost:8000
```
References to http://localhost/ecalc/ are redirected to http://localhost:8000 behind the scenes. This works fine most of the time, including .html or .csv suffixes for export/download. However it fails with _new and with /view suffix (for read-only mode). Can this be fixed by changing some code from absolute path to relative path? Thanks!

**Comment by audreyt** [comment]
Pass in `--basepath /ecalc` would fix this problem. You can build your own image with this Dockerfile:

FROM audreyt/ethercalc
CMD ["sh", "-c", "REDIS_HOST=$REDIS_PORT_6379_TCP_ADDR REDIS_PORT=$REDIS_PORT_6379_TCP_PORT pm2 start -x `which ethercalc` -- --cors --basepath /ecalc && pm2 logs"]


or `docker run` with `ethercalc --cors --basepath /ecalc`

**Comment by C-Duv** [comment]
I've tried the `--basepath` option without luck on a Nginx:

_Dockerfile_:
```
FROM audreyt/ethercalc
CMD ["sh", "-c", "REDIS_HOST=$REDIS_PORT_6379_TCP_ADDR REDIS_PORT=$REDIS_PORT_6379_TCP_PORT pm2 start -x `which ethercalc` -- --cors --basepath /calc && pm2 logs"]
```

_Nginx_:
```
location /calc { # To EtherCalc
    proxy_pass http://127.0.0.1:6003;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}
```

@ckhung: did it worked for you?
