### ISSUE TITLE
ethercalc container doesnt connect to redis container in vagrant machine

### ISSUE THREAD

**Issue by stavros-liaskos** [audreyt/ethercalc#334]
Vagrantfile:
open port: config.vm.network "forwarded_port", guest: 8000, host: 8080
install docker: config.vm.provision "docker" do |d|
  end

in vagrant machine: uname -r
3.13.0-85-generic

docker version:
1.11.0

then I run:
sudo docker run --name redis -d -v /var/lib/redis:/data redis:latest redis-server --appendonly yes
and
sudo docker run -d -p 8000:8000 --link redis:redis audreyt/ethercalc

docker ps:
16c95dc69a98        audreyt/ethercalc   "sh -c 'REDIS_HOST=$R"   4 seconds ago       Up 3 seconds        0.0.0.0:8000->8000/tcp   sad_saha
f7911ed4d118        redis:latest        "/entrypoint.sh redis"   10 seconds ago      Up 9 seconds        6379/tcp                 redis

so now when I open http://127.0.0.1:8080/ from my machine, Ethercalc is opening,but in the VM the dump.json is created which means its not connected to redis container.

I tried without docker containers and its fine but I really want to get this beauty running in containers.

So did I forget something or what?

**Comment by audreyt** [comment]
That actually looks correct. Did you wait for a bit for `redis` to start up before running EtherCalc? Usually I use `redis-cli ping` or equivalent to ensure it's started up. Maybe it takes more than 6 seconds.

Also are you on Mac OS X? Perhaps give `dlite` a try?

**Comment by stavros-liaskos** [comment]
Thanks for the quick reply. Well, what can I say. magic of computers. I was trying this for days and it's just working now. Maybe I wasn't waiting enough and after it creates the dump.json file you need to do  delete it or do a bit of config.Feel free to close/delete this one as useless
