### ISSUE TITLE
Graphs not working in Sandstorm port

### ISSUE THREAD

**Issue by zeigerpuppy** [audreyt/ethercalc#339]
The graph functions don't appear to be working on sandstorm, there is nothing in the drop down to select chart type and no graph renders.

**Comment by eddyparkinson** [comment]
Agree - graphs hit a localization bug.

Looks to be this change,  execution order issue :
https://github.com/audreyt/ethercalc/commit/5cf0c6aceeeed8660743bf491befa2ef58cc4ca4

Fix: change player-graph.ls:

@include = -> @client '/player/graph.js': ->
  $ = window.jQuery || window.$
  return location.reload! unless $
  SocialCalc = window.SocialCalc || alert 'Cannot find window.SocialCalc'

  SocialCalc.Constants.s_loc_horizontal_bar = "Horizontal Bar"   
  SocialCalc.Constants.s_loc_vertical_bar ="Vertical Bar"   
  SocialCalc.Constants.s_loc_pie_chart = "Pie Chart"    
  SocialCalc.Constants.s_loc_line_chart = "Line Chart"    
  SocialCalc.Constants.s_loc_scatter_chart = "Scatter Chart"
  SocialCalc.Constants.s_loc_hide_help = "Hide Help"
 
  colorIndex = 0

**Comment by eddyparkinson** [comment]
I pushed a fix for this to master.

**Comment by audreyt** [comment]
Thanks! Release to npm as `0.20160501.1` and also to Sandstorm (awaiting app store review).

**Comment by zeigerpuppy** [comment]
Thanks, looking forward to using graphs!
