### ISSUE TITLE
Unexpected behavior when adding rows within span of merged cell

### ISSUE THREAD

**Issue by amir-zeldes** [audreyt/ethercalc#341]
When adding a row at a position that is inside the span of a merged cell covering several rows, the merged cell does not update to end one row further below: instead the merged cell continues to end at the same row number as before. This creates a 'shortfall', or also a gap between consecutive merged cell. 

To illustrate, consider the following example: a user wishes to add a transaction to a list of transactions, which is continuously spanned by quarter and year columns to the right:

![ethercalc_before_insert](https://cloud.githubusercontent.com/assets/2188635/14825982/f60e0d56-0ba9-11e6-8bb8-958c51e2b02f.png)

If the user now inserts a new transaction record row below row 4 (between transactions C and D), the expected behavior, as in popular desktop spreadsheet editors, is for the quarter and year spans to adjust to end one row further below. However, the actual behavior creates gaps in columns 2 and 3, as shown here:

![ethercalc_after_insert](https://cloud.githubusercontent.com/assets/2188635/14826019/206e3c7e-0baa-11e6-9b88-c1da4fb0d2e9.png)

If there are many columns, with different length spans, this can be very difficult and cumbersome to correct.

**Comment by marcelklehr** [comment]
@eddyparkinson The insertcol/deletecol/insertrow/deleterow commands would have to be fixed, to do some kind of collision detection... Is there an attribute that we could use to know whether a cell is part of a merger? Otherwise we'd have to devise some algorithm to efficiently determine affected mergers. Worst case is O(n), where n is the number of cells above/left of the inserted row/column.

**Comment by eddyparkinson** [comment]
>Worst case is O(n)

Agree - also looks like your worst case suggestion looks like the one to use.

Command:
**merge J2:J4
**
Sets the rowspan and colspan of the cell J2 - nothing else looks to be changed.

**Comment by amir-zeldes** [comment]
Hi again - not sure if there's already been progress on this or whether this relates to the relevant attributes in the data model, but in case it's helpful: the socialcalc format outputted by the REST API seems to suggest that merge areas are retrievable as col/rowspans for the specific cells. For example in the image above:

```
cell:B2:t:Q1:rowspan:6
```

And again, although I have no idea how this is implemented, I think what needs to be checked on insertion/deletion is the one dimension of either the row or the column (depending on whether a row or column is inserted), so it's as many tests for rowspan (or colspan) as there are columns (or rows) in the used range, where in each test we need to find the last filled cell in that dimension, get its span, and see if it overlaps with the insertion/deletion. 

Sorry if this is totally obvious and redundant - thanks for looking into this!

**Comment by marcelklehr** [comment]
@amir-zeldes Thank you for commenting! I figured out the attributes as well. You have to check all columns and rows left/above the affected range, though, because rowspan and colspan can occur at the same time.

**Comment by eddyparkinson** [comment]
`cellskip` looks to already have what is needed.

    SocialCalc.RenderCell = function(context, rownum, colnum, rowpane, colpane, noElement, linkstyle) {
     ...
      if (context.cellskip[coord]) { // skip if within a span

**Comment by marcelklehr** [comment]
@eddyparkinson Awesome! I'm relieved not to have to resort to cruel methods :)

**Comment by amir-zeldes** [comment]
Oh yes, I see, of course it can have a rowspan and colspan > 1! OK, so this sounds like there may be a solution - I hate to ask, but do you have some idea of a timeline when a fix for this might be available? I'm trying to use EtherCalc in the context of a larger project, and this feature would be an important factor in committing to this tool. 

Thanks for your help!

**Comment by marcelklehr** [comment]
@amir-zeldes I expect to get to this in the next 2 weeks. My fix will be part of [ot-socialcalc](https://github.com/marcelklehr/ot-socialcalc), though, and there will need to be an effort to integrate that in ethercalc (I'm using it [independently from ethercalc](https://github.com/hivejs/hive-editor-spreadsheet-socialcalc))

**Comment by eddyparkinson** [comment]
@amir-zeldes  will this help - it lets you set merged cells, insert rows etc. 
It lets you insert and merge with formulas and a button in a cell.

http://sheet.cellmaster.com.au/mergecells

**Comment by marcelklehr** [comment]
Sorry, the fix will be part of https://npmjs.org/package/socialcalc, of course, which should be rather easy to re-integrate in ethercalc.

**Comment by marcelklehr** [comment]
@eddyparkinson black magic \o/ ! :sparkles:

**Comment by amir-zeldes** [comment]
Hi everyone - thanks for all the useful suggestions! I wasn't aware of the advanced formula options that @eddyparkinson showed, thanks! I have a project which involves collaborative work with some rather volatile and different looking spreadsheets, so I'm not sure I could wire them all like that to behave reliably. Essentially lots of people will be adding rows at different places, and I need the spans to adjust all around.

But if the fix is going to be integrated into EtherCalc then that's great, is there someone I should talk to to help get that done?

Thanks again for all your help!

**Comment by marcelklehr** [comment]
Fixed and tested: https://github.com/marcelklehr/socialcalc/commit/c21e5658c78dc764c4444c76bfb7834f5abb6b83

I can wrap up a pull request for this repo, but I think the better way would be if ethercalc added socialcalc as a dependency.

**Comment by audreyt** [comment]
Please create a pull request for adding socialcalc as a dependency (or patching this repo, either would do).

**Comment by amir-zeldes** [comment]
That would be amazing, thank you so much!

**Comment by eddyparkinson** [comment]
Just tested - it works, closing issue.

**Comment by amir-zeldes** [comment]
Yes, I was able to confirm it too and forgot to report back - many thanks!
