### ISSUE TITLE
Not working in subdirectory with NGINX

### ISSUE THREAD

**Issue by alex9434** [audreyt/ethercalc#344]
Dear all,

I followed the sample nginx.conf in the directory ethernet/nginx to set up etherpad at domain.com/etherpad because I wanted to avoid a new subdomain because I do not have a wildcard ssl certificate. However, I only get a blank screen with the following error log form NGINX.

2016/05/02 07:47:56 [error] 613#613: *1 open() "/usr/local/share/html/ethercalc/images/sc_unlock.png" failed (2: No such file or directory), client: 192.168.102.1, server: _, request: "GET /ethercalc/images/sc_unlock.png HTTP/1.1", host: "domain.com"
2016/05/02 07:47:56 [error] 613#613: *4 open() "/usr/local/share/html/ethercalc/images/sc_unhideright.gif" failed (2: No such file or directory), client: 192.168.102.1, server: _, request: "GET /ethercalc/images/sc_unhideright.gif HTTP/1.1", host: "domain.com"
2016/05/02 07:47:56 [error] 613#613: *1 open() "/usr/local/share/html/ethercalc/static/ethercalc.js" failed (2: No such file or directory), client: 192.168.102.1, server: _, request: "GET /ethercalc/static/ethercalc.js HTTP/1.1", host: "domain.com"
2016/05/02 07:47:56 [error] 613#613: *1 open() "/usr/local/share/html/ethercalc/socket.io/socket.io.js" failed (2: No such file or directory), client: 192.168.102.1, server: _, request: "GET /ethercalc/socket.io/socket.io.js HTTP/1.1", host: "domain.com"
2016/05/02 07:47:56 [error] 613#613: *1 open() "/usr/local/share/html/ethercalc/zappa/zappa.js" failed (2: No such file or directory), client: 192.168.102.1, server: _, request: "GET /ethercalc/zappa/zappa.js HTTP/1.1", host: "domain.com"
2016/05/02 07:47:56 [error] 613#613: *1 open() "/usr/local/share/html/ethercalc/player/broadcast.js" failed (2: No such file or directory), client: 192.168.102.1, server: _, request: "GET /ethercalc/player/broadcast.js HTTP/1.1", host: "domain.com"
2016/05/02 07:47:56 [error] 613#613: *1 open() "/usr/local/share/html/ethercalc/player/graph.js" failed (2: No such file or directory), client: 192.168.102.1, server: _, request: "GET /ethercalc/player/graph.js HTTP/1.1", host: "domain.com"
2016/05/02 07:47:56 [error] 613#613: *1 open() "/usr/local/share/html/ethercalc/player/main.js" failed (2: No such file or directory), client: 192.168.102.1, server: _, request: "GET /ethercalc/player/main.js HTTP/1.1", host: "domain.com"
2016/05/02 07:47:56 [error] 613#613: *1 open() "/usr/local/share/html/ethercalc/static/socialcalc.css" failed (2: No such file or directory), client: 192.168.102.1, server: _, request: "GET /ethercalc/static/socialcalc.css HTTP/1.1", host: "domain.com"
2016/05/02 07:47:56 [error] 613#613: *5 open() "/usr/local/share/html/ethercalc/static/index.css" failed (2: No such file or directory), client: 192.168.102.1, server: _, request: "GET /ethercalc/static/index.css HTTP/1.1", host: "domain.com"
2016/05/02 07:47:56 [error] 613#613: *6 open() "/usr/local/share/html/ethercalc/static/vex.css" failed (2: No such file or directory), client: 192.168.102.1, server: _, request: "GET /ethercalc/static/vex.css HTTP/1.1", host: "domain.com"
2016/05/02 07:47:56 [error] 613#613: *1 open() "/usr/local/share/html/ethercalc/static/vex-theme-flat-attack.css" failed (2: No such file or directory), client: 192.168.102.1, server: _, request: "GET /ethercalc/static/vex-theme-flat-attack.css HTTP/1.1", host: "domain.com"
2016/05/02 07:47:59 [error] 613#613: *1 open() "/usr/local/share/html/ethercalc/images/sc_unlock.png" failed (2: No such file or directory), client: 192.168.102.1, server: _, request: "GET /ethercalc/images/sc_unlock.png HTTP/1.1", host: "domain.com"
2016/05/02 07:47:59 [error] 613#613: *6 open() "/usr/local/share/html/ethercalc/images/sc_unhideright.gif" failed (2: No such file or directory), client: 192.168.102.1, server: _, request: "GET /ethercalc/images/sc_unhideright.gif HTTP/1.1", host: "domain.com"
2016/05/02 07:47:59 [error] 613#613: *1 open() "/usr/local/share/html/ethercalc/static/ethercalc.js" failed (2: No such file or directory), client: 192.168.102.1, server: _, request: "GET /ethercalc/static/ethercalc.js HTTP/1.1", host: "domain.com"
2016/05/02 07:47:59 [error] 613#613: *1 open() "/usr/local/share/html/ethercalc/socket.io/socket.io.js" failed (2: No such file or directory), client: 192.168.102.1, server: _, request: "GET /ethercalc/socket.io/socket.io.js HTTP/1.1", host: "domain.com"
2016/05/02 07:47:59 [error] 613#613: *1 open() "/usr/local/share/html/ethercalc/zappa/zappa.js" failed (2: No such file or directory), client: 192.168.102.1, server: _, request: "GET /ethercalc/zappa/zappa.js HTTP/1.1", host: "domain.com"
2016/05/02 07:47:59 [error] 613#613: *1 open() "/usr/local/share/html/ethercalc/player/broadcast.js" failed (2: No such file or directory), client: 192.168.102.1, server: _, request: "GET /ethercalc/player/broadcast.js HTTP/1.1", host: "domain.com"
2016/05/02 07:47:59 [error] 613#613: *1 open() "/usr/local/share/html/ethercalc/player/graph.js" failed (2: No such file or directory), client: 192.168.102.1, server: _, request: "GET /ethercalc/player/graph.js HTTP/1.1", host: "domain.com"
2016/05/02 07:47:59 [error] 613#613: *1 open() "/usr/local/share/html/ethercalc/player/main.js" failed (2: No such file or directory), client: 192.168.102.1, server: _, request: "GET /ethercalc/player/main.js HTTP/1.1", host: "domain.com"

Important part of nginx is here:

        # Example for mounting under /ethercalc
        location /ethercalc {
            return 301 $scheme://$server_name$request_uri/;
        }
        location /ethercalc/ {
            proxy_pass      http://127.0.0.1:8000;
            rewrite /ethercalc(/.*) $1 break;
        }
        location /ethercalc/socket.io {
            proxy_pass      http://127.0.0.1:8000;
            rewrite /ethercalc(/.*) $1 break;
            # WebSocket support
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }

**Comment by audreyt** [comment]
Hi, that means the proxy_pass is not actually taking place. Are you placing the configuration in the correct virtual host section? Maybe the default nginx host section is intercepting all requests.
