### ISSUE TITLE
Other connection URI (port) to redis

### ISSUE THREAD

**Issue by rugk** [audreyt/ethercalc#348]
I'd like to use a different port for redis and and AUTH password. Usually both can be set in the [redis URI](https://github.com/mp911de/lettuce/wiki/Redis-URI-and-connection-details), but I see no option to set it here.
So how can I set this settings?

**Comment by eddyparkinson** [comment]
environment variables -  node environment variables
  env = process.env  [redisPort, redisHost, redisPass, redisDb, dataDir] = env<[ REDIS_PORT REDIS_HOST REDIS_PASS REDIS_DB OPENSHIFT_DATA_DIR ]>
 ---
Eddy Parkinson PhD
Software Engineering and Logistics
Mobile 0406 962 958 

New ideas pass through three periods: 1) It can`t be done. 2) It 
probably can be done, but it`s not worth doing. 3) I knew it was a good 
idea all along! - Arthur C. Clarke
 

    On Wednesday, 18 May 2016, 3:55, rugk <notifications@github.com> wrote:
 

 I'd like to use a different port for redis and and AUTH password. Usually both can be set in the redis URI, but I see no option to set it here.
So how can I set this settings?—

**Comment by rugk** [comment]
Ah you mean [this line](https://github.com/audreyt/ethercalc/blob/master/db.js#L10-L11)?
Thanks for your information. I'll try it out.
