### ISSUE TITLE
How to disable development mode?

### ISSUE THREAD

**Issue by rugk** [audreyt/ethercalc#349]
When started Ethercalc tells me:

```
Express server listening on port ... in development mode
```

So how can I switch to productive mode?

**Comment by audreyt** [comment]
`export NODE_ENV=production`

**Comment by rugk** [comment]
Thanks.
BTW when I'm already about confusing log/output messages, what does this mean?
> Zappa 0.5.0 "You can't do that on stage anymore" orchestrating the show

**Comment by audreyt** [comment]
That is just our middleware of choice announcing its existence. It's harmless.

**Comment by rugk** [comment]
Okay.
