### ISSUE TITLE
How to insert JSON API data (GET) into an EtherCalc spreadsheet?

### ISSUE THREAD

**Issue by leafcutterant** [audreyt/ethercalc#351]
Sorry if this is not the best place to ask this.

I wondered if it's possible, and if yes, then how, to insert data from a simple JSON API to a spreadsheet at https://ethercalc.net/, using the GET method. I'd really appreciate any help on this.

**Comment by audreyt** [comment]
There are two formats. Appending `.csv.json` works:

https://ethercalc.org/g0v-hackath7n.csv.json

Also cells:

https://ethercalc.org/_/g0v-hackath7n/cells

See `API.md` :)

**Comment by leafcutterant** [comment]
@audreyt, thank you very much! But I couldn't figure it out... I've read `API.md` and tried everything I found on the interface, but I'm not quite familiar with the code. Could you elaborate a bit?

I think I'm missing two things: 1) the syntax, 2) what to actually do on the web user interface, what options to use.

E.g. if I want to import certain values from https://api.coinmarketcap.com/v1/ticker/peercoin/ into certain cells, what should I do?

**Comment by audreyt** [comment]
Hmm we really need to write a Zapier adapter...

The idea is to use a POST request which will append one row:
 https://github.com/audreyt/ethercalc/issues/74#issuecomment-212011178

The code can be run in browser, in a server you own, or a triggered function (Google Cloud Function, Amazon Lambda), or a third-party service (like Zapier, but we'd need to have an adapter for that.)

**Comment by leafcutterant** [comment]
Alright, now I understand better what you wrote! I think we talk about three separate things.

What you describe is 1) how to turn EtherCalc spreadsheets into APi forms, and 2) how to append arbitrary text input to an EtherCalc spreadsheet.

What I wondered is how to have an EtherCalc spreadsheet query data from an external API, display it in one of the cells, and have it re-requested upon re-opening the spreadsheet. Is this possible?

**Comment by audreyt** [comment]
I see, you mean something like [Bound App Scripts](https://developers.google.com/apps-script/guides/bound) in Google Spreadsheet. There are various third-party EtherCalc users implementing them in-house but I don't think any pull requests have materialized yet.

Other folks please feel free to chime in. :-)

**Comment by leafcutterant** [comment]
Yes, as far as I understood the description, it's something like that. What reassures me is that I've seen this (what I described) done in Google Spreadsheets before.

If you or anyone knows of an EtherCalc host with such capabilities, share it here :)
(Maybe re-open for visibility.)

**Comment by eddyparkinson** [comment]
@leafcutterant 
re: Pull data via API
 This requires a trigger and an action. I have created a way to do a trigger and an action:

  http://sheet.cellmaster.com.au/copyvalue
 While the trigger and action are not what you asked for the framework is the same.

 If you are able to add this, I am very interested, I will help if I can. It is wanted because there is a need to link to other systems, e.g. CRM, ERP, Accounting Systems etc.
