### ISSUE TITLE
reference to a cell of another sheet

### ISSUE THREAD

**Issue by PhilLAL** [audreyt/ethercalc#354]
Hi,
ethercalc seems to allow references to cell into other sheet (https://github.com/audreyt/ethercalc/wiki) with '="sheet1"!A1'.
However, it does not seem to work, whether I use «sheet1» or the new sheet name.
Perhaps is it due to the instance I use (https://framacalc.org). 
Do you know how to solve this problem ?

**Comment by eddyparkinson** [comment]
remove the double quotes 

=sheet1!A1

or 
='sheet1'!A1

See:
https://framacalc.org/eddy2

quotes get used because of spaces etc in the sheet/file name in excel

**Comment by PhilLAL** [comment]
Thank you. Could you also give an example for multi spreadsheet ethercal please? 
If I have an ethercalc doc with sheet1 and sheet2, and into sheet2, I want to access cell B1 from sheet1...

**Comment by eddyparkinson** [comment]
='eddy3.1'!A1

where eddy3 is from https://framacalc.org/=eddy3
 and ".1" is the sheet number

e.g.  https://framacalc.org/eddy2
