### ISSUE TITLE
Content is not saved

### ISSUE THREAD

**Issue by rugk** [audreyt/ethercalc#364]
When I open a table, write something into it and later open the link again the spreadsheet is empty again. This might be related to https://github.com/audreyt/ethercalc/issues/359 or even the cause of this.

In my browser I can see that websocket messages are sent and the server also replies to them.

The Ethercalc log seems to be normal:
```
on disconnect
join [log-90zlpiv1at_formdata] [user-0.9310968267169872]
join [log-90zlpiv1at] [user-0.9310968267169872]
on disconnect
join [log-90zlpiv1at] [user-0.9310968267169872]
on disconnect
join [log-90zlpiv1at_formdata] [user-0.20042075230250056]
join [log-90zlpiv1at] [user-0.20042075230250056]
```

As you can see it even displays disconnect messages, so it clearly notices disconnects.

Anyone any ideas on how to debug this?

**Comment by eddyparkinson** [comment]
Sounds like a local bug on the setup you are using. The data is stored in redis or a file when redis is not running. 

Log, when redis is not running:

[Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379]
==> Falling back to JSON storage: dump.json
==> Restored previous session from JSON file

**Comment by rugk** [comment]
I showed you my log. :smiley: 

At the beginning there is:
```
Connected to Redis Server: localhost:SOMEPORT
Selecting Redis database 0
```

**Comment by rugk** [comment]
Now I found the issue: In my redis config I blocked (aka renamed) the command "BGSAVE". After removing this it worked.

**Comment by rugk** [comment]
You might however consider to show an error message (to the console output) when such errors happen...
