### ISSUE TITLE
Ctrl+A should mark all cells

### ISSUE THREAD

**Issue by rugk** [audreyt/ethercalc#368]
Ctrl+A currently causes Firefox to mark the text:

![selecttext](https://cloud.githubusercontent.com/assets/11966684/15800242/32012d6e-2a74-11e6-9011-897ff89e4e7a.png)

It should rather mark all cells in a sheet, so I can e.g. do `Ctrl+A` and `DEL` to clear a sheet.

**Comment by eddyparkinson** [comment]
added. 
Note: Ctrl+v pastes cell contents only, not formats. Use toolbar to paste formats.
