### ISSUE TITLE
can ethercalc support "write-only" access

### ISSUE THREAD

**Issue by wbwangk** [audreyt/ethercalc#375]
i share a ethercalc document， somebody can only write in some cell，but can not read other one write’s cell。cell‘s data is secret to other one but the writer。document creater can read all cell’s data。

**Comment by audreyt** [comment]
For a "write only" use case maybe use the form based input?

http://sheet.cellmaster.com.au/yoyoform/appeditor uses `TEXTBOX` formula to collect cells and the result is written into the `_formdata/view` namespace (view source to see how it's put together).

As for auth, we only currently support `--key` based auth (per-site) but not per-sheet authentication.

With Sandstorm.io (or with manual auth config as in `nginx/conf/nginx.conf`) we have per-sheet authentication but not per-cell ones.

**Comment by eddyparkinson** [comment]
@wbwangk can you tell me more about how you want to use it. 

Form/app options:

   http://sheet.cellmaster.com.au/yoyoform/form   new blank form/app (Clones the template)
   http://sheet.cellmaster.com.au/yoyoform/app  shared app 
   http://sheet.cellmaster.com.au/yoyoform/appeditor  edit the template

I understand that some people want a form, with data that can be updated at a later date.
They want to limit who can edit the data. Is this what you had in mind?

**Comment by wbwangk** [comment]
thank audreyt and eddyparkinson!

that almost what i want.
