### ISSUE TITLE
user guide

### ISSUE THREAD

**Issue by lancson** [audreyt/ethercalc#378]
Hello, 
is there a kind of user guide about ethercalc anywhere ? 
It could be useful  for some beginners, like me ;-)
thanks for your help 
best regards
Lancson

**Comment by audreyt** [comment]
Well we have a wiki:
https://github.com/audreyt/ethercalc/wiki

Many of the SocialCalc documentations apply to us too — might be good to use it as a structure for the wiki:
https://www.socialtext.net/help-en/SocialCalc

**Comment by ckhung** [comment]
Sure. Originally I planned to fill more info into that page and then split big chunks off later. Anyone wants to start organizing it and adding new pages now? (Digesting old issues and adding the UI instructions would be my personal priority -- after playing more with the UI when I have time.)
