### ISSUE TITLE
Import option for ethercalc

### ISSUE THREAD

**Issue by SreekeshOkky** [audreyt/ethercalc#38]
It would be nice to have an option to import xls or similar spreadsheet files to the ethercalc. It is easy to create visualization from the ethercalc.

**Comment by audreyt** [comment]
As of today's version, EtherCalc 0.20150103.1 now supports importing multi-sheet Excel (and OpenDocument Spreadsheets) via this REST API:

```bash
curl -i -X PUT --data-binary @file.xlsx http://HOST/=file.xlsx
```

The leading `=` indicates multi-sheet; in the UI it's visible at `/=file` while individual sheets are visible as `/file.1` and `/file.2` etc.

If one only needs to import the first worksheet in the Excel file, this should also work:

```bash
curl -i -X PUT --data-binary @file.xlsx http://HOST/_/file
```

**Comment by albertusgeyser** [comment]
Good Day

No implementation for a open file icon yet to make things easier?

Thank You

Albertus Geyser

**Comment by audreyt** [comment]
Not yet — designs, mockups and pull requests welcome.

**Comment by albertusgeyser** [comment]
People still doing development on product.

**Comment by eddyparkinson** [comment]
People push bug fixes. But has been a many months, maybe a year, since any feature additions.

**Comment by robertocabellon** [comment]
Import from Google Spreadsheet URL would be a great feature!
