### ISSUE TITLE
sort function not working 

### ISSUE THREAD

**Issue by lancson** [audreyt/ethercalc#381]
the sort function doesn't have any effect 
e.g. [https://framacalc.org/pB3pI60Mg4](url)

**Comment by lancson** [comment]
sorry, I did find how it works , sorry . I was just cliking on "OK" on the left hand side below "définir cellule" instead of "sort" (trier in french) a little bit on the right

**Comment by PhilLAL** [comment]
Hi Audrey,
I do not find how to make sort work in the [doc](https://github.com/audreyt/ethercalc/wiki). 
Is there anywhere some tips or examples?
Thank you.

**Comment by eddyparkinson** [comment]
Sort
----

- Sort Tab - in spreadsheet, select sort tab on tool bar
- Range to sort - select range to sort - or select sort all from dropdown
- click ok
- select Columns - Major, Minor and last
- click "sort A1:B5" button

**Comment by PhilLAL** [comment]
Thank you Eddy.
In fact, I wanted to sort all the tab according to the date into a column but keeping content consistent for each line. 
I found how to do this : 

* Sort Tab - in spreadsheet, select sort tab on tool bar
* Range to sort - select range to sort - or select sort all from dropdown (Select range to avoid column titles)
* click ok
* select Columns - Major, Minor and last (select column to sort, other will stay consistent so a line will contain the same data before and after the sort)
* click "sort A1:B5" button

**Comment by eshattow** [comment]
How to do "range includes header, exclude first row" ?
