### ISSUE TITLE
Cross-sheet references don't work

### ISSUE THREAD

**Issue by gazeto** [audreyt/ethercalc#384]
Good day everybody,

for some reason, I can't create any cross-sheet references (according to the =foo!A1 pattern explained before). There's just an error "not available". Am I too stupid or is this a bug? Any workaround?

cheers

**Comment by eddyparkinson** [comment]
From: #354 

For multi sheet style 

='eddy3.1'!A1

where eddy3 is from https://framacalc.org/=eddy3
and ".1" is the sheet number

**Comment by enemali** [comment]
so referencing by name doesn't work except by sheet number

**Comment by eddyparkinson** [comment]
There are 2 sheet style - single and multi. 

**Single**

='eddy4'!A1

where eddy4 is from https://framacalc.org/eddy4

**multi sheet**

='eddy3.1'!A1

where eddy3 is from https://framacalc.org/=eddy3
and ".1" is the sheet number

**Comment by dtygel** [comment]
Hi, we have an implementation of ethercalc, and we can't do this reference. Is it a bug or should we do some configuration?

For testing purposes, we've created this multisheet: 
https://rios.org.br:9000/=WdSdfGRKYwSP0Iv3

When we write ='WdSdfGRKYwSP0Iv3.2'!D12, it says simply "sheet unavailable".

Any hints on how to make it work as in framacalc? We own the implementation, so we can do changes in the configuration files or in the version installed.

Thanks,

daniel

**Comment by eddyparkinson** [comment]
Better to create a new issue. But sheet names are a problem, they don't use a consistent rule for every situation.

**Comment by dtygel** [comment]
Done.
https://github.com/audreyt/ethercalc/issues/649
