### ISSUE TITLE
Unhide the 1st row / column

### ISSUE THREAD

**Issue by Kwaencore** [audreyt/ethercalc#390]
Hi,
While using Chrome, Opera, Firefox and Edge, I can't unhide a row nor a column if it is before the first visible row/column of the calc (otherwise the tiny arrows works if the hidden rows / column are in the middle of the sheet).

In "Audit" form it looks like the command for hidding a column is "set N:N hide yes" (for column N) and the command for unhidding a column is "set N hide". I haven't found a way to set directly these commands to the sheets. Is there a way to set these commands ?

**Comment by eddyparkinson** [comment]
Curl will fix it, but yes it is a bug

curl -H "Content-Type: application/json" -X POST  http://sheet.cellmaster.com.au/_/aupusy8036ox -d '{"command":"set E hide"}'

when I push a new version, you will be also to send commands with formulas, e.g. 
http://sheet.cellmaster.com.au/command

**Comment by FramaJosephK** [comment]
You can also do it with javascript (in the scratchpad for example) :
```javascript
jQuery.ajax({
    type: "POST",
    url: window.location.href.replace(window.location.host,window.location.host+'/_'),
    data: JSON.stringify({command: "set A:C hide"}),
    contentType: 'application/json'
 });
```

**Comment by eddyparkinson** [comment]
fixed clash with resize col/row
