### ISSUE TITLE
Always redirects to master

### ISSUE THREAD

**Issue by rugk** [audreyt/ethercalc#391]
Even if I click on "Create spreadsheet" the latest master always redirects to the home page.
I have installed Ethercalc in a subdir.

I saw there is a RegExp determinating whether to redirect and [according to my testing](https://regex101.com/r/sY1xA5/2) it should work. But in fact it does always redirect to `_start`. There is one line written into the console, which is "Root".

Version: https://github.com/audreyt/ethercalc/commit/5918b9fd9ab8123fbdd9331b42d455c86fe14939

**Comment by audreyt** [comment]
Hi, would you like to elaborate on `installed Ethercalc in a subdir` so I can try to replicate the setup? Is it via a reverse (nginx / apache ) proxy?

**Comment by rugk** [comment]
Yes nginx reverse proxy with a configuration [similar to this one](https://github.com/ether/etherpad-lite/wiki/How-to-put-Etherpad-Lite-behind-a-reverse-Proxy#from-subdirectory-url).

I can also mail you a link to my instance if you want to have a look.

**Comment by rugk** [comment]
Oh, issue solved itself... It is now working. :smile:

**Comment by rugk** [comment]
The reason was a caching issue: The request which adds an "&auth" was cached...
