### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by rugk** [audreyt/ethercalc#392]
Please add a favicon. 

To generate favicons, which work with all devices use https://realfavicongenerator.net/.

Maybe use https://github.com/audreyt/ethercalc/issues/218#issuecomment-147573765? (Just please use a transparent background...)

**Comment by eddyparkinson** [comment]
Pull requests welcome

To add:
  #@get '/favicon.ico': -> @response.send 404 ''
  @get '/favicon.ico': sendFile \favicon.ico  #return site icon
Example here: https://github.com/eddyparkinson/cellmaster/blob/website/src/main.ls

and put "favicon.ico" into the root folder.
Example here: https://github.com/eddyparkinson/cellmaster/tree/website

**Comment by audreyt** [comment]
Awesome, thanks!
