### ISSUE TITLE
Ethercalc app for Cloudron

### ISSUE THREAD

**Issue by gramakri** [audreyt/ethercalc#399]
We made an Ethercalc app for the Cloudron (Cloudron is a platform for running web apps on a server).

I pushed an initial version to the Store - https://cloudron.io/appstore.html?app=net.ethercalc.cloudronapp. The source code for the app is at https://github.com/cloudron-io/ethercalc-app. It runs the latest published Ethercalc as of today (0.20160612.0).

Just letting you guys know that this exists since I couldn't find a mailing list :-) Is there a place where you list the available installation options?

**Comment by gramakri** [comment]
If you want to see on how this looks on the Cloudron, you can install it on the demo Cloudron. https://my-demo.cloudron.me (username: cloudron password: cloudron)

**Comment by audreyt** [comment]
Hi! Thanks for the information — please add the installation instruction next to Sandstorm at: https://github.com/audreyt/ethercalc.net/blob/gh-pages/index.html#L170 as a pull request.
