### ISSUE TITLE
Basic Auth system (for read-only / read-write access)

### ISSUE THREAD

**Issue by comm2k** [audreyt/ethercalc#4]
Thanks for the auth-work so far. We would need a stand-alone solution. As you mentioned in issue #1 if a basic auth system is required I should open a new issue - here it is ;-)
- We'd prefer not having to use a reverse proxy (I'd have to read up and set up one first etc.)
- Also we're not embedding ethercalc in another app, we're using it 'pure' :)

**Comment by felixbecker2** [comment]
Can this be put _into_ the documentation? There should it go, instead of referring from the documentation to an issue ...
