### ISSUE TITLE
dump.json wiped out

### ISSUE THREAD

**Issue by eddyparkinson** [audreyt/ethercalc#403]
Something deleted my dump.json file.
 I had a spreadsheet open with data in. It looks like the server auto restarted ethercalc
 and when it reconnected the dump.json was empty. All the data gone, all the sheets, not just the
 open sheet.

Cause: 
 I don't know the cause, but any change between
  2016-04-21 00:39:14 and 2016-07-06 13:45:24  has a good probability. 

as the error occurred soon after I merged these changes in.

**Comment by audreyt** [comment]
Hi, sorry for the data loss. If you make changes and restart using the current version, does it reset `dump.json` again?

(For production use, we still recommend Redis.)

**Comment by eddyparkinson** [comment]
This is an old issue - nothing to do with the merge. I did some testing and it looks to have always worked this way, looks like a file lock issue.

I have added a fix to my local copy, (never replace file, if it exists) will merge it in at some point.
