### ISSUE TITLE
How to select distinct cells

### ISSUE THREAD

**Issue by ldidry** [audreyt/ethercalc#409]
Hello,

Is there a way to select cells that are not nearby each other? Like A1 and C3 ?

**Comment by audreyt** [comment]
Not at the moment — the selection of `editor.range` is of `range:anchorcoord:top:bottom:left:right` form and a refactoring at `socialcalc` level into `editor.ranges` would be needed for non-rectangular selections.

**Comment by ldidry** [comment]
Ok, thank you.
