### ISSUE TITLE
Cannot execute `loadclipboard` command

### ISSUE THREAD

**Issue by atifaziz** [audreyt/ethercalc#411]
There seems to be a number of issues preventing `loadclipboard` command to be issued via the [API for posting commands][post-cmds-api].

First of all, the `loadclipboard` command seems to have been hijacked by [line 370 in main.ls][main.ls#370], which seems to have been done for [internal support][loadcb-save] of other APIs that permit [appending rows in CSV][append-csv-api] or [overwriting with SocialCalc format][put-sc]. I tried to work round that by sending `loadclipboard` as an array of one command:

    { "command": "loadclipboard ..." }

However, that still didn't work and it appears that [this condition on line 370][main.ls#370] is a bit problematic by being too broad:

    if command is /^loadclipboard\s*/

This evaluates to true whether `command` is a string starting with `loadclipboard` _or_ an array where the first element is a string starting with the same. The above line [transpiles to the following in JavaScript][main.js#606]:

    if (/^loadclipboard\s*/.exec(command)) {

Problem is that when `command` is an array, [`RegExp.exec`][reexec] will convert it to a string via `toString()` and then execute the regular expression against it. And here is what [`Array.ToString`][arrtostr] (quoting MDN) does:

> For `Array` objects, the `toString` method joins the array and returns one string containing each array element separated by commas. 

So the way to work round that seems to be to put something else as the first command, which isn't cool. What's more, even if one gets past that, it seems there's a format encoding issue later on in SocialCalc ([line 3163 of `SocialCalc.js`][scjs#L3163]):

    SocialCalc.Clipboard.clipboard = SocialCalc.decodeFromSave(rest);

This seems to cause issues when there are formulas that require colons encoded as `\c`. I can expand on that but I think this issue needs reporting at [marcelklehr/socialcalc][marcelklehr/socialcalc] instead?

[main.ls#370]: https://github.com/audreyt/ethercalc/blob/0fea2ac4efc3db4d27730ef6ee95a98856b8fce6/src/main.ls#L370
[post-cmds-api]: https://github.com/audreyt/ethercalc/blob/0fea2ac4efc3db4d27730ef6ee95a98856b8fce6/API.md#post-commands-post
[loadcb-save]: https://github.com/audreyt/ethercalc/blob/0fea2ac4efc3db4d27730ef6ee95a98856b8fce6/src/main.ls#L303
[append-csv-api]: https://github.com/audreyt/ethercalc/blob/0fea2ac4efc3db4d27730ef6ee95a98856b8fce6/API.md#append-rows-post
[put-sc]: https://github.com/audreyt/ethercalc/blob/0fea2ac4efc3db4d27730ef6ee95a98856b8fce6/src/main.ls#L303
[main.js#606]: https://github.com/audreyt/ethercalc/blob/0fea2ac4efc3db4d27730ef6ee95a98856b8fce6/main.js#L606
[arrtostr]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/toString
[reexec]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec
[scjs#L3163]: https://github.com/marcelklehr/socialcalc/blob/0e912b2a0d3866824d1503ebb83be0b08400f557/SocialCalc.js#L3163
[marcelklehr/socialcalc]: https://github.com/marcelklehr/socialcalc

**Comment by audreyt** [comment]
Indeed, the last issue (about escaping) would go to socialcalc repo.

**Comment by atifaziz** [comment]
@audreyt Cheers for merging that so promptly.

Just want to add that the following doesn't appear to be an issue:

> What's more, even if one gets past that, it seems there's a format encoding issue later on in SocialCalc ([line 3163 of `SocialCalc.js`][scjs#L3163]):

I was getting the escaping wrong between JSON and SocialCalc. In addition to colons, backslashes and line feeds need escaping as well.

[scjs#L3163]: https://github.com/marcelklehr/socialcalc/blob/0e912b2a0d3866824d1503ebb83be0b08400f557/SocialCalc.js#L3163
