### ISSUE TITLE
Backup / automatic Excel Export

### ISSUE THREAD

**Issue by OliverHi** [audreyt/ethercalc#415]
Hi,
we are using ethercalc via sandstorm and we really like it. We do really need a backup that is usable without an eithercalc/sandstorm instance. Is there any way to automatically (by some kind of script) export all sheets (/grains) as excel sheets? I could do that by hand but nobody will do that for every sheet (and every day).
If thats not possible, where is the actual data for the sheets stored? Then perhaps I could restore that on a different installation of ethercalc.

Thanks a lot!

**Comment by audreyt** [comment]
Hi, each sheet is stored in a `dump.json` file. So on the filesystem level you can back them up easily:

```bash
ls /opt/sandstorm/var/sandstorm/apps/*/dump.json
```

Please see https://docs.sandstorm.io/en/latest/administering/backups/#to-back-up-one-individual-grain for more related information.

 It is also possible to export them using the REST API, namely `GET /_/sheetname` or `GET /_/sheetname.xlsx` etc. Please see #335 for a sample REST request.
