### ISSUE TITLE
Source maps not working properly

### ISSUE THREAD

**Issue by EmbeddedMike** [audreyt/ethercalc#418]
They work properly on the cellmaster fork, but not Ethercalc.
@eddyparkinson -- you might know why your fork works, and Audrey's does not.

**Comment by eddyparkinson** [comment]
unminify
---

I use unminify in Chrome - unminify - http://elijahmanor.com/7-chrome-tips-developers-designers-may-not-know/


Makefile 
---

I suspect it needs to re-compile as these lines in the Makefile create the source map

     node node_modules/zappajs/node_modules/uglify-js/bin/uglifyjs node_modules/socialcalc/SocialCalc.js $(ETHERCALC_FILES) $(UGLIFYJS_ARGS) --source-map ethercalc.js.map --source-map-include-sources >> $@
        mv ethercalc.js.map static
