### ISSUE TITLE
IPC socket support

### ISSUE THREAD

**Issue by atifaziz** [audreyt/ethercalc#419]
I've added support for IPC sockets in Zappa [that's now part of v5.2](https://github.com/zappajs/zappajs/issues/116#issuecomment-240225261). For background, see:

- zappajs/zappajs#116
- zappajs/zappajs#117 (PR)

Since EtherCalc uses Zappa, I'd like to address the same issue here so that EtherCalc can also allow use of IPC sockets. This would be a rather straightforward change. The `options` argument of [`zappa.run`](https://github.com/zappajs/zappajs/blob/6e2667dc25a8f320802f32b23ff51947bc6bd9c3/docs/reference.md#zapparun) now honors a `path` property for IPC scenarios and so this just needs to be passed along. At the moment, the [start-up code assumes that port is a number](https://github.com/audreyt/ethercalc/blob/55c84ff0469988a5fbf08b3e5dd25c91067d7b24/src/app.ls#L15):

```ls
port = Number(argv.port or json?PORT_NODEJS or process.env.PORT or process.env.VCAP_APP_PORT or process.env.OPENSHIFT_NODEJS_PORT) or 8000
```

I propose to change this so that if `port` is a string then it's assumed to be an IPC path instead. If that sounds okay then I'd be happy to submit a PR.

**Comment by audreyt** [comment]
That sounds great. Please go ahead with the PR!
