### ISSUE TITLE
Update zappajs to 5.x

### ISSUE THREAD

**Issue by atifaziz** [audreyt/ethercalc#420]
In order to address #419, [zappajs](https://www.npmjs.com/package/zappajs) needs to be updated to 5.2.0. Are we okay to move forward on this? [EtherCalc is locked far back on `0.5.x`](https://github.com/audreyt/ethercalc/blob/5c808fcff047ed68963a7f01f21409f8ce24e192/package.json#L14) at the moment so there may be concerns about breaking changes across a delta of 5 major versions?

**Comment by audreyt** [comment]
It's fine, please make a pull request — if it breaks we keep both pieces :)
