### ISSUE TITLE
survey forms: how?

### ISSUE THREAD

**Issue by dckc** [audreyt/ethercalc#424]
I can't figure out how to use the survey forms feature. Help?!

**Comment by ldidry** [comment]
Did you checked the [wiki](https://github.com/audreyt/ethercalc/wiki)?

**Comment by dckc** [comment]
I had not, but now I see [create a form](https://github.com/audreyt/ethercalc/wiki#create-a-form). Thanks!

I suggest you make the wiki a little easier to find... perhaps add links from README.md and from http://ethercalc.net/.

**Comment by eddyparkinson** [comment]
**Form** hello world

- Form:  http://sheet.cellmaster.com.au/exampleform/form
- master template: http://sheet.cellmaster.com.au/exampleform
- submitted data: http://sheet.cellmaster.com.au/exampleform_formdata
- Master form view: http://sheet.cellmaster.com.au/exampleform/app


**Form** Carbon Offset 
includes all widgets 

- Spreadsheet: sheet.cellmaster.com.au/carbonoffset
- Webapp: sheet.cellmaster.com.au/carbonoffset/app

**Comment by eddyparkinson** [comment]
@ldidry  did you do the Wiki - looks good, I did not know about it. I updated a little.  I think issue #383 has been fixed .

**Comment by ldidry** [comment]
@eddyparkinson Yes and no 😃 I didn't start it, but I added the form part and some other stuff.

**Comment by tyreun** [comment]
Hi,

The server http://sheet.cellmaster.com.au is unreachable.  :-(

I try to understand how works the forms on ethercalc.

Cheers

**Comment by eddyparkinson** [comment]
@tyreun try

https://ethercalc.org/mkcegljpv9eb
https://ethercalc.org/mkcegljpv9eb/form
https://ethercalc.org/mkcegljpv9eb/appeditor
https://ethercalc.org/mkcegljpv9eb_formdata

yes, the server stopped - I gave up with Redhat openshift, the new version is hard to debug, I gave up after 2 days.
