### ISSUE TITLE
Delete Row

### ISSUE THREAD

**Issue by miladiyosra** [audreyt/ethercalc#428]
Hi audreyt,

I want to sand a request to delete a rows in ethercalc using the API, It is possible to do it  ? 

Thanks

**Comment by eddyparkinson** [comment]
deleterow looks to accept a range - did you try passing a range?

**Comment by miladiyosra** [comment]
In Node js i'm trying to delete row using request  for exemple the first row by doing this but it doesn't work:

var request = require('request');
	request({
			 method: 'POST',
			 body: 'deleterow A1:B1',
										  
			 url: 'http://localhost:8000/_/data',
			headers: {
				'Content-Type': 'text/csv'}},
				function (error, re, body) {
				if(!error){
				console.log('done');}});

Do you have an idea about this assue ? 

Thanks

**Comment by eddyparkinson** [comment]
Suggest you look at: http://stackoverflow.com/questions/8675688/send-content-type-application-json-post-with-node-js

Pass a json and "command" is required.
