### ISSUE TITLE
CONCAT Formula

### ISSUE THREAD

**Issue by hamdijmii1992** [audreyt/ethercalc#431]
Hello.
Is there a CONCAT fromula in ethercalc like Excel's CONCAT ?

**Comment by eddyparkinson** [comment]
You can use & see this:
https://www.ablebits.com/office-addins-blog/2015/07/15/excel-concatenate-strings-cells-columns/

But the help does not list a concat type function.  (click the "fx" icon for a list of functions)

**Comment by biancah** [comment]
Why is this closed? CONCAT function still error in https://ethercalc.org/ ...

**Comment by eddyparkinson** [comment]
@audreyt can you push to npm and ethercalc.org

@biancah sorry. It is fixed in github. But looks like changes have not been pushed to npm or ethercalc.org

Working example:
http://sheet.cellmaster.com.au/example_concat

**Comment by audreyt** [comment]
Sure — it is now published.

**Comment by biancah** [comment]
@audreyt thank you !
