### ISSUE TITLE
Export database

### ISSUE THREAD

**Issue by doudidou** [audreyt/ethercalc#433]
Hello,
I want to know how to export the ethercalc database to another server for use it in another ethercalc? Because it is redis, i don't really know how it works. 
Sorry for disturbing, and for my bad english,
doudidou

**Comment by eddyparkinson** [comment]
You want a "backup" and "restore" of redis.  Google brings up lots of suggestions

https://www.google.com.au/?gfe_rd=cr&ei=pnLkV9-lJcrN8gfl86HgBA#q=redis%20backup%20restore
