### ISSUE TITLE
Restoring data on spreadsheet after deleting cell values

### ISSUE THREAD

**Issue by kambale** [audreyt/ethercalc#434]
Hi.

A user who had access to the spreadsheet deleted data on it 24 hours ago. The sheet is hosted in Sandstorm Oasis. We are trying to restore the data on the sheet from a specific time 48 hours ago. I have read documentation on Ethercalc and Sandstorm but I can't seem to find instruction on pulling a log or backup of the grain.

Would you mind pointing me in the right direction?

**Comment by kambale** [comment]
I have now the backup file in zip but I keep getting error whenever I try to restore it.

Upload failed: 413 HTTP/2.0 413

and when using the dump.json file to upload, I get

Upload failed: 413 HTTP/2.0 413

Any thoughts?

**Comment by eddyparkinson** [comment]
Am not sure if these files keep a history, so I don't know if this is possible. But if you have the data
then you should be able to restore it.

The snapshot has all the data for a sheet so if you can find "snapshot-sheetname",e.g. look at 
  "snapshot-coconstants_formdata" below. Then it will have all the data, and you could paste this 
 into the clipboard to restore things.

*Example blank snapshot*

```
  "snapshot-coconstants_formdata": "socialcalc:version:1.0\nMIME-Version: 1.0\nContent-Type: multipart/mixed; boundary=SocialCalcSpreadsheetControlSave\n--SocialCalcSpreadsheetControlSave\nContent-type: text/plain; charset=UTF-8\n\n# SocialCalc Spreadsheet Control Save\nversion:1.0\npart:sheet\npart:edit\npart:audit\n--SocialCalcSpreadsheetControlSave\nContent-type: text/plain; charset=UTF-8\n\nversion:1.5\nsheet:c:1:r:1:tvf:1\nvalueformat:1:text-wiki\n--SocialCalcSpreadsheetControlSave\nContent-type: text/plain; charset=UTF-8\n\nversion:1.0\nrowpane:0:1:1\ncolpane:0:1:1\necell:A1\n--SocialCalcSpreadsheetControlSave\nContent-type: text/plain; charset=UTF-8\n\n--SocialCalcSpreadsheetControlSave--\n",
  "chat-coconstants": [],


```
