### ISSUE TITLE
Post call failed with 404 error

### ISSUE THREAD

**Issue by hamdijmii1992** [audreyt/ethercalc#440]
When I trying to add a row in my sheet with rest api, I stuck in a 404 Not Found error.
There is my post call:
`$.ajax({
              url: 'https://ethercalc.org/blabla',
              method: 'POST',
              type: 'post',
              contentType: 'text/csv',
              data: 'a,b;e,c',
	      success: function (response, type, xhr) {
	      console.log(response);
	      return response; 

	     }
            });`

**Comment by rolandwillis** [comment]
@hamdijmii1992 The url is wrong in your example

It should be 
https://ethercalc.org/_/blabla

Please see http://docs.ethercalc.apiary.io/#reference/0/page/append-rows

**Comment by hamdijmii1992** [comment]
Oh, I ignored this dash, Thank you.
