### ISSUE TITLE
Loading Modal to show as Spreadsheet loads content - enhancement

### ISSUE THREAD

**Issue by rolandwillis** [audreyt/ethercalc#443]
It would be nice when a spreadsheet loads if a 'Please wait ... loading data.' modal could be displayed if there is data to load. I think this is particularly important as a UI feedback element since it can take several seconds to load a larger document which appears blank and is unresponsive until it loads.

**Comment by eddyparkinson** [comment]
Loading Modal (spinner) displays until sheet data arrives at client, so addresses network issues. But re-calc can be slow. Might also want a re-calc spinner.
