### ISSUE TITLE
Override a sheet row 

### ISSUE THREAD

**Issue by hamdijmii1992** [audreyt/ethercalc#444]
Is there a rest solution to override a row in Ethercalc ?

**Comment by rolandwillis** [comment]
As far as I am aware there is no direct post route that takes a roomid, row_number and new_row_values, however it is fairly trivial using the much more powerful POST Commands API 

http://docs.ethercalc.apiary.io/#reference/0/page/post-commands

This takes a JSON structure with a command field (either as a string or an array of strings), or a plain-text command string. (quoted from the docs)

The available commands can be seen on the Audit tab after completing some manual operations on a sheet via your browser. 

So to mimic your requirement to some extent (albeit a bit verbose!), the 'commands' below set values to some cells in row 7, then it clears the values of the cells in that row and then it assigns new values to the same cells in the row.

set A7 value n 10
set B7 value n 20
set C7 value n 30
set D7 value n 40
set E7 value n 50
set F7 value n 60
set A7:F7 empty
set A7 text t a
set B7 text t b
set C7 text t c
set D7 text t d
set E7 text t e
set F7 text t f

Hope that helps. Roland

**Comment by hamdijmii1992** [comment]
Thanks @rolandwillis  this will help me a lot.

**Comment by eddyparkinson** [comment]
maybe also, load into clipboard and paste
