### ISSUE TITLE
the merged cells disappear in the exported csv

### ISSUE THREAD

**Issue by dllhlx** [audreyt/ethercalc#445]
hi:
    As mentioned in the title, when I open the csv exported from the spreadsheet, I find the merged cells become a single cell. I don't known why, please help, thanks a lot.

the spreadsheet's merged cells like that
![001](https://cloud.githubusercontent.com/assets/7111160/19348074/9baae9a0-917e-11e6-8de4-d633451f3039.png)

the exported csv's merged cells disappeared and became single celll like that:
![002](https://cloud.githubusercontent.com/assets/7111160/19348086/ab84c9d6-917e-11e6-9a13-506e003f7594.png)

**Comment by eddyparkinson** [comment]
HTML and Excel should work, but CSV does not work like that. CSV stands for comma separated values, so there is no way to encode merged cells.

**Comment by dllhlx** [comment]
@eddyparkinson  thanks very much !

**Comment by dllhlx** [comment]
@eddyparkinson  In fact, I save the exported file as excel this time ,
![003](https://cloud.githubusercontent.com/assets/7111160/19379523/ee8b1dc4-9224-11e6-927c-bc9954c418cb.png)

 but after open the file,  I find the merged cells become single cell as before.

**Comment by amir-zeldes** [comment]
Hi, I'm running into the same issue: Excel export seems to unmerge all merged cells. Is there some way to make the export retain merged cells?

**Comment by eddyparkinson** [comment]
@amir-zeldes sorry, merged cells, style and formulae are not exported to excel. 

https://github.com/protobi/js-xlsx
has "ws['!merges']: array"

So looks to be possible. It would need adding to https://github.com/SheetJS/js-harb

**pull requests** 
There is a pull request problem with https://github.com/SheetJS/js-xlsx 
Details: https://github.com/SheetJS/js-xlsx/issues/513#event-908493236

**forking SheetJS** - We are working on setting up an Organization account and forking SheetJS 
https://github.com/node-xlsx/js-xlsx/issues/1#issuecomment-270044216

**Comment by amir-zeldes** [comment]
OK, I've read the above, I see this is a complicated situation. I'll stay on the lookout for updates and report any issues I find. Other stuff I've noticed:

  * Export of colons is serialized literally as `\c` in Excel output
  * Import of Excel (e.g. using a PUT call via curl) also results in loss of spans (and formatting)

Please let me know if I should open issues for these/where. Many thanks for your work on this amazing project!
