### ISSUE TITLE
Ethercalc stopped working

### ISSUE THREAD

**Issue by marinappdf** [audreyt/ethercalc#446]
All ethercalc graisn just stop working, all the others remain ok. I was editing a grains when it disconected and all I got was 
 Parameter 'url' must be a string, not undefined.
I tried to do backup, but I got only a json, not the data.

**Comment by eddyparkinson** [comment]
Suggest you report this to sandstorm, or the person who setup the server. They might still have a log of what happened and be able to offer more detail. 
Regards fixing the spreadsheet, I suspect you would need to reverse the command that caused the problem. 
@audreyt are you still around, you have not posted in a while. Any suggestions?

**Comment by marinappdf** [comment]
It seems that the sandstorm update broke ethercalc, we turned back to the previously version and turned off the automatic actualization.

Thank you!
