### ISSUE TITLE
COMMAND and COMMANDIF Functions

### ISSUE THREAD

**Issue by rolandwillis** [audreyt/ethercalc#447]
@eddyparkinson Hi, I have worked out how most of the form functions work now from your detailed example form at http://sheet.cellmaster.com.au/carbonoffset , however, I am still struggling with the COMMAND and COMMANDIF functions as I could not seem to find an example of their usage.

I tried something like =COMMAND(B5,'SET A1 value n 42') thinking that the command might be like a  command sent to the API but that returns an error. In fact nothing I try seems to work. Please could you supply an example of usage? Much appreciated :)

**Comment by eddyparkinson** [comment]
Looks correct.

Example for you http://sheet.cellmaster.com.au/command_example

I add a break point to ExecuteSheetCommand to check the syntax.

**Comment by rolandwillis** [comment]
@eddyparkinson Thanks for the prompt response. My error was the capitalization of the keyword 'set'. If capitalized, this produces an alert stating that the command is unknown.
