### ISSUE TITLE
Use websockets port 8000 from client for Openshift Origin

### ISSUE THREAD

**Issue by yudhiwidyatama** [audreyt/ethercalc#448]
For openshift origin M4 or enterprise 2.x, we are limited to port 8000 for websockets (See http://stackoverflow.com/questions/19948974/websocket-connection-to-openshift-app-failed).
Is it possible to have a switch to change websockets urls so they use port 8000 ? I was unable to find out where the websockets url get generated in the src code.

Currently running Ethercalc in openshift M4 yields many errors.
<img width="533" alt="screen shot 2016-10-26 at 5 34 19 am copy" src="https://cloud.githubusercontent.com/assets/610030/19706782/02f02882-9b3e-11e6-85dd-113793f3a445.png">

**Comment by eddyparkinson** [comment]
I know this branch works on open shift
 https://github.com/eddyparkinson/cellmaster/tree/website

spreadsheet functions should all be the same.

**Comment by yudhiwidyatama** [comment]
After experimenting a bit, the solution is to access the openshift application using 8000 port in the first place, so the generated websocket urls would also use port 8000. Using port 8000, the  Openshift Origin's apache reverse proxy no longer being used, and this solves WebSocket errors, and allows us to have more than 8 tabs in the sheet without hanging.
