### ISSUE TITLE
Export in view mode not working

### ISSUE THREAD

**Issue by sebsheep** [audreyt/ethercalc#451]
When we are in "view mode", e.g. 
https://ethercalc.org/odkcdsjjs11b/view
clicking on the export button (top left) will ask the wrong address to do the export.

In fact, it will ask
https://ethercalc.org/odkcdsjjs11b/odkcdsjjs11b.html
instead of 
https://ethercalc.org/odkcdsjjs11b.html

**Comment by eddyparkinson** [comment]
the code is here:

https://github.com/audreyt/ethercalc/blob/b6cfa0053d9c246fa39c351b9b6a8363439778ef/src/player.ls#L318-L331

SocialCalc._view = true if requestParams[\view]

Looks like a minor change.
