### ISSUE TITLE
Basepath not working

### ISSUE THREAD

**Issue by remipassmoilesel** [audreyt/ethercalc#452]
Hello, thanks for sharing Ethercalc freely,

I try to setup Ethercalc with an Apache proxy but "basepath" option does not work.
Here is my Apache configuration:

```
        ProxyPass /ethercalc http://localhost:8000
        ProxyPassReverse /ethercalc http://localhost:8000
```

Here is the command I use to launch Ethercalc:

`        /opt/ethercalc/bin/ethercalc --basepath=ethercalc --host=127.0.0.1 --port=8000 --polling `

But all resources are loaded without "basepath" value. For example:

```
<script src="./static/ethercalc.js"></script>
<script src="./socket.io/socket.io.js"></script>
<script src="./zappa/zappa.js"></script>
<script src="./player/broadcast.js"></script>
<script src="./player/graph.js"></script>
<script src="./player/main.js"></script>
```
I tried many combinations of arguments: no effect. 

Thanks for your help.

**Comment by eddyparkinson** [comment]
nginx/conf/nginx.conf  has

       ### Uncomment this if running with --basepath /path/prefix
        # location /zappa/socket/__local/ {
        #     rewrite (.*) /path/prefix$1;
        # }


try removing the # from the 3 lines

**Comment by remipassmoilesel** [comment]
I don't think it is a HTTP server problem, resources are reachable with the good URL path (with prefix) and I have many others proxy configurations running well. 

I think the problem is the "basepath" option, which do not have any effect. This option is supposed to change the base path of resources (I think ?) by adding an URL prefix.

But, when I specify "basepath" option on launch nothing happen. So without basepath, loading  ethercalc.js look like that:

```
$ /opt/ethercalc/bin/ethercalc --basepath=ethercalc

<script src="./static/ethercalc.js"></script>
```

And with basepath it should look like that (with 'urlprefix').
```
$ /opt/ethercalc/bin/ethercalc --basepath=ethercalc --basepath=urlprefix/

<script src="urlprefix/static/ethercalc.js"></script>
```

But no url prefix are added.

**Comment by eddyparkinson** [comment]
It does look to fail, but is hard to be 100% sure as I have a none standard setup at the moment.

Note:
`<script src="./static/ethercalc.js"></script>`
is not an absolute path , so I would not expect it to change.

**Comment by remipassmoilesel** [comment]
So how do basepath work ? I tried again and if it supposed to use <base> tag, it do not. With the following command:

$ bin/ethercalc --basepath=something
$ bin/ethercalc --basepath=/something

<base target="_blank"/>

**Comment by eddyparkinson** [comment]
When I use
bin/ethercalc --basepath=/calcdir 

http://localhost:8000/_new
redirects to 
http://desktop-894i7al:8000/calcdir/vsnls2z4has7
which gives 404 not found

but I did not change nginx/conf/nginx.conf
I have not looked at what nginx does.

**Comment by remipassmoilesel** [comment]
I think it is clearly a bug

**Comment by eddyparkinson** [comment]
@audreyt did say some people are using subfolders (basepath ?) with ethercalc.
I will mark as a bug, but am surprised someone did not report this if we broke the code.
Maybe people stopped using basepath.

**Comment by eddyparkinson** [comment]
@remipassmoilesel 

**possible work around**  
 in src/main.ls
 replace  every   @get '/
 with                  @get "#BASEPATH

e.g.
  @get '/static/socialcalc.js': ->
  @get "#BASEPATH/static/socialcalc.js": ->

note the use of "
 
But there must have been a setting that was auto adding the basepath that is no longer working.
 I suspect this  https://github.com/expressjs/express/issues/478 
 so maybe an old version of zappajs would fix the problem, as it uses express.

**Comment by remipassmoilesel** [comment]
@eddyparkinson, 

Thanks for the workaround, I will try do deal with this.

In my opinion, base path are essential, just because servers are used for different purposes. For example, a few weeks ago I built an instant messaging system that also used Etherpad and to offer my users a single point of access to the collaboration system the use of proxy and base paths was indispensable (/etherpad/... , /xmpp/... , or maybe /ethercalc/... )

Thanks for your help and for your replies.

**Comment by eddyparkinson** [comment]
@rugk do you have basepath working? remipassmoilesel wants to use basepath
I notice you have several post on the issue, e.g. #360

**Comment by rugk** [comment]
Yes, I think it works here, with some workarounds such as the one [mentioned here](https://github.com/audreyt/ethercalc/issues/360#issuecomment-223701991).

**Comment by hermannschwaerzlerUIBK** [comment]
This is an old issue still I would like to tell you my workaround (similar to @eddyparkinson in https://github.com/audreyt/ethercalc/issues/452#issuecomment-261422150).

I replace any occurrence of `@get 'somepath'` with `@get "#BASEPATHsomepath"`:

`sed --in-place -r -e "s/@get '([^']+)'/@get \"#BASEPATH\1\"/" src/main.ls`

After that `--basepath` actually works for me. I am running ethercalc in a reverse-proxy setup. On the frontend (aka reverse-proxy) I use these settings (Apache):
```
ProxyPass        /ethercalc                 http://backend:8000
ProxyPassReverse /ethercalc                 http://backend:8000
```
On the backend I start ethercalc like this:
`node app.js --basepath ethercalc --polling`

Do you want me to send a patch or create a pull request?

**Comment by audreyt** [comment]
A pull request would be much appreciated.
