### ISSUE TITLE
Link broken on Wiki -> the source code

### ISSUE THREAD

**Issue by rubenrivera** [audreyt/ethercalc#457]
The link [the source code](https://github.com/audreyt/ethercalc/blob/master/formula1.js) taken from [Wiki ](https://github.com/audreyt/ethercalc/wiki) is broken. Looks that formula1.js was removed from master.

**Comment by eddyparkinson** [comment]
thanks @rubenrivera for reporting, fixed.

The correct file:
https://github.com/marcelklehr/socialcalc/blob/master/formula1.js
