### ISSUE TITLE
Unguessable url for read only

### ISSUE THREAD

**Issue by sebsheep** [audreyt/ethercalc#468]
Hello,

Does ethercalc provides a way to have unguessable urls for read only, from which it is not possible to have the edit link?

If not, is it possible to add this functionnality ?

E.g. from https://ethercalc.org/odkcdsjjs11b/view it is straightforward to have the edit url, we just have to truncate the "/view" part.

**Comment by eddyparkinson** [comment]
**Read only with sandstorm and ethercalc**

https://sandstorm.io can do this

Setup
https://github.com/sandstorm-io/sandstorm

and add ethercalc.

**e.g.**
to try it:
https://oasis.sandstorm.io/demo
click "Try quick demo"
goto "app market"
select "ethercalc"
edit the sheet
share as read only.

**Comment by eddyparkinson** [comment]
I would like to add this feature to ethercalc - but is a time/money issue.
