### ISSUE TITLE
Force a value into a cell from JS

### ISSUE THREAD

**Issue by CarbonMan** [audreyt/ethercalc#470]
I am just testing an idea and would like to see how I can force a value into a cell using JS from the console.  What is the correct method to force a value into a cell?

I was able to execute;
    SocialCalc.Callbacks.broadcast("execute", {cmdstr: 'set K33 value n 33', saveundo: true, room: EtherCalc._room})
Though the value only appeared in the cell once the page was refreshed.

I really need to find a way to have the cell UI updated, all formulas executed and the backend updated from a JS call.

Evidently the value for a cell is held like this;
    SocialCalc.CurrentSpreadsheetControlObject.sheet.cells.K33.datavalue

Updating the value there does not update the display and changes are not stored on the server. It looks like the updating is controlled through SocialCalc.CurrentSpreadsheetControlObject.sheet.RecalcSheet()
 but when I call it nothing happens. 
Is there any documentation for the client side of how ethercalc manages cell state?

**Comment by rubenrivera** [comment]
This issue was cross-poste to SE Web Applications -> http://webapps.stackexchange.com/q/101174/88163

**Comment by CarbonMan** [comment]
Thanks @Rubén, I will deleted the SO question as I know that cross-posting is a bit pushy but I wasn't getting any feedback over there so I thought it wasn't monitored.
The API is interesting but I need to POST the contents of the cell not a GET. (Not yelling just RESTing) I am using the console in preparation for writing some Javascript code that will be embedded into the page. The JS code will primarily be responsible for inserting/updating values in the spreadsheet

**Comment by eddyparkinson** [comment]
**EditorScheduleSheetCommands**

I would use spreadsheet.editor.EditorScheduleSheetCommands
if adding to the eithercalc client.
See  https://github.com/marcelklehr/socialcalc/blob/master/formula1.js#L5581

To try it.  Look at the command example  http://sheet.cellmaster.com.au/examples

**API**

curl -H "Content-Type: application/json" -X POST  http://server/_/srqf6vyw1ngx -d '{"command":"set A1 text t xy"}'

but for javascript use xjax post - http://stackoverflow.com/questions/10936407/ajax-type-post-post-method-to-php

**Comment by CarbonMan** [comment]
Thank you.
SocialCalc.CurrentSpreadsheetControlObject.editor.EditorScheduleSheetCommands("set A1 value n 5")
did the trick.

Much appreciated
