### ISSUE TITLE
missing images/sc_commentbg.gif

### ISSUE THREAD

**Issue by landryb** [audreyt/ethercalc#478]
When you go to the comment tab and set a comment, saving it will trigger a 404 in the console, images/sc_commentbg.gif is missing from the git repo ?

**Comment by eddyparkinson** [comment]
This file:
https://github.com/audreyt/ethercalc/blob/708859d166ad13ce7afb054be1848cef21701e58/images/sc-commentbg.gif

**Comment by landryb** [comment]
From what i understand of the aforementionned commit, file sc-commentbg.gif was removed from git, but in the json files referencing it, it should have been renamed/moved to sc_commentbg.gif ?

**Comment by eddyparkinson** [comment]
@landryb yes, that is right. Pull requests are welcome.
