### ISSUE TITLE
Persistence issue

### ISSUE THREAD

**Issue by hamdijmii1992** [audreyt/ethercalc#481]
I faced a strange issue with my ethercalc sheets, from time to time I remarked that my sheets were evicted automatically.In my redis configuration,  I use an:

- RDB persistence mode

- TTL set to -1 by default 

- "maxmemory" sets to 0 (no limitation).

Any idea please ?

**Comment by eddyparkinson** [comment]
Do you mean all your sheets were removed? This might not be the same, but I have seen this with the dump.json file. Adding a restart every 24 hours removed the problem. It only every happened after ethercalc had been running for a few days.

**Comment by hamdijmii1992** [comment]
@eddyparkinson with RDB persistence mode all my sheets was evicted automatically every few days.
Thanks, I will add a cron job to restart ethercalc every 24 hours as you said, but Why this kind of issue happens ?

**Comment by hamdijmii1992** [comment]
@audreyt Can I disable removing old sheets directly in ethercalc, please ?

**Comment by audreyt** [comment]
We only expire old sheets if the `--expire` flag is set.

**Comment by hamdijmii1992** [comment]
Thanks @audreyt 
But, My init script didn't include --expire flag:

`start-stop-daemon --start --chuid "$USER:$GROUP" --background --make-pidfile --pidfile /var/run/$NAME.pid --exec $EPLITE_DIR/$EPLITE_BIN -- $LOGFILE --cors || true`

**Comment by hamdijmii1992** [comment]
Thanks for ALL, it seems that I got hacked by a bot, so I made my redis more secure.
