### ISSUE TITLE
Key authentication restriction

### ISSUE THREAD

**Issue by hamdijmii1992** [audreyt/ethercalc#482]
According to issue #1 , I understand that I can use the --key flag to perform authentication .
My need is to allow only users that  have a valid auth parameter to both edit and view my sheets
For example when a user open a sheet like: 

- ipaddress:port/id_sheet -> will be not enable to view/edit sheet
- ipaddress:port/id_sheet?auth=invalid_key -> will be not enable to view/edit sheet
- ipaddress:port/id_sheet?auth=valid_key -> will be enable to view/edit sheet

How can I perform this restriction with --key option in ethercalc ? 
Should I make some changes in the source code ?

best regards :-)

**Comment by eddyparkinson** [comment]
node app.js --key mypassword

Looks to fail. 
When I use the above command, I can still edit the sheet.
So I assume the Key authentication code is broken. Looks like it was working some time ago: https://github.com/audreyt/ethercalc/issues/91

main.ls file has most of the code for this. Pull requests welcome
