### ISSUE TITLE
Non-overwrite behavior when merging cells creates hidden values

### ISSUE THREAD

**Issue by amir-zeldes** [audreyt/ethercalc#483]
When merging multiple cells containing content, only the value of the top-left cell is retained visually: the merged cell displays the single value (which makes sense). 

However there is a problem with the underlying values of other cells in the merge - they are not actually erased, just hidden by the merged cell. As a result, values which users may think have been deleted are actually hidden beneath merged cells, and can resurface if the cell is unmerged, or also in the socialcalc format in the API or on export to CSV. This is a potential data security hazard, if users share or export a spreadsheet with sensitive invisible values which then surprisingly turn out to still be there.

The expected behavior from my point of view would match Excel's behavior: a merge destroys all values except for the value retained in the merged cell. All other underlying cells are cleared.

**Comment by amir-zeldes** [comment]
Just checking - is this something that's likely to get implemented? Would it require changes to SocialCalc? If you point me in the right direction, I may be able to implement this and submit a pull request, I'm just worried about breaking something accidentally. 

Would iterating over all cells except the top left one and clearing them work? Thanks!

**Comment by eddyparkinson** [comment]
>Would iterating over all cells except the top left one and clearing them work? 

Sounds correct to me,  also add an undo.

This is the code:
https://github.com/marcelklehr/socialcalc/blob/master/socialcalc-3.js#L2074-L2090

**Comment by amir-zeldes** [comment]
OK, I've had a look, I think I'd try something like this:

```
      case "merge":
         sheet.renderneeded = true;
         what = cmd.NextToken();
         rest = cmd.RestOfString();
         ParseRange();
         cell=sheet.GetAssuredCell(cr1.coord);
         if (cell.readonly) break;

         // check whether merged cells other than cr1 contain data and clear them
         for (row=cr1.row; row <= cr2.row; row++) {
            for (col=cr1.col; col <= cr2.col; col++) {
               if (row != cr1.row && col != cr1.col){ // skip top left cell
                   quashedCellCoord = SocialCalc.crToCoord(col, row);
                   quashedCell = sheet.GetAssuredCell(quashedCellCoord);
                   // save quashed cell value for undo
                   if (saveundo) changes.AddUndo("set "+quashedCellCoord+" all", sheet.CellToString(quashedCell));
                   delete sheet.cells[quashedCellCoord]; // delete cell
               }
            }
         }


         if (saveundo) changes.AddUndo("unmerge "+cr1.coord);

         if (cr2.col > cr1.col) cell.colspan = cr2.col - cr1.col + 1;
         else delete cell.colspan;
         if (cr2.row > cr1.row) cell.rowspan = cr2.row - cr1.row + 1;
         else delete cell.rowspan;

         sheet.changedrendervalues = true;

         break;
```

The only problem is I can't seem to test this, I'm having trouble recompiling the minified ethercalc.js. I edited socialcalc-3.js, and also tried directly inserting it into node_modules/socialcalc/SocialCalc.js. The minified file seems to suggest:

`make depends`

But when I do this in /usr/lib/node_modules/ethercalc/ I just get:

`make: Nothing to be done for `depends'.`

I'm probably missing something obvious, but I've never developed for node before, so this is new to me. Any pointers would be appreciated!
But when I do that

**Comment by eddyparkinson** [comment]
**Make problem** with node_modules/socialcalc/SocialCalc.js
@marcelklehr @audreyt do you know why make is not picking up that  has changed?

I sometimes use "touch" to force the compile. I expect the make file wants fixing.

**Comment by marcelklehr** [comment]
@eddyparkinson are you talking about the problem by @amir-zeldes above?
There's a Makefile for ethercalc and there's one for socialcalc. They are not connected in any way. Running one doesn't trigger the other. You will need to run `make` in node_modules/socialcalc/ first, then run `make depends` in ethercalc. This could of course be integrated into ethercalc's makefile ;)

**Comment by eddyparkinson** [comment]
@amir-zeldes suggest "touch src/main.ls" and "make" or "make all".
this should force a compile.

**Comment by amir-zeldes** [comment]
OK, thanks everyone - I wasn't able to recompile the minified code (I think something is wrong with my zappajs complaining it can't find uglify), but I was able to test it by manually minifying it. It seems to be working according to the behavior above, incl. undo. 

The pull request is here, I'm happy to revise if you have any comments:

marcelklehr/socialcalc#26
