### ISSUE TITLE
CORS issue when using rest API  with authorization header

### ISSUE THREAD

**Issue by hamdijmii1992** [audreyt/ethercalc#485]
Hello.
I faced a problem with Ethercalc rest API  when trying to get an ethercalc sheet.
To secure my ethercalc server I add a basic authentication as @audreyt  says in issue #20, after that I created an ajax call to get a sheet as follows:

`function(data) {
             $.ajax({
              url: 'http://192.168.1.16:8000/yx6g9kodc4pp.csv.json',
			  beforeSend: function (xhr) {
    xhr.setRequestHeader ("Authorization", "Basic " + btoa("username" + ":" + "password"))},
              method: 'GET',`

But I got a CORS error like:

`Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. The response had HTTP status code 401.`

**It's weird sense I enable cors in my server by adding --cors flag !!** ??

Best regards!

**Comment by audreyt** [comment]
Origin `null` indicates a local file. Would you like to host the client HTML & JS using something like `static-here` ?

Also, instead of using `Authorization: Basic`, jQuery offers `username` and `password` options: http://stackoverflow.com/a/11960692

**Comment by hamdijmii1992** [comment]
Thanks @audreyt  for your quick response.
In fact, 4.0 express version says that 

> This means no basic http authentication unless you do it yourself

So instead of using this code snippet, we have to use this one under:

` var basicAuth = require('basic-auth');
   var auth = function (req, res, next) {
  function unauthorized(res) {
    res.set('WWW-Authenticate', 'Basic realm=Authorization Required');
    return res.send(401);
  };

  var user = basicAuth(req);

  if (!user || !user.name || !user.pass) {
    return unauthorized(res);
  };

  if (user.name === 'username' && user.pass === 'password*') {
    return next();
  } else {
    return unauthorized(res);
  };
};`
