### ISSUE TITLE
How to increase ethercalc performance ?

### ISSUE THREAD

**Issue by hamdijmii1992** [audreyt/ethercalc#486]
I used ethercalc server as a rest API, but some times (not always) I wait for a long to get an ajax response (between 2 to 5 min). For me it's very  annoying and I guess that my ethercalc (maybe redis) deployment miss some things because I didn't have this issue with etherclac demo.

I deployed my ethercal server under a VM with those characteristics:

1. model name      : Intel Core Processor (Haswell, no TSX)

1. cpu MHz         : 3092.862

1. cache size      : 4096 KB

1. processor       : 1

1. cpu cores       : 1

I attached below my redis conf.
[redis.txt](https://github.com/audreyt/ethercalc/files/739850/redis.txt)

I need a help to  speedup my rest responses !
Best regards ?

**Comment by eddyparkinson** [comment]
**Performance issue**
Nodejs tracers are designed to solve performance issues.  Would be good to add one. 

**Shutting down**
 Ethercalc looks to crash after a few days and needs a restart. I suspect your server spots the crash
when you make the API call. It auto restarts the service and then processes the API call.
 Suggest you autorestart ethercalc every day.

**Redis AWS bgsave issue**
#432

**Comment by hamdijmii1992** [comment]
@eddyparkinson thanks, For more information about my issue, when I debugged ethercalc, I found that the code snippet that was very slow is 
```
if (content instanceof Function) {
				  console.log("entering ....... \n");
                return content(SC[room], function(rv){
                  this$.response.type(type);
				  console.log("exiting ....... ", room);
                  return this$.response.send(200, rv);
                });
              } 
```

So i think the SC[room] call speed down my request ?

**Comment by eddyparkinson** [comment]
How often is it slow? 

Do you mean the call to content() as SC[room] is an array.
Assume it passes content back to the client. 

Looks like this code
https://github.com/audreyt/ethercalc/blob/master/main.js#L195-L199
Auto created from https://github.com/audreyt/ethercalc/blob/master/src/main.ls#L131-L134

**Comment by hamdijmii1992** [comment]
You are right, I mean this code snippet.
In my strange case, often, after two successive time-accepted requests, the third one hanged up( between 2 and 3min) in this code snippet above.
I also debugged sc.js to know if redis in behind this latency but I found that redis db send data immediately, I think that this latency goes from the communication between sc.js and main.js, but I didn't find where can I speedup it.

**Comment by eddyparkinson** [comment]
Looks like we lack information to workout what the problem is. Suggest adding more logs or using
Nodejs tracers to work out what is happening.

Try your request against sheet.cellmaster.com.au
Also what is the rest API request?

**Comment by hamdijmii1992** [comment]
@eddyparkinson I used tracer to output some logs, This is my log file.
[log.txt](https://github.com/audreyt/ethercalc/files/750148/log.txt)
As you can see,

- In the first log snippet the time response is acceptable (1s)

- In the second log snippet time response is very long (about 2 min)

- In the third  log snippet time response is not very acceptable ( 25 seconds).

- In the fourth log snippet time response is acceptable (1 s)

- In the fifth log snippet time response is very long (about 2 min).

I tried requesting  sheet.cellmaster.com.au and I got my responses immediately (the issue of long wait disappeared)

I use ajax requests as rest API request .

Thanks.

**Comment by eddyparkinson** [comment]
Maybe redis is causing it. sheet.cellmaster.com.au runs on openshift without redis. It uses dump.json.
Are you able to log redis response times?

Re:Rest API
what is the command you send to the API, a "set"?

**Comment by hamdijmii1992** [comment]
I logged redis response and I found that my db act immediately to requests.
**Solution** 
I installed Nodejs from source and in this time my strange latency disappeared !!
