### ISSUE TITLE
ethercalc won't stop calculation

### ISSUE THREAD

**Issue by 1337gut** [audreyt/ethercalc#487]
Hi,
I've got ethercalc running via docker. So far it worked fine. (Not great but fine.)
But two days ago I edited an (already "messy") multisheet and since then I can't edit anything.

Last steps I did before this appeared:
- I added another sheet (#4)
- I entered this formula: =IF(ISERROR(VLOOKUP(B96+1,WOCHENPLAN.4!A$2:E$999,1,FALSE))=TRUE,B96+1,IF(COUNTA(VLOOKUP(B96+1,WOCHENPLAN.4!A$2:E$999,3,FALSE),VLOOKUP(B96+1,WOCHENPLAN.4!A$2:E$999,4,FALSE),VLOOKUP(B96+1,WOCHENPLAN.4!A$2:E$999,5,FALSE))<3,"<span style=""background-color:yellow"">"&B96&+1"</span>","<span style=""background-color:red"">&B96&+1</span>"))
What I wanted to do: I want to check if the date in this cell which is calculated from the date in the cell above (B96+1) is in a list in WOCHENPLAN.4. If it is, I want it to check if there are some fields marked and if, the background of the cell should change.

After this I'm facing these issues:
- 4th sheet doesn't appear in the tabs, but is reachable by its direct URL.
- Some changed data is stored in a tab but not calculated correctly in another tab (worked before).
- I can't do any changes nor scroll in the tab where I entered the formula.
- I can do changes in the other tabs and these changes will be saved.

I did a restart to both docker containers but this didn't help.
Now I don't know how to get rid of this problem. Is there any way i.e. to delete cells by entering the redis container?

**Comment by eddyparkinson** [comment]
Suggest you use curl

curl -H "Content-Type: application/json" -X POST  http://**host**/_/**sheet** -d '{"command":"set A1 text t xy"}'

change **host** and **sheet**

some examples of how to use command
http://sheet.cellmaster.com.au/command_example

Is there anyway you can re-create this? If so can you post details so I can fix it.
I do have a version with a fix in, but needs more testing.

**Comment by 1337gut** [comment]
Holy Moly, that helped! Didn't know Curl could do that. Thanks a lot!
I'll do some testing once I got the time.
