### ISSUE TITLE
can't find end of central directory error

### ISSUE THREAD

**Issue by hamdijmii1992** [audreyt/ethercalc#495]
The last days my ethercalc rest api works well, today, as usual, I tried to push some data to etherclac wilt rest api but I got this error:

> /root/ethercalc/node_modules/jszip/lib/zipEntries.js:135
>             throw new Error("Corrupted zip : can't find end of central directory");
>             ^
> 
> Error: Corrupted zip : can't find end of central directory
>     at ZipEntries.readEndOfCentral (/root/ethercalc/node_modules/jszip/lib/zipEntries.js:135:19)
>     at ZipEntries.load (/root/ethercalc/node_modules/jszip/lib/zipEntries.js:197:14)
>     at ZipEntries (/root/ethercalc/node_modules/jszip/lib/zipEntries.js:21:14)
>     at JSZip.module.exports [as load] (/root/ethercalc/node_modules/jszip/lib/load.js:11:18)
>     at JSZip (/root/ethercalc/node_modules/jszip/lib/index.js:39:14)
>     at Object.readSync [as read] (/root/ethercalc/node_modules/xlsx/xlsx.js:5150:24)
>     at Object.read (/root/ethercalc/node_modules/j/j.js:37:33)
>     at IncomingMessage.<anonymous> (/root/ethercalc/main.js:537:50)
>     at emitNone (events.js:86:13)
>     at IncomingMessage.emit (events.js:186:7)
>     at endReadableNT (_stream_readable.js:974:12)
>     at _combinedTickCallback (internal/process/next_tick.js:74:11)
>     at process._tickCallback (internal/process/next_tick.js:98:9)

Any idea about this error ?

**Comment by eddyparkinson** [comment]
Are you importing or exporting? Look like a problem with the file or  jszip.

Also, what version of node. Lots of code no longer supports old version of node.

**Comment by hamdijmii1992** [comment]
Thanks @eddyparkinson , In fact the source bug is that some letters should be guarded like '"'+name+'"' to be sent safely to ethercalc , because some head letters in variables could throw a strange behavior in ethercalc like
"P" in a head of variable name.
So for example

> var data_to_be_pushed = name+',' abr;   ====> could throw a strange behavior
> var data_to_be_pushed =  '"'+name+'"'+',' abr; ====> it's safe and not behave strange

**Comment by pierreozoux** [comment]
I just hit the bug! Was wondering why my name "Pierre" would throw errors... But ok, thanks for the clarification!
