### ISSUE TITLE
page load loop on node version v6.0

### ISSUE THREAD

**Issue by JamesCordell** [audreyt/ethercalc#500]
Hi

I am using the following.

node version v6.0 which bypasses the node mailer issues. I am unable to use node version 4 as
i get.

ethercalc/node_modules/nodemailer/lib/mailer/index.js:75
            this.transporter.on('idle', (...args) => {

what version are you using?

**Comment by JamesCordell** [comment]
I have discovered that using ubuntu 16.04 fixes this page load loop.

**Comment by eddyparkinson** [comment]
Node 0.1 is running here http://sheet.cellmaster.com.au/examples

I don't know what  http://framaclac.org or ethercalc.org or sandstorm are using.

But would be good to update things to latest versions of node. As older versions
 will get dropped eventually.

Pull requests welcome.

**Comment by JamesCordell** [comment]
updating the version fixed this thanks.
