### ISSUE TITLE
copy-paste from 1 source cells to several target cells

### ISSUE THREAD

**Issue by PhilLAL** [audreyt/ethercalc#502]
Hi,
I observed that I can copy 1 cell to several cells (vertically or horizontally) selected with mouse, but if these target cells are selected with keyboard, only the first cell will be copied. 

It seems to me it is not the behavior the user is waiting for.

**Comment by eddyparkinson** [comment]
Strange, I can do it. Have you more detals.

**Copy and paste with keyboard**
cell A7 "a"
ctrl+c
move to A18
hold shift and move to A22
ctrl+v

it pastes "a" into every cell in the range A18:A22

**Comment by PhilLAL** [comment]
Sorry, it seems to work as I try today.
I'm going back to my user to check the use case.
