### ISSUE TITLE
ethercalc barcode images

### ISSUE THREAD

**Issue by CarbonMan** [audreyt/ethercalc#507]
I don't want to cross post but I am not sure whether http://webapps.stackexchange.com is monitored for Ethercalc questions.

[Embedding barcodes](http://webapps.stackexchange.com/questions/104812/how-can-you-get-an-image-from-a-url-via-a-function-in-ethercalc)

Would it be better to post here or on webapps for questions regarding usage?

**Comment by eddyparkinson** [comment]
**Ethercalc questions**
Best to post a link to your stackexchange question here. I don't think stackexchange is monitored for
ethercalc questions very often.
