### ISSUE TITLE
Sheet Loading Loop Node V7.8.0

### ISSUE THREAD

**Issue by mcarpenterjr** [audreyt/ethercalc#509]
Seeing issue #500 I'm having a similar experience.
The installation is not using Redis, I did notice two undefined errors in the console.

Uncaught TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (broadcast.js:63)
    at Object.zappa.run (zappa.js:123)
    at broadcast.js:1

bundle.js:5243 Uncaught TypeError: Cannot read property 'dataset' of null
    at HTMLDocument.r (bundle.js:5243)

not 100% on where to start diagnosing.

**Comment by eddyparkinson** [comment]
Is this running on a server or local? At what point do you get the errors, when you start the server or when you open a sheet in the browser?

My guess is Socket.IO is being blocked. as it broadcasts messages to all connected spreadsheet clients.
Maybe related: https://github.com/audreyt/ethercalc/issues/448

**Comment by bmiller59** [comment]
+ 1 I am having this same issue.

**Comment by eddyparkinson** [comment]
Have you got any more details?

> Is this running on a server or local? At what point do you get the errors, when you start the server or when you open a sheet in the browser?

**Comment by bmiller59** [comment]
This happens on attempt to create a new spreadsheet. The server starts without without errors and I can access the home page, but both create a new document and uploading a document result in this error. The page loads and reloads forever generating the error above.

I am guessing it has to do with upgraded node modules having different behavior from expected.

**Comment by eddyparkinson** [comment]
Running on a server,or local?

**Comment by bmiller59** [comment]
Running a server. I am accessing it behind apache using this config below (with domain name changed). There are no apache, nor nodejs errors generated in the log files. You will see I am using a different port, but I have confirmed it is indeed reachable there on the server using curl.

<VirtualHost *:80>
    ServerName calc.example.org

    Redirect permanent / https://calc.example.org/
</VirtualHost>

<VirtualHost *:443>
    ServerName calc.example.org
    SSLEngine On
    SSLProxyEngine On

    ErrorLog                /var/log/apache2/ethercalc.info-error_log
    CustomLog               /var/log/apache2/ethercalc.info-access_log common


	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/html


	# Proxy pass to the node.js server
        ProxyVia On
        ProxyPreserveHost On
        ProxyRequests off
	ProxyPass / http://127.0.0.1:8778/
	ProxyPassReverse / http://127.0.0.1:8778/
	
	# Set up websockets to work through the proxy
        <IfModule mod_rewrite.c>
	   RewriteEngine On
	   RewriteCond %{REQUEST_URI}  ^/socket.io            [NC]
	   RewriteCond %{QUERY_STRING} transport=websocket    [NC]
	   RewriteRule /(.*)           ws://127.0.0.1:8778/$1 [P,L]
        </IfModule>
        <Proxy *>
          Require all granted
        </Proxy>


	# Simple Auth for both viewing and editing sheets
	<LocationMatch "^/">
		AuthType Basic
		AuthName "Ethercalc Viewer"
		AuthUserFile "/etc/apache2/.htpasswd"
		Require valid-user

	</LocationMatch>
	
        <LocationMatch ^/(.*)/edit$>
 		AuthType Basic
		AuthName "Ethercalc Viewer"
		AuthUserFile "/etc/apache2/.htpasswd"
		Require user user editor
	</LocationMatch>

	# Set up an alias for static files. Saves having to serve them from node.js
	Alias /static /home/pm2/ethercalc/install/static
	Alias /l10n /home/pm2/ethercalc/install/l10n
        Alias /images /home/pm2/ethercalc/install/images


</VirtualHost>

**Comment by bmiller59** [comment]
FYI, In a different browser (firefox) the same error/problem shows like this:


TypeError: SocialCalc.Sheet is undefined[Learn More]  broadcast.js:63:9
	<anonymous> https://calc.brendanmiller.org/player/broadcast.js:63:9
	zappa.run https://calc.brendanmiller.org/zappa/zappa.js:123:7
	<anonymous> https://calc.brendanmiller.org/player/broadcast.js:1:2
TypeError: SocialCalc.Sheet is undefined[Learn More]  broadcast.js:63:9
TypeError: SocialCalc.Sheet is undefined[Learn More]  broadcast.js:63:9

**Comment by eddyparkinson** [comment]
**web sockets blocked?**

Are web sockets blocked? Try to run it on a local machine. Also there is a log on the server, this will show if a request for a sheet has been received.  

**Curl**
 curl does not use web sockets AFAIK

**Comment by mcarpenterjr** [comment]
Hey, I'm pretty sure I resolved this issue by creating a new instance of ethercalc on my server. I would say for me It's solved. So I'm going to close this since I'm not a fan of leaving issues open and hanging in the balance.

**Comment by AlejandroDagobah** [comment]
Hey i have the same issue but i dont know how to create a new instance of ethercalc i don't use a server yet i'm on local do you mean like to clone it again?
