### ISSUE TITLE
Localisation works, but currency still $/date/number format still US

### ISSUE THREAD

**Issue by nschlia** [audreyt/ethercalc#513]
Installed ethercalc on Debian 8.7 (using npm install -g ethercalc). All works fine, the page comes up in German, but number/date/currency are still US. I removed the de.json file, the page came up in English. So the German file gets used. But anyways, all cells show up in US localisation.

**Comment by eddyparkinson** [comment]
Agree:
 Currency = $
 number = 1,234.56
 Date= 2017/10/11 or 10/11/2017 = 11-Oct-2017

**Comment by eddyparkinson** [comment]
**Localisation settings**

From  file fr.json
old ##0.0%|1,234.56%:#,##0.00%|[newcol]:|$1,234:$#,##0|$1,234.5:$#,##0.0|$1,234.56
new ##0.0%|1 234,56%:#,##0.00%|[newcol]:|1 234 €:#,##0 €|1 234,5 €:#,##0.0 €|1 234,56

See
https://github.com/audreyt/ethercalc/commit/55c84ff0469988a5fbf08b3e5dd25c91067d7b24

If these changes are made to the de.json file, it looks like it would fix some of the issues.

**Comment by nschlia** [comment]
Thanks! This actually fixes the problem.

Here's the German version for de.json:

 "SCFormatNumberFormats": "[cancel]:|[break]:|%loc!Default!:|[custom]:|%loc!Automatic!:general|%loc!Auto w/ commas!:[,]General|[break]:|00:00|000:000|0000:0000|00000:00000|[break]:|%loc!Formula!:formula|%loc!Hidden!:hidden|[newcol]:1234:0|1 234:#,##0|1 234.5:#,##0.0|1 234,56:#,##0.00|1 234,567:#,##0.000|1 23,.5678:#,##0.0000|[break]:|1 234%:#,##0%|1 234,5%:#,##0.0%|1 234,56%:#,##0.00%|[newcol]:|1 234 €:#,##0 €|1 234,5 €:#,##0.0 €|1 234,56 €:#,##0.00 €|[break]:|(1 234):#,##0_);(#,##0)|(1 234,5):#,##0.0_);(#,##0.0)|(1 234,56):#,##0.00_);(#,##0.00)|[break]:|(1 234€):#,##0_)€;(#,##0€)|(1 234,5€):#,##0.0_)€;(#,##0.0€)|(1 234,56€):#,##0.00_)€;(#,##0.00€)|[newcol]:|1.4.06:m.d.yy|01.04.2006:mm.dd.yyyy|2006-01-04:yyyy-mm-dd|4. Jan. 06:d. mmm. yy|04. Jan. 2006:dd. mmm. yyyy|4. Januar 2006:d. mmmm yyyy|[break]:|1\\c23:h:mm|1\\c23 PM:h:mm AM/PM|1\\c23\\c45:h:mm:ss|01\\c23\\c45:hh:mm:ss|26\\c23 (h\\cm):[hh]:mm|69\\c45 (m\\cs):[mm]:ss|69 (s):[ss]|[newcol]:|2006-01-04 01\\c23\\c45:yyyy-mm-dd hh:mm:ss|Januar 4, 2006:mmmm d, yyyy hh:mm:ss|Mo:ddd|Montag:dddd|",

Two things though:

- The date is displayed as e.g. "29,04,2017", the dots are replaced with kommas. Probably because the values are treated as numbers.
- The date format in the French version needs to be changed, too. I think the format is dd.mm.yyyy etc. (as in German)

Here's the French version which I think is correct:

  "SCFormatNumberFormats": "[cancel]:|[break]:|%loc!Default!:|[custom]:|%loc!Automatic!:general|%loc!Auto w/ commas!:[,]General|[break]:|00:00|000:000|0000:0000|00000:00000|[break]:|%loc!Formula!:formula|%loc!Hidden!:hidden|[newcol]:1234:0|1 234:#,##0|1 234.5:#,##0.0|1 234,56:#,##0.00|1 234,567:#,##0.000|1 23,.5678:#,##0.0000|[break]:|1 234%:#,##0%|1 234,5%:#,##0.0%|1 234,56%:#,##0.00%|[newcol]:|1 234 €:#,##0 €|1 234,5 €:#,##0.0 €|1 234,56 €:#,##0.00 €|[break]:|(1 234):#,##0_);(#,##0)|(1 234,5):#,##0.0_);(#,##0.0)|(1 234,56):#,##0.00_);(#,##0.00)|[break]:|(1 234€):#,##0_)€;(#,##0€)|(1 234,5€):#,##0.0_)€;(#,##0.0€)|(1 234,56€):#,##0.00_)€;(#,##0.00€)|[newcol]:|1.4.06:m.d.yy|01.04.2006:mm.dd.yyyy|2006-01-04:yyyy-mm-dd|4-Jan-06:d-mmm-yy|04-Jan-2006:dd-mmm-yyyy|Janvier 4, 2006:mmmm d, yyyy|[break]:|1\\c23:h:mm|1\\c23 PM:h:mm AM/PM|1\\c23\\c45:h:mm:ss|01\\c23\\c45:hh:mm:ss|26\\c23 (h\\cm):[hh]:mm|69\\c45 (m\\cs):[mm]:ss|69 (s):[ss]|[newcol]:|2006-01-04 01\\c23\\c45:yyyy-mm-dd hh:mm:ss|Janvier 4, 2006:mmmm d, yyyy hh:mm:ss|Mer:ddd|Mercredi:dddd|",

**Comment by eddyparkinson** [comment]
Fix formatting - 
 I changed both fr.json and de.json using the formats you posted. Hope this works. Please download and test if possible. 
https://github.com/audreyt/ethercalc/blob/master/l10n/de.json

**Comment by nschlia** [comment]
Tested the latest git version: Works as it should. The date format is correct, currency also.

The only problem that remains is that dates look like this 29,04,2017, the dots are still replaced with kommas. I guess the reason is somewhere.
