### ISSUE TITLE
Ethercalc crashed with Fatal error in v8::ToLocalChecked

### ISSUE THREAD

**Issue by ldidry** [audreyt/ethercalc#515]
Yesterday, I migrated my ethercalc to another server and upgraded it from 0.20160612.0 to 0.20170303.0, and installed node to v6.10.3 instead of v4.8.3.

All was fine but it crashed during the night, saying:

```
#
# Fatal error in v8::ToLocalChecked
# Empty MaybeLocal.
#
Illegal instruction
```

It crashed 80 times during the night (at very different times, from yesterday 21:26 to this morning 02:05) and was restarted by systemd each time… except for the last one.

The calc accessed just before it crashed are not the same, neither are the users.

Does anybody have an idea? It looks similar to https://github.com/audreyt/node-webworker-threads/issues/73 which ethercalc use, but it's been solved 2 years ago.

**Comment by eddyparkinson** [comment]
What version of web workers is installed?

**Comment by ldidry** [comment]
0.7.11

**Comment by eddyparkinson** [comment]
webworker-threads readme:-
---
>requires ...  a working **node-gyp toolchain**.
see  https://github.com/audreyt/node-webworker-threads/blob/master/README.md

**Comment by ldidry** [comment]
> requires ... a working node-gyp toolchain.

Well… if it compiles, it means that I have a working node-gyp toolchain, doesn't it?

I installed it in my home on the server, no error:

```
npm install webworker-threads

> webworker-threads@0.7.11 install /home/luc/node_modules/webworker-threads
> node-gyp rebuild

make: Entering directory '/home/luc/node_modules/webworker-threads/build'
  CXX(target) Release/obj.target/WebWorkerThreads/src/WebWorkerThreads.o
  SOLINK_MODULE(target) Release/obj.target/WebWorkerThreads.node
  COPY Release/WebWorkerThreads.node
make: Leaving directory '/home/luc/node_modules/webworker-threads/build'
/home/luc
└─┬ webworker-threads@0.7.11 
  ├── bindings@1.2.1 
  └── nan@2.6.2 

npm WARN enoent ENOENT: no such file or directory, open '/home/luc/package.json'
npm WARN luc No description
npm WARN luc No repository field.
npm WARN luc No README data
npm WARN luc No license field.
```

**Comment by ldidry** [comment]
@eddyparkinson Is it possible to disable webworker-threads in ethercalc?

**Comment by eddyparkinson** [comment]
Yes, 

These 8 lines disable webworkers:-

https://github.com/eddyparkinson/cellmaster/blob/website/src/sc.ls#L40-L48

**Comment by audreyt** [comment]
Or run with `--vm`

**Comment by ldidry** [comment]
Thank you very much!
