### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by berserk82** [audreyt/ethercalc#516]
Does EtherCalc require anything but a webserver to run? (eg. node, frameworks, etc)

**Comment by eddyparkinson** [comment]
Everything is nodejs & optional redis as a DB. - Install node and use npm to auto download. 


**OpenShift**
 1) create openshift account
 2) click -  top right  sheet.cellmaster.com.au 

**redis**
if Redit exists, it will use it. If not it will create a dump file. to store sheet data.
