### ISSUE TITLE
Data lost after reboot the computer

### ISSUE THREAD

**Issue by jthou** [audreyt/ethercalc#517]
Hi, @audreyt ,

Thanks for you creating such a great application. I deployed it on my local server, and did some work on it. But yesterday, after I reboot my the server, all the work is dispeared. And now, I can only see the black datasheets.

Could you help to tell me how to recover the data? It's important to me. 

Thanks!

-Justin

**Comment by audreyt** [comment]
Hi, sorry about the data loss. Did you run a Redis server? Is it possible that the Redis was not running after the reboot?

If you did not run `Redis` then perhaps the working directory changed between the reboots and `dump.json` is located differently?

**Comment by eddyparkinson** [comment]
Suggest you use Redis or backup dump.json -  It looks like Node.js file system does not handle the lock correctly and the file is sometimes replaced with a blank file.
