### ISSUE TITLE
change redis port?

### ISSUE THREAD

**Issue by hajika** [audreyt/ethercalc#519]
my redis is not running under 6379, how can I change the port to redis?

I just did

`$ grep -rl '6379' . | while read line ; do sed -i -e 's/6379/65000/g' "$line" ; done`

but I hope there is another solution :)

**Comment by eddyparkinson** [comment]
**Redis setting**

environment variables :
REDIS_PORT
REDIS_HOST 
REDIS_SOCKPATH 
REDIS_PASS

used here:
https://github.com/audreyt/ethercalc/blob/master/db.js#L10-L11
