### ISSUE TITLE
error: cannot get / 

### ISSUE THREAD

**Issue by hajika** [audreyt/ethercalc#520]
starting ethercalc now works without errors:

```
$ node server.js --host localhost --port 62000
Please connect to: http://localhost:62000/
Starting backend using webworker-threads
Falling back to vm.CreateContext backend
Express server listening on port 62000 in development mode
Zappa 0.5.0 "You can't do that on stage anymore" orchestrating the show
Connected to Redis Server: localhost:65000

```

But when I try to open it in the Browser, it shows only `cannot GET /`. There does not appear any error in the terminal.

**Comment by eddyparkinson** [comment]
Did you put http://localhost:62000/ in your browser, as stated above, and not http://localhost/

Note I use app.js, e.g.

node app.js --host localhost --port 62000

**Comment by hajika** [comment]
it works now with app.js, thx
