### ISSUE TITLE
Create a status board or status twitter account

### ISSUE THREAD

**Issue by patcon** [audreyt/ethercalc#522]
I'm trying to use and introduce Hackfoldr at the organization I'm working with, and I'm a little nervous that twice so far, I've seen the content on my ethercalc sheet go down, and am not sure the proper place to appeal to or flag the outage.

What I'm seeing:
- content disappears
- writing only saves locally, and refreshing shows content disappear
- restore results in JS dialog ("restore failed")

It seems to be back up after 5 minutes, but this seems like a very opaque process. Could we consider making a status board. I suspect there's automation happening that's restarting the service or whatever, but would be rad if that automation also acknowledged its action somewhere publicly, so we could understand how often this happens (or even whether one person is individually causing it somehow). That way, we can make decisions about whether we should use google docs for certain mission critical usage :)

Thanks!

**Comment by eddyparkinson** [comment]
**Restart every 24 hours**

Restarting every 24 hours fixes this.

Which server are you using?
https://ethercalc.org/
https://ethercalc.net/
https://framacalc.org/
sheet.cellmaster.com.au
https://sandstorm.io/

Options:

- https://sandstorm.io/ this has maybe the best support

- OpenShift with redis - Create an open shift account with redis and run on your own server. Use the top right link on http://sheet.cellmaster.com.au/  and add this auto restart code https://github.com/eddyparkinson/cellmaster/blob/treesforlife/.openshift/cron/minutely/timetrigger#L17-L21

- talk with audreyt  if you are using ethercalc.org or ethercalc.net

 
Yes, https://github.com/audreyt/ethercalc does crash after a day or two and will auto restart the next time you use it. 
I added an auto restart every 24 hours to sheet.cellmaster.com.au

**Status board or status twitter**
There is a status timestamp here http://sheet.cellmaster.com.au/status/app
 it updates every 60 mins. It could be changed to every min.

it uses openshift cron job - this script https://github.com/eddyparkinson/cellmaster/blob/website/.openshift/cron/hourly/pollsheet

**Comment by patcon** [comment]
Thanks so much for the response!

(I didn't think to clarify, but I'm using ethercalc.org through hackfoldr.org)

While I can't use sheet.cellmaster.com.au, I'm sure other will appreciate the results of the auto-restart, so thank you!

I will leave this open, but I would understand if a maintainer wished to close this as-is (seems like it's perhaps overly platform-centric, not project-centric.

**Comment by eddyparkinson** [comment]
@audreyt are you able to add a auto restart to the ethercalc.org server. Restarting every 24 hours would fix the problem. ... The problem is ethercalc crashes after a few days and does not re-start until someone tries to use it, causing the service to be unusable while it is restarting.

**Comment by audreyt** [comment]
ethercalc.org now restarts every 24 hours.
