### ISSUE TITLE
how to start?

### ISSUE THREAD

**Issue by hajika** [audreyt/ethercalc#524]
ok Iam confused now.

There is `server.js`, `app.js`, `bin/run.sh`, `bin/runSafe.sh`, `bin/ethercalc` to start the software. Which one should I use? With `app.js` and `server.js` I can use for example `--port 60000`, but in `run.sh` I can change the env_var for Redis, but dont know how to change the server port then.

So, why is there so many possibilities to start the server and what should I use when I want to use another port than 8000 for the webserver and have Redis working on another port than the default one?

edit: just did a diff, actually there is not any difference between `app.js` and `server.js` ...

**Comment by eddyparkinson** [comment]
app.js is the master that starts ethercalc.

- app.js - is used by make. I use "node app.js" 
- bin/ethercalc is a binary wrapper and looks to load and run app.js.
- bin/run.sh runs bin/ethercalc
- runSafe.sh sends a status/error email and runs bin/run.sh
- server.js is a Symbolic Link to app.js (like a shortcut)
