### ISSUE TITLE
endless redirecting

### ISSUE THREAD

**Issue by hajika** [audreyt/ethercalc#525]
I started ethercalc now by using

`export REDIS_PORT=65000; node app.js --host localhost --port 62500`

that also seems to work, and I have a redirect from my subdomain calc.example.com via RewriteEngine

```
RewriteEngine On
#RewriteCond %{HTTPS} !=on
#RewriteCond %{ENV:HTTPS} !=on
#RewriteRule .* https://%{SERVER_NAME}%{REQUEST_URI} [R=301,L]
RewriteRule (.*) http://localhost:62500/$1 [P]
```

It works to open the startpage of Ethercalc, but when I want to open a new sheet like `calc.example.com/test`, Iam redirected all the time and nothing else happens

**Comment by eddyparkinson** [comment]
Socket.IO
----

I assume socket.io is not connecting because of port/firewall issues.

Have you got logs from the server and/or a browser error

**Comment by hajika** [comment]
I do not get any errors from the apache, and I use the same way and tried the same ports that works for other projects. There even does not appear anything on the terminal within the ethercalc process. But when I used `make`, I got an error:

module.js:471
    throw err;
    ^

```
Error: Cannot find module '~/ethercalc/node_modules/zappajs/node_modules/.bin/uglifyjs'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
make: *** [static/ethercalc.js] Error 1

```

**Comment by hajika** [comment]
ok now it works, maybe the use of make was a problem? Thx. But maybe you could put a better installation guide in the Readme.md
