### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by rugk** [audreyt/ethercalc#528]
Could we get a new release at some time? The latest release is from 2015…

**Comment by eddyparkinson** [comment]
You mean NPM? 
It says 4 month ago.  https://www.npmjs.com/package/ethercalc


So these 2 fixes are missing

Prevent crash "TypeError: Cannot read property 'exportCSV' of undefined"
#521 by ldidry was merged 18 days ago • Approved  
 7
Do not try to put in history if name of calc is too long
#518 by ldidry was merged on 1 Jun • Approved

**Comment by rugk** [comment]
Ah, no I meant GitHub. Obviously since 2015 you [forgot to tag your releases](https://github.com/audreyt/ethercalc/releases), so everybody looking at the releases page thinks the latest release was in 2015.
Also, not everybody uses npm. So please tag releases (again).

**Comment by eddyparkinson** [comment]
done
