### ISSUE TITLE
Ethercalc remove new information at 2h00 morning

### ISSUE THREAD

**Issue by gwenaelforestier** [audreyt/ethercalc#530]
Hello,
i use an ethercal in several city, for my work.
Each time i write new issues in afternoon

if you see LOG 
https://ethercalc.org/log/?inscriptionsGENTILLY

last time at 2h00 morning, i have a remove of -906 data.

it s not the first time and i cant work if i loose data

thanks

**Comment by eddyparkinson** [comment]
@audreyt would know. My guess is the server is auto rebooting at that time. As if it runs for more than about 2 days without rebooting it tends to crash. But surprised you lost data, I think that version saves everything to redis. 
I suspect the version with best support is sandstorm.

**Comment by ttcat** [comment]
Same here!

**Comment by audreyt** [comment]
The disk was full. Sorry about that. Fixed.
