### ISSUE TITLE
Revision history button not displayed in Chrome

### ISSUE THREAD

**Issue by patcon** [audreyt/ethercalc#531]
It seems that the button works fine on FF, but it has always been missing for me in Chrome. It also doesn't seem to be linked in any menus, so there is no work-around except telling users to manually type direct link.

It seems the the div with id `restore` isn't in the DOM in Chrome.

### Possible Fixes

1. Fix presumed CSS issue, or
2. Add a menu item to mitigate situations like this with finicky CSS in special-case buttons.

![screenshot](https://i.imgur.com/yo38AOo.png)

```
# Chrome on Ubuntu 14.04
Version 48.0.2564.116 (64-bit)
```

**Comment by patcon** [comment]
Oh! Interestingly, it shows up when using the "back" button.

### Reproduce

1. In Chrome, go to https://ethercalc.org/welcome-to-hackfoldr (button should be missing)
2. Type "google.com" in url bar, and ENTER
3. Click the back button. (button should now be present)

**Comment by eddyparkinson** [comment]
That looks an old version of Chrome (48.0.2564 - 2016-01-20 (Linux, macOS and Windows)) - 

Works with:
Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by patcon** [comment]
Ah, my apt repo was an old one..! Thanks eddy!
