### ISSUE TITLE
[support] Advice on frequent data loss on ethercalc.org

### ISSUE THREAD

**Issue by patcon** [audreyt/ethercalc#541]
Hi there,

I have been introducing [beta.hackfoldr.org](beta.hackfoldr.org) (which is backed by [ethercalc.org](ethercalc.org)) at an organization where I am on contract, [EDGI](envirodatagov.org). I really really love this tool (Hackfoldr), and hope to be able to continue sharing it with others.

### Facts & Feelings

:mag: We use ethercalc.org through beta.hackfoldr.org.
:mag: We update our sheet once or twice a day.
:mag: We are active in Pacific through Eastern timezones.
:mag: We experience fairly frequent data loss (at least once a week).
:heart: I feel the data loss is preventing us from relying on the tool.
:mag: The lost data is *almost* always available in the backup/revision backlog.
:heart: Using the backup/revision backlog seems too complicated for our users.

I'm wondering whether perhaps there might be an edge-case that is only affecting heavy users in timezones opposite Taiwan.

I was hoping to solicit advice on possible solutions before we must otherwise migrate to using another tool in the near future :)

Thanks so much for any consideration!

### Questions

- What time does the restart mentioned in https://github.com/audreyt/ethercalc/issues/522#issuecomment-309226172 occur? That might at the very least help to avoid data loss in my own personal usage of hackfoldr :)

cc: @audreyt

**Comment by audreyt** [comment]
Hi! Sorry about the data loss. It was a while ago when the disk was full, but as of July 18, we are back at `27.6% of 188.53GB` and should be fine.

The backup-and-restart happens around midnight Taiwan time.

To host Hackfoldr independently (and with full permission control), Sandstorm.io has a "LinksHolder" app contributed by PDIS folks.
