### ISSUE TITLE
save share and file permission

### ISSUE THREAD

**Issue by vhp1360** [audreyt/ethercalc#544]
Hello dears,
I could not find the way to save a spread sheet with a name and share it with other persons that allow to someones r/w permission and only r for someones.
I'm wondering if any one assists me.

Thanks

**Comment by eddyparkinson** [comment]
The sandstorm version might do this, it has several share options. https://apps.sandstorm.io/app/a0n6hwm32zjsrzes8gnjg734dh6jwt7x83xdgytspe761pe2asw0

It requires code, but passport https://github.com/jaredhanson/passport has login code, and long term would be a good solution to this problem.

**Comment by ocdtrekkie** [comment]
Yes, the Sandstorm version can do all of that.

**Comment by vhp1360** [comment]
OK!
thanks.
