### ISSUE TITLE
hide columns without arrow.

### ISSUE THREAD

**Issue by robertfernanV** [audreyt/ethercalc#546]
Greetings I'm using google translate I need to hide some columns without giving the user the option to see them, by watching this post [Link](https://github.com/audreyt/ethercalc/issues/390) which is to show them I understand how to hide them via ajax. but I need you not to show the arrows that are when the columns are hidden.

thanks for your help

**Comment by eddyparkinson** [comment]
Standstorm 
---
The standstorm can share read only/read write etc, but does not have a way to share part of a sheet.
https://apps.sandstorm.io/app/a0n6hwm32zjsrzes8gnjg734dh6jwt7x83xdgytspe761pe2asw0

User Interface
---
You can also add a user interface, see http://sheet.cellmaster.com.au/carbonoffset/app
more examples http://sheet.cellmaster.com.au/examples

2 sheets
---
I assume you know you can combine 2 or more sheets and have some of them private. i.e. reference values in another sheet. Again
 standstorm has the best support for this, as it has good control over access rights.

**Comment by robertfernanV** [comment]
>
Good morning, thank you for your response. I'm using google translate, I just need to hide certain columns, I was thinking of a less optimal solution, that would copy the method that hides the cell, but that does not register that change in the socket or redis, but I did not get that part in the code of SocialCalc.js besides I do not know what scripts I need to modify more.

If you know which part of the code I should change I would appreciate it even more, Regards

**Comment by eddyparkinson** [comment]
This line - 
https://github.com/marcelklehr/socialcalc/blob/master/socialcalctableeditor.js#L1633

to see in action:
run in the browser and search for "mousecoltounhide" in  /static/ethercalc.js
add a break point. see https://i.imgur.com/OCO4lf3.png

**Comment by robertfernanV** [comment]
Good evening, thank you very much for your answer. if I am wrong this does not apply if I hide the cell via api ?, since I do this with this link: https://github.com/audreyt/ethercalc/issues/390
and another question where can I add aliases to the columns? Really thank you very much and apologize for the inconveniences

**Comment by eddyparkinson** [comment]
ExecuteSheetCommand 
---

> this does not apply if I hide the cell via api

True. The master for processing all sheet commands is  SocialCalc.ExecuteSheetCommand 
https://github.com/marcelklehr/socialcalc/blob/master/socialcalc-3.js#L1765
 - both the API and the show column button send the command to ExecuteSheetCommand 

Note: ExecuteSheetCommand exists on the server and client. All commands are propagated to both the server and client. 

Named cell/range
---

>where can I add aliases

Ethercalc menu -> Names

**Comment by robertfernanV** [comment]
Good evening, thank you very much for your help. and your time thanks

**Comment by robertfernanV** [comment]
@eddyparkinson  

Hi, I hope you're well, I need to trigger this function.
https://github.com/audreyt/ethercalc/blob/master/player-broadcast.js#L71
from the index.html  but I do not know where to get the sheet parameter, is there a way to get the sheet from the index.html? Thanks for your help

**Comment by eddyparkinson** [comment]
I do like this:

```

	 var spreadsheet =  window.spreadsheet;
	 if (spreadsheet == null) spreadsheet = window.ss
	 var sheet = spreadsheet.sheet;
...
        sheet.ScheduleSheetCommands('sendemail '+emailContents,  false); 

```
https://github.com/marcelklehr/socialcalc/blob/master/SocialCalc.js#L20832

Am guessing you would need to put the code in index.html below

 <script src="./EtherCalc_files/main.js"></script>

**Comment by robertfernanV** [comment]
@eddyparkinson 
Hello, thanks for answering
this is my code 
` $(window).load(function() {`
    ` var spreadsheet =  window.spreadsheet;`
	 ` if (spreadsheet == null) spreadsheet = window.ss`
	`  var sheet = spreadsheet.sheet;`
    `  SocialCalc.OrigScheduleSheetCommands(sheet,"set C hide yes",false,false);`
 `   });`
` Cannot read property 'sheet' of undefined`

I'll explain the context a bit.
the method
https://github.com/audreyt/ethercalc/blob/master/src/player-broadcast.ls#L53

defined in player-broadcast.ls I want to pass you by example
`SocialCalc.ScheduleSheetCommands = (sheet, "set C hide yes", false, false)`

so you do not apply that change to other users
and I need to do it from the index.html
Currently hidden the rows with the api, but in it I do not know if there is a parameter to inform that the change is local and not global

Thank you very much in advance for your answer

**Comment by eddyparkinson** [comment]
'sheet' undefined
---
I don't know what event via index.html would work. What event triggers after sheet is assigned. But below is the flow.


SocialCalc.EditorRenderSheet (ethercalc.js:282)
SocialCalc.TableEditor.EditorRenderSheet (ethercalc.js:259)
SocialCalc.CreateTableEditor (ethercalc.js:272)
SocialCalc.TableEditor.CreateTableEditor (ethercalc.js:259)
SocialCalc.InitializeSpreadsheetControl (ethercalc.js:823)
SocialCalc.SpreadsheetControl.InitializeSpreadsheetControl (ethercalc.js:809)
onLoad (main.js:453)
onReady (main.js:377)

SocialCalc.EditorRenderSheet (ethercalc.js:282)
SocialCalc.TableEditor.EditorRenderSheet (ethercalc.js:259)
SocialCalc.CreateTableEditor (ethercalc.js:272)
SocialCalc.TableEditor.CreateTableEditor (ethercalc.js:259)
SocialCalc.InitializeSpreadsheetViewer (ethercalc.js:944)
SocialCalc.SpreadsheetViewer.InitializeSpreadsheetViewer (ethercalc.js:941)
SocialCalc.InitializeSpreadsheetControl (ethercalc.js:823)
SocialCalc.SpreadsheetControl.InitializeSpreadsheetControl (ethercalc.js:809)
onLoad (main.js:453)
onReady (main.js:377)

SocialCalc.ScheduleRender (ethercalc.js:381)
SocialCalc.TableEditor.ScheduleRender (ethercalc.js:266)
SocialCalc.EditorSheetStatusCallback (ethercalc.js:289)
p (ethercalc.js:160)
SocialCalc.RecalcTimerRoutine (ethercalc.js:165)

SocialCalc.ScheduleRender (ethercalc.js:381)
SocialCalc.TableEditor.ScheduleRender (ethercalc.js:266)
data (main.js:273)
(anonymous function) (zappa.js:75)

SocialCalc.EditorRenderSheet (ethercalc.js:282)
SocialCalc.TableEditor.EditorRenderSheet (ethercalc.js:259)
SocialCalc.DoRenderStep (ethercalc.js:381)
(anonymous function) (ethercalc.js:381)

SocialCalc.ScheduleRender (ethercalc.js:381)
SocialCalc.TableEditor.ScheduleRender (ethercalc.js:266)
SocialCalc.RecalcTimerRoutine (ethercalc.js:162)

draw sheet
SocialCalc.EditorRenderSheet (ethercalc.js:282)
SocialCalc.TableEditor.EditorRenderSheet (ethercalc.js:259)
SocialCalc.DoRenderStep (ethercalc.js:381)
(anonymous function) (ethercalc.js:381)

Local change
---
I suspect 
SocialCalc.OrigScheduleSheetCommands

is the best fit. As using ExecuteSheetCommand would jump the queue. But
for what you are doing, I don't think the queue matters.

panel formula
---
Don't think this will help you, but the panel formula hides/shows rows.  

http://sheet.cellmaster.com.au/example_panel/appeditor

https://github.com/marcelklehr/socialcalc/blob/master/formula1.js#L5245
