### ISSUE TITLE
Can not correctly export xlsx from a sample ethercalc by curl in local computer win7 64

### ISSUE THREAD

**Issue by help1234** [audreyt/ethercalc#549]
I try to export xlsx from 
https://ethercalc.org/test
by curl with the following command in CMD windows

`curl -i https://ethercalc.org/_/test.xlsx --output 1.xlsx`

If I do so, I got a .xlsx file but can not be opened correctly.
I read this post [#112 ](https://github.com/audreyt/ethercalc/issues/112)about 'curl -i -X PUT --data-binary @your.xlsx https://ethercalc.org/_/test' is work fine to import. 

Anyone can help on this?

Thanks a lot.

**Comment by eddyparkinson** [comment]
try https://ethercalc.org/test.xlsx

`curl -i https://ethercalc.org/test.xlsx --output 1.xlsx`

**Comment by help1234** [comment]
thank you for your feedback,I still got a error on my own pc with the ZH-CN microsoft office 2013 64bit.
And I also try openoffice , it open with extra messages in cells , I can not figue why, could you reappear this on your side?



![20170906175524](https://user-images.githubusercontent.com/26106811/30106344-b46e0cfe-932d-11e7-9505-bc81ec55c950.png)
![20170906180301](https://user-images.githubusercontent.com/26106811/30106343-b46c9fea-932d-11e7-9148-1dc7eef5e497.png)

**Comment by help1234** [comment]
Dear eddyparkinson:
I got the reason and thank you for your reply upon there, I mistakenly use the curl with -i parameter and 
obviously I did not understand what its means.

`curl https://ethercalc.org/test.xlsx --output 1.xlsx`works great.
