### ISSUE TITLE
Add more sheets to the same spreadsheet

### ISSUE THREAD

**Issue by ashishkataria** [audreyt/ethercalc#553]
Hi,
Is it possible to add more number of sheets to the same spreadsheet.  How can we implement this?

**Comment by eddyparkinson** [comment]
> Just add a = before the name of the sheet like /=foobar

https://github.com/audreyt/ethercalc/issues/316

e.g 
https://ethercalc.org/=many

**Comment by ashishkataria** [comment]
can we have workbooks similar to google spreadsheets ? 
![sheet](https://user-images.githubusercontent.com/3703088/30905051-969a86c0-a328-11e7-86e3-3f11f9f0bf7e.png)

**Comment by ashishkataria** [comment]
And then can i use  SUM function across sheets (spreadsheets) ?

Let's say I have the value "100" in cell reference C9 in Sheet1. I also have the value "100" in cell reference C9 in Sheet2. Also, I have the value "100" in cell reference C9 in Sheet3.
 
In Sheet4 in cell reference C9 I wish to enter a SUM formula which goes across sheets 1 through 3. What procedure do I engage in order to enter a sum formula which comprises all cell references in C9 for sheets 1, 2, and 3, so that the formula in cell reference C9 in Sheet4 shows up as "300"?

**Comment by eddyparkinson** [comment]
Sum Multi-sheet
---

`=sum(many.2!B1:B)
`
e.g.

https://ethercalc.org/=many

Multi-sheet - Feature thread
---

https://github.com/audreyt/ethercalc/issues/138
