### ISSUE TITLE
moving ethercalc redis database to another server

### ISSUE THREAD

**Issue by alantygel** [audreyt/ethercalc#568]
Hi, 

I need to move my ethercalc instance to another server. 

How can I save the redis database containing the current sheets and load it another server?

**Comment by eddyparkinson** [comment]
If you have a lot of sheets, you are better to look at the redis docs on how to backup and restore 

Maybe this 
https://www.digitalocean.com/community/tutorials/how-to-back-up-and-restore-your-redis-data-on-ubuntu-14-04


**Sheet data:**

Get the sheet data like this - for a single sheet:
https://ethercalc.org/_/ma7rils23qhq
https://ethercalc.org/ma7rils23qhq

Then you can paste this as social calc format on the new server.
