### ISSUE TITLE
ethercalc as a javascript component

### ISSUE THREAD

**Issue by pangard** [audreyt/ethercalc#580]
Hello:

Is it possible to use ethercalc as a javascript component?

By which I mean:

Using our favorite web framework to manage the database, users, translations, etc, we render a webpage that goes something like

```
<script src="static/ethercalc.js"/>

<div id="table"></div>
<input type="submit" name="submit" id="submit" class="btn btn-primary"/>


$(function(){
    table = $('#table');
    calc = EtherCalc(table, {
        ...config...
    });
    $('#submit').on('click', function(){
        data = calc.data;
        ...send data to the server...
    });
})

```

So the server provides an initial sheet, which may have some restrictions, then all interaction is client side until user hits the submit button, for instance.

Then the server will handle interaction with the database, etc.

Regards

**Comment by eddyparkinson** [comment]
Can you describe what you are trying to do.  With an example, maybe?

API
---

Ethercalc has and API, see  https://github.com/audreyt/ethercalc/blob/master/API.md
So you can update cell and extract data via the api.

Client
---

There is a client that can be used on its own - without the server. 

Server
---
The server is able to do spreadsheet calculations on its own. It uses redis or json to store the cell data.

**Comment by pangard** [comment]
The idea was to use ethercalc as a table component like handsontable.
Thank you very much for those links, Eddy. They seem to allow very complex uses of ethercalc. I'd say I can build whatever interaction I can think of. I do miss more detailed documentation, but I guess I'll find my way.
So thanks a lot.
