### ISSUE TITLE
Ethercalc always redirects to a sheet called "foobar" in Ownpad

### ISSUE THREAD

**Issue by poVoq** [audreyt/ethercalc#581]
Ethercalc seems to work fine as a standalone  system, but when iframing it in nextcloud via this plugin:
https://github.com/otetard/ownpad

It always just opens a multi-sheet called "=foobar" instead (but displays a different url, one with "%3D" instead of "=" but otherwise the name of the sheet and not "foobar") of the actually referenced one.
I have no idea why this is happening, so any hints under what conditions Ethercalc does that? I doubt it is strictly speaking a Ownpad issue (but rather some sort of security feature of Ethercalc?), but I also opened an issue there:
https://github.com/otetard/ownpad/issues/45

**Comment by eddyparkinson** [comment]
Looks like you are using a non-production version.

foobar is here: https://github.com/audreyt/ethercalc/blob/6d0fc019c7cbd8fe768f07fd99bf5db2c33a0fb0/multi/main.ls#L5 

but I don't think that is production code as https://github.com/audreyt/ethercalc/blob/master/main.js looks to be created with https://github.com/audreyt/ethercalc/blob/master/src/main.ls
 
I don't know what the ethercalc/multi files are for.

**Comment by poVoq** [comment]
I installed the npm version via: "npm i -g ethercalc"

However I run it via an Nginx reverse proxy as a systemd service.

But the strange thing is that when I go to my Ethercalc address directly (and not through the Ownpad Iframe in Nextcloud), everything seems to work as intended, both for single sheets and multisheets.

However this is clearly a multisheet issue as Ownpad always opens those.

**Comment by eddyparkinson** [comment]
Suggest you look for foobar in your /main.js  i.e. your main should match this main https://github.com/audreyt/ethercalc/blob/master/main.js 

which does not have foobar.

**Comment by poVoq** [comment]
My main.js in "/usr/lib/node_modules/ethercalc" also doesn't contain "foobar" and seems to be identical to the one you linked.

**Comment by poVoq** [comment]
See my new comment here, something really strange is happening with the iframe cross site scripting:
https://github.com/otetard/ownpad/issues/45#issuecomment-357415441

**Comment by poVoq** [comment]
If I recall correctly this was now fixed with the latest official docker file.
