### ISSUE TITLE
Segmentation Fault on Docker Image

### ISSUE THREAD

**Issue by Keridos** [audreyt/ethercalc#583]
"npm install -g ethercalc pm2" seems to create a Segmentation fault on alpine linux 3.7 with docker version 17.10.0-ce build ba9946cf23

**Comment by eddyparkinson** [comment]
Please can you paste the output you get.  

I have not seen anyone report a Segmentation fault. Maybe there is a clash with your system setup.

**Comment by Keridos** [comment]
Seems to be an issue with hardened kernels. NodeJS produces segfaults when MPROTECT is on. Disabling the memory protection via paxctl makes it work again.
