### ISSUE TITLE
API : Get last modified date of a spreadsheet

### ISSUE THREAD

**Issue by CreeperLava** [audreyt/ethercalc#586]
For example through a json file that would hold several properties about the spreadsheet. You'd just need a "GET https://ethercalc.org/id/metadata.json".

**Comment by eddyparkinson** [comment]
modified date time
---

It would be possible to add this. Pull requests welcome.

This shows what is currently saved:
https://ethercalc.org/_/ma7rils23qhq

**Comment by eddyparkinson** [comment]
Was added - see:
https://github.com/audreyt/ethercalc/pull/529

**Comment by CreeperLava** [comment]
Wow, fast ! Thank you.
