### ISSUE TITLE
How to automatically get ethercalc version?

### ISSUE THREAD

**Issue by PhilLAL** [audreyt/ethercalc#590]
Hi,
is there a good way to get the ethercalc version?

I would like to get the version and write it into some place, it would help users to know if the installed version is compatible with the plugin they want for instance.

Thank you

**Comment by eddyparkinson** [comment]
Version of installed npm package
---

https://stackoverflow.com/questions/10972176/find-the-version-of-an-installed-npm-package

**Comment by PhilLAL** [comment]
Thank you.
Does this work even if one install ethercalc from github?
