### ISSUE TITLE
How to automatically get ethercalc version?

### ISSUE THREAD

**Issue by PhilLAL** [audreyt/ethercalc#592]
Hi,
is there a good way to get the ethercalc version even if it is not installed ?
I asked this question in #590 but I am not sure this answer solves all possibilities and the ticket is now closed.

I would like to get the version and write it into some webpage, even if it has not been installed with npm.

Thank you

**Comment by eddyparkinson** [comment]
I suspect Git Commit number and  npm are your best options. Options:

- Git Hub releases -https://github.com/audreyt/ethercalc/releases
- Git Commit number
- Package version -  "version": "0.20170704.0", see
 https://github.com/audreyt/ethercalc/blob/abfe9d8265b2e82ca7957e8e986a802e0a6016b1/package.json
- npm version

I don't know of other options. Hope this helps.

**Comment by PhilLAL** [comment]
Thank you.
Do you think @audreyt could have any additionnal idea to complete?

**Comment by audreyt** [comment]
As eddy said, if it's installed through GitHub, the Git commit number is essentially the version number.

Would you like to elaborate more on the use case of the plug-in compatibility mentioned in #590, perhaps as a user story from the viewpoint of one of your users?

**Comment by PhilLAL** [comment]
No, it's ok for me, I just wanted to be sure I did not miss anything, thank you ! :)
