### ISSUE TITLE
One spreadsheet very slow 

### ISSUE THREAD

**Issue by Klink38** [audreyt/ethercalc#610]
Hello 
I installed Etercalc on a dedicated Linux. 
I have one page with formula she's very slow now (when I add something. I must wait 30 secondes)
I'm a beginner in linux and Java 

Did you a solution to increase performance for this page ? 

regards

**Comment by eddyparkinson** [comment]
That does sound slow. Some formulas are slow, such as lookup, best to not have too many of them.  
Use index instead of lots of lookups. This is true even with open office.

What kinds of formulas do you have and how many?

**Comment by Klink38** [comment]
Hello
Thank you for your answer 
I have 2 formulas per line
=IF(IF(AND(B28<>"",F28=""),E28-TODAY(),"")<0,IF(AND(B28<>"",F28=""),E28-TODAY(),""),"")
=j8*k8
I currently have 350 lines.

I have a doubt about the link ethercalc and redis.
Because I test without formula and the page is still a little slow
I tested without formulas and the page 
I search the internet to validate the liason but I found nothing convincing.
do you know a simple method?

**Comment by eddyparkinson** [comment]
This looks simple enough. But it also looks strange. Are you sure you
want to compare "" to 0

Try pasting it into ethercalc.org to see if it is still slow.

**Comment by Klink38** [comment]
Hello I found why my spreadsheet was slow I have a formula to see the last line increase this formaula was to big... 
thank you
