### ISSUE TITLE
Cant open project in browser

### ISSUE THREAD

**Issue by imidimi** [audreyt/ethercalc#613]
Hi @audreyt 

You have developed great application. I have installed it on my linux server. It running properly according to my console showing output, but cant open in browser.

ubuntu@ip-172-31-17-109:~$ ethercalc
Please connect to: http://ip-172-31-17-109:8000/
Starting backend using webworker-threads
Falling back to vm.CreateContext backend
Express server listening on port 8000 in development mode
Zappa 0.5.0 "You can't do that on stage anymore" orchestrating the show
Connected to Redis Server: localhost:6379

**Comment by audreyt** [comment]
But can you open in http://172.31.17.109:8000 ?

If so, perhaps there is a firewall rule preventing access.
