### ISSUE TITLE
vertical text

### ISSUE THREAD

**Issue by furetto** [audreyt/ethercalc#616]
Couldn't find a way to write text vertically such as:
T
E
S
T

**Comment by eddyparkinson** [comment]
You can put html in a cell.  HTML lets you do vertical text. So I assume it is possible but have not tested
See: 
http://sheet.cellmaster.com.au/example_html
http://sheet.cellmaster.com.au/examples

let us know it it works.

**Comment by furetto** [comment]
Yeah, didn't think of that...it works.
Got any clue if that would work with a multi select box too?

**Comment by eddyparkinson** [comment]
You can apply style to widgets. like this  =textbox("") + style(E2) 
http://sheet.cellmaster.com.au/example_style/appeditor
But not sure about multi select box.

There is a Style section in the examples: http://sheet.cellmaster.com.au/examples

**Comment by cardurator** [comment]
Hello, I'm totally ignorant about HTML formatting and can't reach the examples (server not found).
My searches result on CSS transform keyword, and really can't figure out how to use it on a cell.
Could you post here an example for vertical text?

Thanks in advance
