### ISSUE TITLE
Is there a way to update the single cell's value by post or put a json str? 

### ISSUE THREAD

**Issue by help1234** [audreyt/ethercalc#632]
eg:
/_/{id}/cells/{B1}   

for A1 ,the content now is 'red'. 
and the JSON representation  should be 
{'coord': 'B1', 'datavalue': 'red', 'datatype': 't', 'formula': '', 'valuetype': 't', 'readonly': False}

Can I do something like to put a str {'coord': 'B1', 'datavalue': 'BLUE', 'datatype': 't', 'formula': '', 'valuetype': 't', 'readonly': False} to change the value of B1?

**Comment by eddyparkinson** [comment]
The API

e.g.
curl -H "Content-Type: application/json" -X POST http://sheet.cellmaster.com.au/_/curltest -d $'{"command":"set A1 text t c1r1\nset A2 text t c1r2"}'

See https://github.com/audreyt/ethercalc/blob/master/API.md
