### ISSUE TITLE
Is the API call Append Rows [POST] broken?

### ISSUE THREAD

**Issue by ScrumpyJack** [audreyt/ethercalc#640]
On ethercalc latest, I have tried the following simple API calls

> ❯ cat calc.csv
> APPLES,ORANGES,CHERRIES,BANANAS
> 3,1,5,6
> 3,2,3,5
> ❯ cat calc2.csv
> 4,5,34,7
> ❯ curl -X PUT -H 'Content-Type: text/csv' --data-binary @calc.csv https:/localhost/_/sdfgkjhrkltahnvaryatgarnva
> ❯ curl -X GET -H 'Content-Type: text/csv' https://localhost/_/sdfgkjhrkltahnvaryatgarnva/csv
> APPLES,ORANGES,CHERRIES,BANANAS
> 3,1,5,6
> 3,2,3,5
> ❯ curl -X POST -H 'Content-Type: text/csv' --data-binary @calc2.csv https://localhost/_/sdfgkjhrkltahnvaryatgarnva
> {
>   "command": [
>     "loadclipboard cell\\cA1\\cv\\c4\\ncell\\cB1\\cv\\c5\\ncell\\cC1\\cv\\c34\\ncell\\cD1\\cv\\c7\\nsheet\\cc\\c4\\cr\\c1\\ctvf\\c1\\nvalueformat\\c1\\ctext-wiki\\n",
>     "paste A4 all"
>   ]
> ❯ curl -X GET -H 'Content-Type: text/csv' https://localhost/_/sdfgkjhrkltahnvaryatgarnva/csv
> APPLES,ORANGES,CHERRIES,BANANAS
> 3,1,5,6
> 3,2,3,5
> 4,,,

Is this the expected behaviour? Am i doing something wrong?

**Comment by ScrumpyJack** [comment]
{
"command": [
"loadclipboard cell\cA1\cv\c4\ncell\cB1\cv\c5\ncell\cC1\cv\c34\ncell\cD1\cv\c7\nsheet\cc\c4\cr\c1\ctvf\c1\nvalueformat\c1\ctext-wiki\n",
"paste A4 all"
]
}

that is the *output* of the POST method

**Comment by eddyparkinson** [comment]
That works better.  
I assume your error is the last line i.e. "4,,,"

But it works fine for me. I get 

`curl -X GET -H 'Content-Type: text/csv' https://localhost/_/sdfgkjhrkltahnvaryatgarnva/csv`
```

APPLES,ORANGES,CHERRIES,BANANAS
3,1,5,6
3,2,3,5
4,5,34,7

```

Looks like we have different code.

**Comment by ScrumpyJack** [comment]
Just updated and same issue

```
ethercalc@0.20180825.1 | Proprietary | deps: 13 | versions: 115
Multi-User Spreadsheet Server
http://ethercalc.net/

bin: ethercalc

dist
.tarball: https://registry.npmjs.org/ethercalc/-/ethercalc-0.20180825.1.tgz
.shasum: 5cd79bc46bef917a1a8c82d1f4635d1ca9df2f5f
.integrity: sha512-a/mp2pWMHdqQsoNYwXG7K62qS9vU2K+3wcnf4KLYmz5WWNe4HLxq2MjOqLrsOpWPXgpcIayXe/IwkcD2i1w64g==
.unpackedSize: 5.4 MB

dependencies:
cors: *                   j: ^1.0.0                 optimist: *               uuid-pure: *              zappajs: 0.5.x
csv-parse: ^0.0.6         livescript: 1.5.x         redis: 0.12.x             webworker-threads: ^0.7.1
iconv-lite: ^0.4.13       minimatch: *              socialcalc: ^2.3.0        xoauth2: *

maintainers:
- au <audreyt@audreyt.org>

dist-tags:
latest: 0.20180825.1

published 3 weeks ago by au <audreyt@audreyt.org>
```

**Comment by eddyparkinson** [comment]
Clipboard code?

It works here  http://sheet.cellmaster.com.au/sdfgkjhrkltahnvaryatgarnva
but fails here https://ethercalc.org/sdfgkjhrkltahnvaryatgarnva



`$ curl -X POST -H 'Content-Type: text/csv' --data-binary @calc2.csv http://sheet.cellmaster.com.au/_/sdfgkjhrkltahnvaryatgarnva
`
```
{
  "command": [
    "loadclipboard cell\\cA1\\cv\\c4\\ncell\\cB1\\cv\\c5\\ncell\\cC1\\cv\\c34\\ncell\\cD1\\cv\\c7\\nsheet\\cc\\c4\\cr\\c1\\ctvf\\c1\\nvalueformat\\c1\\ctext-wiki\\ncopiedfrom\\cA1\\cD1\\n",
    "paste A4 all"
  ]
}

```

I know I did update the clipboard code a year or 2 ago.

**Comment by eddyparkinson** [comment]
**Append rows:**  https://ethercalc.docs.apiary.io/#reference/0/page/append-rows

@audreyt  I assume this used to work and something broke it. It works on my version. So am guessing something in the last year.

**Comment by eddyparkinson** [comment]
Looks like this line  
https://github.com/eddyparkinson/j/blob/master/j.js#L291

called by J.utils.to_socialcalc(J.read(buf))
