### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by linglingfa1212** [audreyt/ethercalc#643]
npm WARN saveError ENOENT: no such file or directory, open '/Users/***/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Users/***/package.json'

what's wrong?

**Comment by eddyparkinson** [comment]
Are you able to install other software via npm? - Looks like an npm setup issue.

**Comment by linglingfa1212** [comment]
Thanks for your response.
![image](https://user-images.githubusercontent.com/38340208/45990042-c95ea400-c0b0-11e8-90a5-e40c1b7e53f4.png)
Is this installed OK? How can i know it work?

**Comment by linglingfa1212** [comment]
I can't open http://localhost:8000

**Comment by eddyparkinson** [comment]
You should paste  http://localhost:8000 into a browser.

You should have something like this:

```
$ node app.js
Please connect to: http://localhost:8000/
Starting backend using webworker-threads
Falling back to vm.CreateContext backend
Express server listening on port 8000 in development mode
Zappa 0.5.0 "You can't do that on stage anymore" orchestrating the show
Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
  at RedisClient.on_error (C:\cygwin64\home\eddy\cellmaster\node_modules\redis\index.js:196:24)
  at Socket.<anonymous> (C:\cygwin64\home\eddy\cellmaster\node_modules\redis\index.js:106:14)
  at emitOne (events.js:116:13)
  at Socket.emit (events.js:211:7)
  at emitErrorNT (internal/streams/destroy.js:64:8)
  at _combinedTickCallback (internal/process/next_tick.js:138:11)
  at process._tickCallback (internal/process/next_tick.js:180:9)

==> Falling back to JSON storage: ../dump.json
==> Restored previous session from JSON file

```

**Comment by linglingfa1212** [comment]
![image](https://user-images.githubusercontent.com/38340208/45991347-0f1e6b00-c0b7-11e8-82ac-c68a91027ddb.png)
I got this result.

**Comment by linglingfa1212** [comment]
thanks for you help. I got the site.
![image](https://user-images.githubusercontent.com/38340208/45995251-e3f14700-c0c9-11e8-8af2-e6895cb9fa4b.png)
But how i can run it in background.

**Comment by eddyparkinson** [comment]
run a Unix process in the background
---

node app.js &

see:
https://kb.iu.edu/d/afnz

**Comment by linglingfa1212** [comment]
thanks for your all help
