### ISSUE TITLE
API doesn't work when $id has a character "@" 

### ISSUE THREAD

**Issue by kujiy** [audreyt/ethercalc#645]
A spread sheet named like "http://localhost/abc@xyz" works but causes an error with "http://localhost/abc@xyz.csv"

Is there a temporally solution? I shared this URL to lots of people so don't want to change the URL but need to get it as any machine readable format.

**Comment by eddyparkinson** [comment]
Try editing main.js
replace both:
 room = encodeURIComponent(this.params.room).replace(/%3A/g, ':');
with 
 room =this.params.room

this is untested. Don't know if it will work.

**Comment by kujiy** [comment]
@eddyparkinson Thank you!!
