### ISSUE TITLE
Scrolling in form view

### ISSUE THREAD

**Issue by lmo-reira** [audreyt/ethercalc#647]
Hi,

First of all, thks alot for all the work put into this tool.
I'm digging into the functionalities of ethercalc, and I'm very very very very impressed by the possibilities provided by this piece of software.

During my tests, I noticed something : the form view seems to have a limited size which is the size of the screen.
There is no scrollbar, and even by zooming out in my browser, everything that was outside of the screen is simply cut out.

Is there a workaround, or did I just miss something ??

**Comment by eddyparkinson** [comment]
The issue was mobile. To make it work on mobile I removed the scroll bars. 
But you should have the browser scrollbar. So it should work. 

Try: http://sheet.cellmaster.com.au/carbonoffset/form

It is a workaround and could be improved.

**Comment by lmo-reira** [comment]
Hi Eddy,

Thks for your reply.
I'm not on mobile, I'm on a laptop (testing with both firefox and chromium on a debian 8).

I did more tests following your answer, here is what I noticed : 
- when not using the panel() function, I do not have any scrollbar at all
- when using the panel() function, I do have the browser scrollbar, but it is always the same size whatever the panel size is

When using the panel() function, I can get up to ~140 lines and column X, everything else is cut off.
When not using this function, I only can get up to 50 lines and column X.

**Comment by lmo-reira** [comment]
Hi all,

I finally noticed the scrollbar was working nicely *after* changing a panel.
So I tried to put a splash() + a panel(), and this way I got the correct scrollbar when loading the form.

I guess I can say the problem is kinda solved.
