### ISSUE TITLE
XLSX import from start page broken

### ISSUE THREAD

**Issue by loleg** [audreyt/ethercalc#651]
The file `/static/xlsx.core.min.js` referenced from [start.html](https://github.com/audreyt/ethercalc/blob/master/start.html) is 404, leading to a console error (to the user it looks like the upload is frozen) when trying to upload an XLSX file from the home page.

![screenshot from 2018-12-02 08-58-45](https://user-images.githubusercontent.com/31819/49337264-0d21dc80-f611-11e8-8b60-b69bcf233f8d.png)

Looks to me like a deployment issue.

**Comment by eddyparkinson** [comment]
Reproduce the error
---
I could not reproduce. 
I dropped a xlsx file on https://ethercalc.org and all worked as expected.

**Comment by loleg** [comment]
@eddyparkinson I've just tried on a different machine, in three different browsers, and via VPN to exclude some kind of network glitch. Always the same errors ... Could you try clearing your cache / private mode?

**Comment by eddyparkinson** [comment]
@audreyt  this gives a not found error:      https://ethercalc.org/static/xlsx.core.min.js   Looks to cause the above issue.

**Comment by audreyt** [comment]
Fixed, thanks.

**Comment by loleg** [comment]
Tested & confirmed. Thank *you*!
