### ISSUE TITLE
R software integration

### ISSUE THREAD

**Issue by mrchristian** [audreyt/ethercalc#652]
Hi,

I'm a researcher looking at how to make scientists research workflows FOSS.

I am interested to see if Ethercalc and be made to work with 'R' statistical software in a programmatic way as how R is used with Google Sheets. There exists a package for R to work with Google Sheets googlesheets: https://cran.r-project.org/web/packages/googlesheets/

We would like to see something like this for Ethercalc, then we would make a researchers workflow fully #FOSS as this is our missing building block.

Does something like this exist already?

This is a link to our research PAD for the explorations:

https://pad.dyne.org/pad/#/1/edit/f1F8ONQkjg1HbGIgiO4D6g/1zZVhXslyZTFkeW2+UPEEVtb/

'Making a FOSS Research Workflow' based on a keynote presentation from the 13th Munin Conference (Tromsø, Norway) by Dr. Corina Logan, "We won't be... 'Bullied into Bad Science'", 28.11.2018, slides (slide 25: Being open & transparent saves time & improves research): https://osf.io/sy9f7/

All best

Simon

**Comment by eddyparkinson** [comment]
Rest API
---

There is an API http://docs.ethercalc.apiary.io/
