### ISSUE TITLE
data loss after server restart

### ISSUE THREAD

**Issue by sebalis** [audreyt/ethercalc#653]
Hi. I have installed a simple, standalone installation of Ethercalc (dedicated virtual machine, software globally installed as root using npm not Docker, ethercalc runs as a service using a dedicated user identity, no Redis, Apache proxy). An early morning cron job exists to update the software using npm, and if an update has been installed the service restarts. Also because the memory used by the server process seems to be growing slowly, the update cronjob also restarts the server if it is a Monday morning.

Recently I have observed that all sheet contents are lost after these restarts, I’m fairly sure that this is new behaviour. Users opening their old sheets see no content at all. I have tried restoring the snapshot files in $HOME/data/dump from our daily backups, but that does not help (with or without a server restart). I can manually copy the contents of a pre-restart snapshot file into the Ethercalc clipboard (cutting out leading and trailing lines and adding a “copiedfrom” line seems to be necessary for the Paste action to work). But that is of course not sustainable. Any ideas what else I could do?

**Comment by eddyparkinson** [comment]
Sorry for the data loss

@audreyt any recent changes that might impact dump files? 

@sebalis have you any idea of a date. When did this start.

Is switching to redis an option?

It sounds like it might be the dump file reverting to loading dump.json or some directory setting, and it is trying to load the files from the wrong location. 

Does it load any sheets correctly?

**Comment by sebalis** [comment]
It’s hard to say when this started. I have daily backups for a week, then weekly for a month and then three more months. For a snapshot file to be reduced to the size for a new sheet there seem to be two necessary conditions: the server restart and an attempt to connect to the sheet with some interaction. I just compared listings and the first instance of a sheet snapshot file being reduced was between 26 Nov and 14 Dec. There were no software updates in this time and the server is not used much yet. There were several instances after the weekly server restart of this Monday morning (17 Dec) that I repaired. Maybe it is just this one weekly restart that went badly wrong.

About Redis: I could definitely use it. Reasons not to do that were that I didn’t know this software and wanted to avoid having to learn how to install, configure and maintain it, also I liked the fact that the state of my Ethercalc instance would be represented in plain files so that in cases of problems I could go to these files for analysis and even repairs.

**Comment by eddyparkinson** [comment]
Daily Reboot
---
I did have the same problem. When I switched to a daily reboot the problem more or less vanished. I think I saw the problem once when there was heavy usage. But I have not seen this in the last year or so.

It looks to be a problem with locking. When ethercalc crashes, the file remains locked. Might be better to use a tmp file to indicate dump files are locked.

**Comment by sebalis** [comment]
Since I did not get any promising leads here, and reliably experienced full data loss after every server restart (no matter how frequently or rarely I restarted), I have now sought to get away from the issue by adding Redis to my installation. It was very straightforward and seems to have solved the problem completely. The one thing I miss is having text files storing the state of my tables so I can restory in an easy (but manual) way if needed. On the other hand I hope that this will not be needed anymore.

I still think that this bug should be of interest to the developers and should therefore remain open. It should be easy to replicate my setup. I will provide details on request but basically it is an installation via rpm in which a dedicated user runs the ethercalc command in its home directory, started as a service via two scripts that I could pass on, with an Apache proxy in front.

**Comment by eddyparkinson** [comment]
Agree, it would be good to get it fixed. Sadly I find it hard to replicate. It only happens after a large volume of usage. This makes it hard to debug.  Do you have a consistent way to replicate it with only a one or 2 changes to a sheet?

**Comment by GStainburn** [comment]
I have just experienced the same problem. I restart ethercalc (to enable ssl) and after restarting my one live spreadsheet is now empty.  The directory listing below shows that the snapshots are all the same size, and looking at them they all contain no data.  The last one (11:56) is after the restart and is identical.

The audit file is intact.  My questions are:

1) why would the snapshots be empty?
2) why would restarting the server clear the sheet (Presumably linked to 1) ?
3) Is it possible to restore from the audit file?

**Comment by GStainburn** [comment]
Sorry, forgot to include the file list

[root@ollie2 dump]# ll *73ue*
-rw-r--r-- 1 root root 14613 Sep 27 12:00 audit-73ue2aggf664.txt
-rw-r--r-- 1 root root   642 Sep 20 14:38 snapshot-73ue2aggf664.2_formdata.txt
-rw-r--r-- 1 root root   642 Sep 20 14:38 snapshot-73ue2aggf664.2.txt
-rw-r--r-- 1 root root   642 Sep 20 14:39 snapshot-73ue2aggf664.3_formdata.txt
-rw-r--r-- 1 root root   642 Sep 20 14:39 snapshot-73ue2aggf664.3.txt
-rw-r--r-- 1 root root   642 Sep 20 14:39 snapshot-73ue2aggf664.4_formdata.txt
-rw-r--r-- 1 root root   642 Sep 20 14:39 snapshot-73ue2aggf664.4.txt
-rw-r--r-- 1 root root   642 Sep 20 14:39 snapshot-73ue2aggf664.5_formdata.txt
-rw-r--r-- 1 root root   642 Sep 20 14:39 snapshot-73ue2aggf664.5.txt
-rw-r--r-- 1 root root   642 Sep 27 11:56 snapshot-73ue2aggf664_formdata.txt
-rw-r--r-- 1 root root   642 Sep 27 12:00 snapshot-73ue2aggf664.txt
[root@ollie2 dump]#

**Comment by eddyparkinson** [comment]
sorry for the data loss. 

**Audit File**
I am have not looked at the audit much, but think it resets every time the server restarts.  This is because the client and server share the same code, and the client starts a new audit when it opens the sheet. 

**empty files**

>1.why would the snapshots be empty?
>2. why would restarting the server clear the sheet (Presumably linked to 1) ?

I think this happens if something causes node to crash. But as I said above, I am not able to recreate the problem. So is hard to get to the bottom of the issue.

**Comment by GStainburn** [comment]
I have just had this happen to me again. I rebooted the server after a yum update updated the kernel.
The next time I went in to my ethercalc spreadsheet it contents are gone. The snapshot file are empty. The audit file is still there.

Question 1: is there a way to restore from the audit?
Question 2: Why does the data keep getting lost, and what I can do to prevent it?

[root@ollie2 dump]# ll *transit*
-rw-r--r-- 1 root root 12447 Nov  4 12:51 audit-transit_injectors.txt
-rw-r--r-- 1 root root   642 Nov  4 12:51 snapshot-transit_injectors_formdata.txt
-rw-r--r-- 1 root root   642 Nov  4 12:51 snapshot-transit_injectors.txt
[root@ollie2 dump]#

**Comment by eddyparkinson** [comment]
Restore from audit:
---

`$ curl -H "Content-Type: application/json" -X POST https://sheet.cellmaster.com.au/_/gstainburn -d '{"command":["set B2 text t hello world2","set B5 formula B2"]}'
`

returns:

```
{
  "command": [
    "set B2 text t hello world2",
    "set B5 formula B2"
  ]
}

```

Note: Requires a valid json. You could use sed or an editor to add quotes and commas.

**Comment by GStainburn** [comment]
> ## Restore from audit:
> 
> `$ curl -H "Content-Type: application/json" -X POST https://sheet.cellmaster.com.au/_/gstainburn -d '{"command":["set B2 text t hello world2","set B5 formula B2"]}' `
> 
> returns:
> 
> ```
> {
>   "command": [
>     "set B2 text t hello world2",
>     "set B5 formula B2"
>   ]
> }
> ```
> 
> Note: Requires a valid json. You could use sed or an editor to add quotes and commas.

I wasn't able to get this working, but did manage to manually read the audit and recreate the spreadsheet. I still need to find out why the contents is lost on restart.

I have just made sure that I had a valid snapshot, then did a 'service restart ethercalc' on mhy Centos 7 box.  On restart, the spreadsheet is once again empty.  The service file is below.

How do I shut down the ethercalc service and ensure that the spreadsheet contents are persistant?
How do I recover from a saved snapshot? I have Googled this and found that I'm supposed to load this into the clipboard in SocialCalc-save format. However, when I then try to past the clipboard I get the following error 'unknown line type socialcalc'

[root@ollie2 dump]# cat /etc/systemd/system/ethercalc.service 
[Unit]
Description=ethercalc shared web spreadsheets

[Service]
ExecStart=/opt/ethercalc/ethercalc.sh
StandardOutput=null
Restart=on-failure

[Install]
WantedBy=multi-user.target
[root@ollie2 dump]#

**Comment by eddyparkinson** [comment]
To stop ethercalc I use pkill. I have a process that restarts node every day. is uses:

`pkill node`

**Comment by GStainburn** [comment]
Thank you for this.  I have updated my ethercalc.service file.

I have also installed redis and ethecalc now has persistant content.

One last question. As I am now using Redis as back end, am I correct in thinking that if I Google Redis backup/restore, this will provide me with the ability to backup and restore spreadsheets contents?

**Comment by eddyparkinson** [comment]
Backup redis
---

from https://www.digitalocean.com/community/tutorials/how-to-back-up-and-restore-your-redis-data-on-ubuntu-14-04

```
$ls /var/lib/redis
You should see a dump.rdb file. That’s the Redis data. If appendonly is also enabled, you will also see an appendonly.aof or another .aof file, which contains a log of all write operations received by the server.
```

**Comment by GStainburn** [comment]
> ## Backup redis
> 
> from https://www.digitalocean.com/community/tutorials/how-to-back-up-and-restore-your-redis-data-on-ubuntu-14-04
> 
> ```
> $ls /var/lib/redis
> You should see a dump.rdb file. That’s the Redis data. If appendonly is also enabled, you will also see an appendonly.aof or another .aof file, which contains a log of all write operations received by the server.
> ```

Thanks for this. 

I now have a crontab job that stops ethercalc (after comments earlier in the thread) backs up Redis, and restarts ethercalc.  All this works fine and the data is persistant across the restart.
