### ISSUE TITLE
changing cell values on its own.............

### ISSUE THREAD

**Issue by sccmeyerton** [audreyt/ethercalc#656]
Hello... 

I was very impressed by your application. I thought it to be very powerful.

If i copy a cell from excel and insert it into ethercalc, the value is changed, and so much
that it renders the value useless. I have tried changing the formatting to little avail.

Have you any advice?

One example

Excel : 89820000000003808545

Once pasted into ether calc or imported as part of a spread sheet i get this 

Ethercalc : 89820000000003800000

This is the column in the dataset we were trying to use the application to manage. I would not mind to try ethercalc again but just cannot seem to get the value i copied from the clipboard. it shows in the clip board as the value i want, when i click "save to socialcalc clipboard" everything is changed.....

I am still not able to copy and pasted, i tried saving the format to the cells as well as to the entire sheet, i tried every format, however i did find success using import

i have found that i cannot copy a row from one spread sheet to another. same problem with the values

**Comment by eddyparkinson** [comment]
Yes, looks like you hit the limit. 
It looks like a limit of Java Script, as MAX_SAFE_INTEGER = 9007199254740991
And you have more than 16 digits.  It would need to use BigInt etc. 


`
window.spreadsheet.sheet.cells["B2"]

t.Cell {
coord: "B2"
datatype: "c"
datavalue: 89820000000003800000
displaystring: "89820000000004000000"
formula: "89820000000003808545"
readonly: false
valuetype: "n"
}
`

**Comment by sccmeyerton** [comment]
Ah I see. Thank you kindly for the prompt reply. Its a brilliant project
and I wish you the best with it.

Kind regards
