### ISSUE TITLE
export calc with comments

### ISSUE THREAD

**Issue by PhilLAL** [audreyt/ethercalc#658]
Hi,
I noticed that if I export a calc with comment (for example, C2 cell in https://ethercalc.org/0y5rmnqngzyw), I got an error in the cell C2 of the ODS file.
Do you have any idea how to solve this bug?

Regards

**Comment by eddyparkinson** [comment]
@audreyt  ethercalc.org  looks to be down 

@PhilLAL  using CSV? - or if the export code has a bug, we could post the issue and hope it gets fixed, but that is a long shot.

**Comment by PhilLAL** [comment]
Hi Eddy, I tried with CSV and ODS. Both do the same.

Waiting for ethercalc to be up again, I tested the same on framacalc (but I'm not sure the version used) : https://framacalc.org/y9uy2MxS76
On the cell containing the comment, I noticed several cases:
- when the cell contains a formula (e.g. F3), an error is printed in the cell of the exported ODS
- when the cell contains a text (e.g. C2) or a number (D2), the comment is not exported

**Comment by eddyparkinson** [comment]
Export of comments
---
As far as I can tell, exporting of comments does not work, looks like there is no such feature.

Exporting comments sounds a long shot. The export code comes from https://github.com/sheetjs I think it changed to sheetjs/js-xlsx  But getting fixes merged in was a problem. Someone created a fix for exporting formulas and they would not merge it in for a long time. We even created a community fork so we could make changes.  They did merge the fix maybe 1 year ago. 

Someone did create a fork for exporting formatting, not sure if it was merged in.

**Comment by PhilLAL** [comment]
Thank you very much for the context explanation  Eddy :)

**Comment by PhilLAL** [comment]
By any chance, is there a way to avoid fixing this by hand once the export done? 
For instance by not exporting comments in ethercalc moreover than failing exporting them? Could this be a solution or not? I absolutly don't know the code.
