### ISSUE TITLE
Can't use cell as criteria

### ISSUE THREAD

**Issue by PimprenelIe** [audreyt/ethercalc#660]
Hello,

I'm trying to use "SUMIF" and it's not works as I want ^^' 

I use that command in D1: `=SUMIF(A:A,C1,B:B)`
And : 

- A1 contains Caro
- A2 contains Caroline
- B1 & B2 contains 1
- C1 contains Caro

In D1, I should have 1 but I've 2 as response because Caro is different of Caroline.

Maybe I don't write the test correctly. Somebody can teach me please ? =)

Nico.

**Comment by eddyparkinson** [comment]
try:
=sumif(A1:A2,"="&C1,B1:B2)

But yes you would expect it to default to "="  not sure what it defaults to and if other spreadsheet use a different default.
Looks like the docs could do with updating to make things clear.

**Comment by PimprenelIe** [comment]
Awesome, thank you !

Yes, I think the little section in the menu of functions for the sumif function could be improve =) 

But thank you already for your work !
