### ISSUE TITLE
Can a recalc be initiated as a Command?

### ISSUE THREAD

**Issue by benhempstead** [audreyt/ethercalc#662]
Awesome software, I've been using it for a month or so. 
I'm wondering if a recalc can be initiated. The reason I ask is I'm running into an issue when I execute a list of commands. For example, I have a button in A1. The command tied to it is =COMMAND(A1,D314:F314) where D314 through F314 all contain commands (set/empty/injecting some code for html display,etc). 
What I think is happening is Command1 executes, but the cells affected by the execution of Command1 don't have time to recalculate before Command2 executes and so on. 
If I separate out the commands in D314:F314 to each have their own buttons and click each in sequence, it works beautifully. This makes me think that if I can initiate a recalc between commands, my problem would be solved. Is there a way to do this, or maybe even a command to pause for n seconds before executing the next command? I would like to do the operation as one button click instead of multiple button clicks. Thanks.

**Comment by eddyparkinson** [comment]
Recalc command
---

set E4 value n 9
recalc
"set E7 value n "&E5

E2:3
E3:4
E4:1
E5:=sum(E2:E4)

16

What is the use case
---
Why is this needed, you should have all the data needed to pre-calculate everything before the state change. Did I miss something?

Risk
---
I did think of adding this, but it is not how spreadsheets work. Recalc is a background process as sometime it can take several seconds to recalc.  So if your spreadsheet has a lot of calculations, it might not complete the recalc before doing the next command.
