### ISSUE TITLE
Upgrade Node.js & modules

### ISSUE THREAD

**Issue by thany** [audreyt/ethercalc#667]
You should upgrade to and support Node.js 8.x at the very least, preferably 10.15 LTS (latest, supported until EOL in April 2021).

The dockerfile and the documentation recommend Node.js 4.x, which has been EOL for a while. Node 6.x is also EOL since recently. EOL means no support, no support means possible security issues and other bugs that won't be resolved.

The same goes for required modules: they too will contain bugs that are known by now, and likely solved in more recent versions. Those versions will likely not support such an old version of Node.js.

See also: https://nodejs.org/en/about/releases/

**Comment by eddyparkinson** [comment]
Pull requests are welcome. As always the issue is lack of time/money.

**Comment by thany** [comment]
That is understandable, but since using old libraries and frameworks can impose a real security risk (search engines all full of resources on this), I feel this should deserve some priority. But when you close this issue, it feels more like you don't care much for this. I hope that's not the case. This is a great project that deserves love 😃

Unfortunately I myself also don't have the time to do it, so who am I to talk 🙊

**Comment by eddyparkinson** [comment]
We do care about security.  Sorry, this is a duplicate issue, so I closed it. 

This describes the core issue: 
https://github.com/audreyt/ethercalc/issues/422
