### ISSUE TITLE
Docker image audreyt/ethercalc

### ISSUE THREAD

**Issue by haivala** [audreyt/ethercalc#670]
Can we have update to that?
I was just wondering because the multisheet bug is now fixed...

**Comment by eddyparkinson** [comment]
Context?  what is this about? Is there an issue, or pull request?

**Comment by haivala** [comment]
The image has old code and haven't been updated in ages.
This is the bug I need to have fixed https://github.com/audreyt/ethercalc/pull/665

**Comment by eddyparkinson** [comment]
@audreyt are you able to update the image. Not sure if it means npm or version or both

**Comment by audreyt** [comment]
Sure thing. The image has been updated to today's release (20190703). Ethercalc.org is also updated.
