### ISSUE TITLE
countifs() with multiple ranges and criteria

### ISSUE THREAD

**Issue by ialokim** [audreyt/ethercalc#675]
I'm not sure whether there is another way of achieving this, but I would love to have the function `COUNTIFS` from Excel or [LibreOffice Calc](https://help.libreoffice.org/Calc/COUNTIFS_function), where you can add more than one range and criterion.

**Comment by eddyparkinson** [comment]
DCOUNT(databaserange, fieldname, criteriarange)
Counts the number of numeric values, not blank, text, or error, in the specified field in records that meet the criteria.
 DCOUNTA(databaserange, fieldname, criteriarange)
Counts the number of non-blank values in the specified field in records that meet the criteria.

    On Monday, 22 July 2019, 21:52:58 GMT+9:30, ialokim <notifications@github.com> wrote:  
 
 
I'm not sure whether there is another way of achieving this, but I would love to have the function COUNTIFS from Excel or LibreOffice Calc, where you can add more than one range and criterion.

**Comment by ialokim** [comment]
Okay, cool, didn't know that command. Thanks a lot!
