### ISSUE TITLE
項目啟動沒有項目名稱

### ISSUE THREAD

**Issue by landscape-Melo** [audreyt/ethercalc#676]
您好，美女！
能告知項目如何加上項目名嗎，現在訪問項目默認到斷口號8000，我想加上項目名稱，要不然本地ngnix不好配，謝謝！

**Comment by eddyparkinson** [comment]
@audreyt  I assume this is Chinese. it is not Japanese. I half understand it, but not enough to be able to help.

**Comment by audreyt** [comment]
This is asking how to reverse-proxy ethercalc listening at `localhost:8000/` as a public facing service at `/ethercalc/` with `nginx`.

**Comment by landscape-Melo** [comment]
> @audreyt I assume this is Chinese. it is not Japanese. I half understand it, but not enough to be able to help.
I‘m sorry
I want to know the name of the project to start this project. I am not familiar with the nodejs project, so I don't know how to change the code. I think you can help me. Thank you very much.

**Comment by landscape-Melo** [comment]
> This is asking how to reverse-proxy ethercalc listening at `localhost:8000/` as a public facing service at `/ethercalc/` with `nginx`.
I'm sorry,nginx has already configured a root directory

**Comment by audreyt** [comment]
@landscape-Melo The `location` and `rewrite` directives in nginx is probably what you want. Please refer to this example cnofiguration: https://github.com/audreyt/ethercalc/blob/master/nginx/conf/nginx.conf#L25

**Comment by eddyparkinson** [comment]
To start ethercalc
---

@landscape-Melo 

```
eddy@Eddy-DeskTop-Tosh ~
$ node app.js
Please connect to: http://Eddy-DeskTop-Tosh:8000/
Starting backend using webworker-threads
Falling back to vm.CreateContext backend
Express server listening on port 8000 in development mode
Zappa 0.5.0 "You can't do that on stage anymore" orchestrating the show


```
