### ISSUE TITLE
how to check how much one sheet occupied the memory?

### ISSUE THREAD

**Issue by LiHT2012** [audreyt/ethercalc#677]
How to see how much memory a table occupies in ethercalc or inredis？

**Comment by eddyparkinson** [comment]
Do you want number of bytes, or number of cells with a value?

There is a record kept of the last row & col with a value, if that helps.

You can do like this:
![image](https://user-images.githubusercontent.com/7961707/62847617-66045180-bd16-11e9-8845-a89e99cc73bf.png)

Redis - try to copy the sheet to the clipboard and look at the "SocialCalc-save format" .. this would give you a rough idea of size.
