### ISSUE TITLE
MultiSheet Export ? (ODS, EXCEL)

### ISSUE THREAD

**Issue by sparadrus** [audreyt/ethercalc#680]
Hi,
Sorry for the duplicate, but i'm lost...
I've download ethercalc with git and install wth :  npm i -g ethercalc.
I can't export in ods or excel when we work on multisheet document.
What version of xlsx is necessary? It seems i have 15.1 (install with npm)
I do manuellay copy file in /opt/ethercalc/dist and /opt/ethercalc/static folder ?

In other case, i have this message in debug console : 
Application Cache Error event: Resource fetch failed (404) https://mydomain/static/xlsx.js
I'm behind nginx reverse proxy.
Thanks,
Regards

**Comment by eddyparkinson** [comment]
@audreyt  MultiSheet Export (ODS, EXCEL) looks broken. I get an unreadable document when I export: https://ethercalc.org/=eddytestmulti 
 I assume you did have it working, do you know what version it was working.

**Comment by audreyt** [comment]
This definitely worked in 35afa7276.

I wonder if c028abbc broke the feature by upgrading to a newer `j`?

**Comment by sparadrus** [comment]
Hi Audrey, thanks for reply. I don't understand, you mean i do downgrade "j" ?
Thanks ;)

**Comment by eddyparkinson** [comment]
@sparadrus yes, downgrade would be worth a try, the export uses "j". The conversion to ODS, EXCEL is done by "j".

**Comment by sebalis** [comment]
I just had the same problem, downgraded “j” to 0.4.5 – by editing package.json and executing “npm install”, this was complete guesswork as I’m not into node.js at all. But it seemed to work. My multi-sheet ODS and XLSX exports went from gibberish back to ok-ish (well it would be nice to see my time-formatted cells as time-formatted but I guess that is another issue). Thought I’d let you know.

**Comment by audreyt** [comment]
Thank you for the notice. Fixed for real and released as `ethercalc@0.20191008.0`.
