### ISSUE TITLE
fill with formulas doesn't do as I expect

### ISSUE THREAD

**Issue by setharnold** [audreyt/ethercalc#681]
Hello, I wanted to make a simple modular multiplication table to explain something to a friend on irc. Roughly, it was going to be:

```
  1                           2                         3                         4
1 =MOD(A2*B1, 4) =MOD(A2*C1, 4) =MOD(A2*D1,4) =MOD(A2*E1, 4)
2 =MOD(A3*B1, 4) =MOD(A3*C1, 4) =MOD(A3*D1,4) =MOD(A3*E1, 4)
3 =MOD(A4*B1, 4) =MOD(A4*C1, 4) =MOD(A4*D1,4) =MOD(A4*E1, 4)
4 =MOD(A5*B1, 4) =MOD(A5*C1, 4) =MOD(A5*D1,4) =MOD(A5*E1, 4)
```
(but going up to 10x10, so a little less trivial.)

I wanted to use the fill tool to fill in most of these formulas since it's a bit tedius.

I put in the first formula, `=MOD(A2*B1, 4)`, selected the field, tried to use the fill feature to fill to the right, and got:

```
=MOD(B1*A2,4) =MOD(C1*B2,4) =MOD(D1*C2,4) =MOD(E1*D2,4)
```

-- both multiplicands were moving along with the fill.

What this does is logical but it isn't what I expected.

I fixed the references as I wanted by hand, then tried to use the fill downwards, and that did the same thing.

This behaviour makes it difficult to build the multiplication table as I expected.

ethercalc's really sharp. Well done.

Thanks.

**Comment by setharnold** [comment]
Oh I just found the cool audit feature. That's awesome. Here's a snippet of the audit that I think will help show what I meant better than I could describe it above:

```
set B1 value n 1
set C1 value n 2
set D1 value n 3
set E1 value n 4
set A2 value n 1
set A3 value n 2
set A4 value n 3
set A5 value n 4
set B2 formula MOD(B1*A2,4)
fillright B2:E2 all
filldown B2:E5 all
```

**Comment by eddyparkinson** [comment]
try 
`=mod(B$1*$A2,4)
` in cell B2

**Comment by setharnold** [comment]
On Mon, Sep 9, 2019, 18:09 Eddy Parkinson <notifications@github.com> wrote:

> try
> =mod(B$1*$A2,4) in cell B2
>

This works perfectly! That's a really clever syntax to solve this.

Thanks

>
