### ISSUE TITLE
Multi sheets + /view does not work

### ISSUE THREAD

**Issue by GStainburn** [audreyt/ethercalc#683]
I've just set up an install on my box and I'm really impressed with everything so far. However, I'm struggling with a few things.  I've set up my first sheet which is working fine. 

However, I could not find out how to add multiple sheets. I found that to do this you have to prefix the sheet in the URL with an equals sign. This worked with a new sheet, but when I tried to do this for an existing sheet, 

before:

http://myserver:8000/73ue2aggf664

after:

http://myserver:8000/=73ue2aggf664

the contents were lost. It was as though it was a new worksheet. Is that the case? 

My second problem is that I want to be able to have read only sheets. This works perfectly fine for my single sheet

http://myserver:8000/73ue2aggf664/view

but does not work with a multi-sheet worksheet.  If I try the following URL

http://myserver:8000/=73ue2aggf664/view 

the page load appears to receive a redirect, and the '/view' is lost.

**Comment by eddyparkinson** [comment]
Single sheet
https://ethercalc.org/eddytest1

Multisheet
  https://ethercalc.org/=eddytest1
  creates:   https://ethercalc.org/eddytest1.1

 View:
 https://ethercalc.org/eddytest1.1/view 

 But I don't think you can do:   https://ethercalc.org/=eddytest1/view


Am closing this, but feel free to post questions.
