### ISSUE TITLE
Update ethercalc

### ISSUE THREAD

**Issue by Todymelody** [audreyt/ethercalc#688]
Hi, 
we are using Ethercalc (on Windows with a Redis) since a few years. 
Is there an easy way to update ethercalc? Do I just have to use node.js and typa again "npm install -g ethercalc " ?
And how do I change the language to German? (As it is when using ethercalc.net)
Thank you for any help..i´m really a noob with this

**Comment by eddyparkinson** [comment]
>"npm install -g ethercalc "

npm update
 or
npm update -g

are recommended here: 
https://docs.npmjs.com/updating-packages-downloaded-from-the-registry


>language to German
Should match the language of the browser.

**Comment by eddyparkinson** [comment]
Will close this, let us know how you get on

**Comment by Todymelody** [comment]
[URL=https://www.bilder-upload.eu/bild-7078b6-1570699341.jpg.html][IMG]https://www.bilder-upload.eu/thumb/7078b6-1570699341.jpg[/IMG][/URL]
