### ISSUE TITLE
language json file has incorrect duplicate entries

### ISSUE THREAD

**Issue by joebordes** [audreyt/ethercalc#692]
https://github.com/audreyt/ethercalc/blob/master/l10n/en.json#L36
lines 40, 42, 44 and 46 all have the same "_comment" index which is invalid in JSON

**Comment by eddyparkinson** [comment]
Comments inside a JSON file. How to:
--- 
Someone has added comments to the file.  

See: 
https://stackoverflow.com/questions/244777/can-comments-be-used-in-json

**Comment by joebordes** [comment]
got it. thanks!
