### ISSUE TITLE
CSV import fail.

### ISSUE THREAD

**Issue by cannebergerouge** [audreyt/ethercalc#694]
Installed on CentOS 7 

npm --version
6.13.2
node --version
v13.3.0

ODS and XLSX importation goes well
CSV importation stall on the web page.
with this message on the console:

```
TypeError: X.utils[("sheet_to_" + t)] is not a function                                    
    at /root/ethercalc/node_modules/j/j.js:210:39                                          
    at Array.forEach (<anonymous>:null:null)                                               
    at Object.to_socialcalc (/root/ethercalc/node_modules/j/j.js:206:23)                   
    at IncomingMessage.<anonymous> (/root/ethercalc/main.js:533:34)                        
    at IncomingMessage.emit (events.js:224:7)                                              
    at endReadableNT (_stream_readable.js:1206:12)                                         
    at processTicksAndRejections (internal/process/task_queues.js:84:21)           
```

The public instance at https://ethercalc.net/ goes very well with CSV.

I have tried any kind of csv encoding, UTF-8 and windows one, linux and windows EOL, this do not seem to related to this.

Might be a node.js version related bug, i don't know.

**Comment by eddyparkinson** [comment]
It looks connected to https://github.com/SheetJS/sheetjs you could try a different version

So this line:  
 var X = require('xlsx');        https://github.com/SheetJS/j/blob/master/j.js#L4
 
creates "X", but looks like X.utils[("sheet_to_" + t)] is invalid.  in your version.

This is the main line that links to the package https://github.com/audreyt/ethercalc/blob/master/package.json#L14 
i.e. this package  https://github.com/SheetJS/j

It has a few support files/packages. such as js-harb, js-xlsx

**Comment by cannebergerouge** [comment]
I have the same version of j as there:
https://github.com/audreyt/ethercalc/blob/master/package.json#L14

├── j@1.0.0

Installed harb, xlsx and xlsxjs.  

seem similar to this:
https://github.com/audreyt/ethercalc/issues/687

**Comment by eddyparkinson** [comment]
Yes looks related to #687  same line breaks.

Looks like j.js has changed - my version has
     `to_socialcalc: to_socialcalc, `   https://github.com/eddyparkinson/j/blob/master/j.js#L325
and the new one has 
	`to_socialcalc: util('eth'), `    https://github.com/SheetJS/j/blob/master/j.js#L244

@audreyt  Looks like this line fails 
  https://github.com/SheetJS/j/blob/master/j.js#L210
I think it is trying to call   X.utils.sheet_to_eth(ws)  - but it does not exist.
Thoughts?

**Comment by eddyparkinson** [comment]
workaround - un-tested
---
Use: https://github.com/SheetJS/sheetjs/tree/442c4342df6627a592100612c7152dbe02d03a42

As all versions of SheetJS/sheetjs from Aug 5 2019 are broken

**Comment by cannebergerouge** [comment]
Thanks, I confirm that It can be fixed downgrading **xlsx** version from 0.15.3 to 0.14.5

`sudo npm install -g xlsx@0.14.5`

Now my instance behaving the same as the public server.

**Comment by cannebergerouge** [comment]
xlsx changelog.md

```
## v0.15.1 (2019-08-14)

* XLSX ignore XML artifacts
* HTML capture and persist merges

## v0.15.0

* `dist/xlsx.mini.min.js` mini build with XLSX read/write and some utilities
* **Removed legacy conversion utility functions**

## v0.14.5

* XLS PtgNameX lookup
* XLS always create stub cells for blank cells with comments

```

Probably that _Removed legacy conversion utility functions_ thing on the v0.15.0 version...

**Comment by SheetJSDev** [comment]
Hello and apologies for the confusion!

So we were preparing for a smaller build that omitted some of the niche formats, of which the Ethercalc format is one (no offense).  In the past, we used to have separate utility functions for single-sheet conversions, but that's not a great approach and we phased out the `sheet_to_eth` utility forgetting that Ethercalc still used it.

The conversion is still available through the general workbook writer:

```js
const result = XLSX.write(wb, {
  type:"binary", /* you can change this to "array" or "buffer" depending on where you are running the code */
  bookType: "eth",
  sheet: "name_of_worksheet" /* if omitted, only the first worksheet will be converted */
});
```

The direct equivalent of the old utility function would be:

```js
function sheet_to_eth(ws, opts) {
  // stub workbook
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "Sheet1");
  // call XLSX.write
  return XLSX.write(wb, {type: opts && opts.type || "binary", bookType: "eth", sheet: "Sheet1"});
}
```

**Comment by ocdtrekkie** [comment]
@SheetJSDev By "smaller build that omitted some of the niche formats", would I be correct in assuming the "larger" build will remain available for projects like EtherCalc?

**Comment by SheetJSDev** [comment]
The functionality wasn't removed from the main build, as demonstrated in the sample code above.

It's hard to strike a good balance between script size and functionality.  The final decision was to keep the full build and introduce a slimmer build.

**Comment by eddyparkinson** [comment]
@SheetJSDev  where to put the fix. As there are 2 options I can see:

 **in SheetJS/j/** - single fix
https://github.com/SheetJS/j/blob/master/j.js#L210

or

 **in audreyt/ethercalc** 5 dependencies I found in main.ls - maybe others as well in other files
https://github.com/audreyt/ethercalc/blob/master/src/main.ls

**Comment by ocdtrekkie** [comment]
Well, SheetJS deprecated the function intentionally. Easiest solution is for EtherCalc to add its own sheet_to_eth as described.

**Comment by NexisSis** [comment]
Found the answer, https://github.com/audreyt/ethercalc/commit/efa54c86fc4093231b1cc5a45921b6a3f4a96676 doesn't help, because `"j": "^1.0.0",` package using latest xlsx version, to fix it you need to change xlsx package in `"j": "^1.0.0",` package.json or downgrade `"j": "^1.0.0", => `"j": "0.4.5",`` (past version) in ethercalc

**Comment by eddyparkinson** [comment]
@NexisSis  does the latest version fail for you? 

this fix https://github.com/audreyt/ethercalc/commit/efa54c86fc4093231b1cc5a45921b6a3f4a96676#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 

Can we close this issue, or is it still broken?

**Comment by TofBaasken** [comment]
Hi , I'm experiencing the same issue described here. I'm not really into node.js , and I'm building ethercalc using a dockerfile similar to the one at https://github.com/audreyt/ethercalc/blob/master/Dockerfile

Can you give any advice on dealing with the issue based on this dockerfile ? I tried using customized package.json files but with no success .

Thanks

**Comment by audreyt** [comment]
The fix has been released as part of 0.20200505.0 and so running `docker build --no-cache` again should work.

**Comment by TofBaasken** [comment]
Great, it works !

**Comment by ocdtrekkie** [comment]
I will look at pushing an updated Sandstorm package if this is working again, but I still think the "long term fix" here is to add the code referenced above, here: https://github.com/audreyt/ethercalc/issues/694#issuecomment-565320336 within EtherCalc itself, so that we can use the latest SheetJS.
