### ISSUE TITLE
":" in name (%3A) breaks export

### ISSUE THREAD

**Issue by grinapo** [audreyt/ethercalc#696]
…which is pretty inconvenient since Matrix(/Riot) started to include EtherCalc widget, which creates matrix room named sheets, like: `!vcabRcVAPxxWekOvEd%3Afoobar.org`.

It results 404 on any export.

(Simply disallowing would completely break matrix as it is now, but I try to notify them not to use ":" either.)

**Comment by eddyparkinson** [comment]
The naming could do with a better solution. As we have had other naming issues, maybe still open. 

If I remember correctly there are 2 or 3 places that impact naming, all with different naming rules. A standard section of code for naming would help.

Pull requests are welcome.

**Comment by eddyparkinson** [comment]
unicode sheet names fail with API/curl
