### ISSUE TITLE
The date format : coma instead of dots

### ISSUE THREAD

**Issue by meaz** [audreyt/ethercalc#697]
Dates look like this 29,04,2017, the dots are replaced with comas.

**Comment by eddyparkinson** [comment]
What language? When do you see this, CSV, online spreadsheet?

**Comment by meaz** [comment]
Language: French
I see that in online spreadsheet.
![2020-01-02_10-39](https://user-images.githubusercontent.com/13604424/71660706-36e58f80-2d4c-11ea-83b4-38528e8878b4.png)
You also see that I enter 25/12/2019 but in the cell it is displayed as `12,25,2019`

Following your question, I also tried to export it as CSV. I just have "43824" in the whole csv file.

**Comment by eddyparkinson** [comment]
I get:
![image](https://user-images.githubusercontent.com/7961707/71698086-17ad3780-2e0a-11ea-8135-fb776ebce452.png)

I think this is coming from my OS settings not my browsers settings, as changing my browser's language does not impact this. When I change my browser language, my ethercalc menus change to french, but the date format does not change.

I can use the format menu to change the date format, it has several options.

**Comment by meaz** [comment]
The language is detected, the problem is when you try to edit the format of the cell
![Capture d’écran de 2020-01-03 08-40-46](https://user-images.githubusercontent.com/13604424/71712297-f564eb00-2e04-11ea-9720-28b411f69710.png)
So if you select 04.01.2020 you get 04,01,2020

**Comment by eddyparkinson** [comment]
Looks correct. can you look at this line in your version:

https://github.com/audreyt/ethercalc/blob/master/l10n/fr.json#L167


"SCFormatNumberFormats": "[cancel]:|[break]:|%loc!Default!:|[custom]:|%loc!Automatic!:general|%loc!Auto w/ commas!:[,]General|[break]:|00:00|000:000|0000:0000|00000:00000|[break]:|%loc!Formula!:formula|%loc!Hidden!:hidden|[newcol]:1234:0|1 234:#,##0|1 234.5:#,##0.0|1 234,56:#,##0.00|1 234,567:#,##0.000|1 23,.5678:#,##0.0000|[break]:|1 234%:#,##0%|1 234,5%:#,##0.0%|1 234,56%:#,##0.00%|[newcol]:|1 234 €:#,##0 €|1 234,5 €:#,##0.0 €|1 234,56 €:#,##0.00 €|[break]:|(1 234):#,##0_);(#,##0)|(1 234,5):#,##0.0_);(#,##0.0)|(1 234,56):#,##0.00_);(#,##0.00)|[break]:|(1 234€):#,##0_)€;(#,##0€)|(1 234,5€):#,##0.0_)€;(#,##0.0€)|(1 234,56€):#,##0.00_)€;(#,##0.00€)|[newcol]:**|1.4.06:m.d.yy|01.04.2006:mm.dd.yyyy|**2006-01-04:yyyy-mm-dd|4-Jan-06:d-mmm-yy|04-Jan-2006:dd-mmm-yyyy|Janvier 4, 2006:mmmm d, yyyy|[break]:|1\\c23:h:mm|1\\c23 PM:h:mm AM/PM|1\\c23\\c45:h:mm:ss|01\\c23\\c45:hh:mm:ss|26\\c23 (h\\cm):[hh]:mm|69\\c45 (m\\cs):[mm]:ss|69 (s):[ss]|[newcol]:|2006-01-04 01\\c23\\c45:yyyy-mm-dd hh:mm:ss|Janvier 4, 2006:mmmm d, yyyy hh:mm:ss|Mer:ddd|Mercredi:dddd|",

**Comment by meaz** [comment]
I wonder if this is enough. If my locales are set to en_US then there is no way for me to use other formats the US standards.

**Comment by eddyparkinson** [comment]
How to move things forward? 
It there something that can be done, or do we close the issue?

**Comment by meaz** [comment]
I don't know... You tell me ;)

**Comment by eddyparkinson** [comment]
@Framartin are you able to help with this. is this a bug in https://github.com/audreyt/ethercalc/commits/master/l10n/fr.json ?

**Comment by Framartin** [comment]
I confirm that when I select the format `01.04.2006:mm.dd.yyyy` for a date it is displayed as `01,04,2006:mm,dd,yyyy`. Is it related to the fact that in French the decimal separator is the comma? Maybe all `.` characters are replaced by `,` during the formatting?

**Comment by Framartin** [comment]
Anyway, the format with month first is never used in French. The most common is `04/01/2006:dd/mm/yyyy`. For example, it's the default formatting for dates in LibreOffice with French locale.

**Comment by eddyparkinson** [comment]
Looks like we have different versions. When I swap to french I get "01/04/2006" rather than "01.04.2006"

![image](https://user-images.githubusercontent.com/7961707/73238208-07f5f880-41e8-11ea-9e0c-efacd64a2ea4.png)

Are you able use https://github.com/audreyt/ethercalc/commits/master/l10n/fr.json  
and confirm it shows "01/04/2006" ? 

I assume you also want the french dates swapping to dd/mm/yyyy i.e. the date followed by the month then the year.

**Comment by meaz** [comment]
Indeed dd/mm/yyyy would be much better.

I use [https://github.com/audreyt/ethercalc/commits/master/l10n/fr.json](https://github.com/audreyt/ethercalc/commits/master/l10n/fr.json) but it still shows 01.04.2006 which become comas when I validate. 
I've also tried from https://ethercalc.org in case there was some issue on my server. But I have the same issue:
![ethercalc](https://user-images.githubusercontent.com/13604424/74100375-7d3dc380-4b2e-11ea-85e3-623e6b05edc6.png)

**Comment by eddyparkinson** [comment]
Changed date format from mm.dd.yyyy to dd/mm/yyyy
---

https://github.com/audreyt/ethercalc/commit/ca81358792d17d04521efe9c820a7123909bdf37#diff-9c37fb0ae99db8a7640ec977c63ad76e

I have just changed the format. Please can you replace your l10n/fr.json  
 with https://github.com/audreyt/ethercalc/blob/master/l10n/fr.json 
and test it out.

**Comment by meaz** [comment]
Thanks a lot, it works fine @eddyparkinson
