### ISSUE TITLE
Unicode cells break the export

### ISSUE THREAD

**Issue by loleg** [audreyt/ethercalc#700]
When exporting a spreadsheet with Unicode characters into any format, we can only see garbage bytes:

![Screenshot from 2020-02-22 13-45-50](https://user-images.githubusercontent.com/31819/75092600-aec87d00-5579-11ea-890c-e26e6d5f64fd.png)

**Comment by loleg** [comment]
It looks like export is completely broken, giving either a Python error or server offline exception now. If it's causing grief, it should be disabled.

**Comment by eddyparkinson** [comment]
works fine for me. CSV, HTML, Excel formats but i tested on http://sheet.cellmaster.com.au/

Not sure why. Can you explain your steps to see if we can pin down the cause?
