### ISSUE TITLE
Allow to Freeze Header Rows/Columns while scrolling the rest of the sheet

### ISSUE THREAD

**Issue by jongleur1983** [audreyt/ethercalc#701]
In Excel it is possible to "freeze" a configurable set of rows/columns on the top/left.
Those - usually headers - are stay visible when scrolling the rest of the table after that.

See https://support.office.com/en-us/article/Freeze-panes-to-lock-rows-and-columns-dab2ffc9-020d-4026-8121-67dd25f2508f

This feature would be great to have in EtherCalc as well.

**Comment by eddyparkinson** [comment]
Use the blue bar on the top right, just above the scroll arrow. 

![image](https://user-images.githubusercontent.com/7961707/75204660-60a5ba80-57c1-11ea-9948-d538ae1d2c96.png)

**Comment by jongleur1983** [comment]
@eddyparkinson thanks - didn't see it before. Is there a way to lock COLUMNS as well?

**Comment by eddyparkinson** [comment]
@jongleur1983 The blue bar on the bottom left.

**Comment by jongleur1983** [comment]
Thanks, works like a charm.
