### ISSUE TITLE
Running EtherCalc as background service

### ISSUE THREAD

**Issue by mbressman** [audreyt/ethercalc#703]
I am not sure if closed issues are seen at all, so am posting a new issue since I'm having issues with getting EtherCalc to run as a background service on an Ubuntu Server 18.04 virtual machine.  Any help is appreciated.

See my post here: https://github.com/audreyt/ethercalc/issues/127#issuecomment-593153731

Thanks!

**Comment by poVoq** [comment]
Use the official Docker image: https://hub.docker.com/r/audreyt/ethercalc/

**Comment by mbressman** [comment]
> Use the official Docker image: https://hub.docker.com/r/audreyt/ethercalc/

Thanks for the reply.  I've already gotten it installed using npm and was hoping I could just get it running as a background service with my current install?

**Comment by poVoq** [comment]
See my other old reply. Might have to be adapted for 18.04, but principally it should still work.

**Comment by mbressman** [comment]
> See my other old reply. Might have to be adapted for 18.04, but principally it should still work.

Yup - tried to use your old reply (https://github.com/audreyt/ethercalc/issues/127#issuecomment-354604751) but couldn't get it working.

**Comment by poVoq** [comment]
Try harder :p

Or use the Docker image, which is what I switched to.

**Comment by mbressman** [comment]
I'm a bit out of my element here - that's why I was posting here for some assistance.  I'm happy to hire someone to assist, but this is definitely not my area of expertise.

**Comment by poVoq** [comment]
Hence my suggestion to use Docker, which is super easy.

**Comment by mbressman** [comment]
Honestly I haven't yet learned about Docker - could you perhaps point me in the direction of a good tutorial or site that explains it so I can get a good understanding of it and then use it?  Thanks!

**Comment by poVoq** [comment]
https://lmgtfy.com/?q=docker+tutorial+beginner

Sorry for being a bit smug about it, but if you want to selfhost something you got to be willing to learn. Otherwise it is a lost cause.

**Comment by mbressman** [comment]
I'm very willing to learn - but also am always hopeful that I can get help for problems from the online community.  Time is a major factor, as always.  Unfortunately, it seems right now that instead of just being able to solve this particular problem, I now have to go spend a significant amount of time learning Docker - that was something I was looking to avoid at this particular moment but I guess there's no real alternative :(

**Comment by poVoq** [comment]
I am 99% sure the solution from my other post is still working.

Maybe if you would post what exactly didn't work for you, it would be possible to help.

**Comment by mbressman** [comment]
I followed the instructions but then attempted to browse to the local IP:8000 and EtherCalc didn't launch.  So I'm not sure what the next steps are to figure out why it isn't working, but am happy to perform troubleshooting steps that you recommend to hopefully get it fixed.  Thanks.

**Comment by poVoq** [comment]
Please comment on the other post and post the output of:
`sudo systemctl status ethercalc`

**Comment by mbressman** [comment]
Will do - give me about 5 to 10 mins.  Thanks!

**Comment by eddyparkinson** [comment]
My cron job script.

```
#!/bin/bash
pkill node
cd /home/ethercalc
env TZ='Australia/Adelaide' /usr/local/bin/node app.js &

```

I suspect there are many good ways to run ethercalc in the background, the above is one option that works for me.

**Comment by mbressman** [comment]
Thanks for the help everyone!  I was able to troubleshoot under issue #127 and got it working.
