### ISSUE TITLE
POST to 中文網址 會失敗

### ISSUE THREAD

**Issue by bestian** [audreyt/ethercalc#705]
當POST Request的目標url是中文名
如
`https://ethercalc.org/_/沙盒0`
時

資料就不知道如何被處理了, [沙盒0]((https://ethercalc.org/%E6%B2%99%E7%9B%920)
)上沒有更新

我試過把request的url先做encodeURIComponent，但還是不行

請幫忙debug一下好嗎? 謝謝!

that's my [JSBin](https://jsbin.com/feyuqog/edit?html,js,console,output)
that's my [Ethercalc Sheet](https://ethercalc.org/%E6%B2%99%E7%9B%920)

**Comment by eddyparkinson** [comment]
Chinese -> English
---

當POST Request的目標url是中文名
如
https://ethercalc.org/_/沙盒0
時

資料就不知道如何被處理了, 沙盒0上沒有更新

我試過把request的url先做encodeURIComponent，但還是不行

請幫忙debug一下好嗎? 謝謝!

When the target URL of the POST Request is a Chinese name
Such as
https://ethercalc.org/_/Sandbox 0
Time

The information does not know how to be processed, there is no update on sandbox 0

I tried to encodeURIComponent for request URL first, but still not work

Could you please debug it? Thank you!

Known bug
---

Pull requests welcome  - 拉请求欢迎

Duplicate of https://github.com/audreyt/ethercalc/issues/696

**Comment by MetaJuanitoFatas** [comment]
@audreyt GitHub‘s close not smart enough yet, so we need to manually close this ☺️
