### ISSUE TITLE
'=' ignored in URL when last fragment character

### ISSUE THREAD

**Issue by Luxoboy** [audreyt/ethercalc#711]
Hello,

When I type a URL with a fragment ending with `=` in a cell, the `=` is not included in the link URL.
Exemple [here](https://ethercalc.org/d9nmytpae65e).

Thanks!

**Comment by eddyparkinson** [comment]
Format as link
---

change the format of the cell to a link format

![image](https://user-images.githubusercontent.com/7961707/79525061-24942500-80a1-11ea-9c15-3f0fe80516ea.png)

**Comment by Luxoboy** [comment]
Thanks for the tip.

But it doesn't fix the issue when the cell contains mixed content (text and URL).
Won't argue of course, just reported what I thought was a bug in the URL detection.

Cheers!

**Comment by eddyparkinson** [comment]
@Luxoboy you can format as html, and include a href
see http://sheet.cellmaster.com.au/example_html
