### ISSUE TITLE
Cannot open ethercalc page nor get .csv.json data from ethercalc 

### ISSUE THREAD

**Issue by bestian** [audreyt/ethercalc#713]
Error

"502 Bad gateway"

"Access to XMLHttpRequest at 'https://ethercalc.org/autolearn_main.csv.json' from origin 'http://goban.tw' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource."

**Comment by bestian** [comment]
the bug appears suddenly, then ok again

**Comment by eddyparkinson** [comment]
Strange URL ...  try

https://ethercalc.org/autolearn_main.json
https://ethercalc.org/autolearn_main.csv

**Comment by eddyparkinson** [comment]
Closing this. Please let us know if this has not been resolved.
