### ISSUE TITLE
Multiple sheets impossible ?

### ISSUE THREAD

**Issue by petiard** [audreyt/ethercalc#714]
Hello! (sorry for my bad english...)
I have installed Ethercalc on a server.
I can create a file with one sheet but it's not possible to have multiple sheets.
I've tried with = before the name but it doesn't work.
I can import an ods or xlsx file if it contains only one sheet, but it fails if it contains two or more sheets...

What can I do?

Best regards.

François

**Comment by eddyparkinson** [comment]
Edit muti sheets
----

>I've tried with = before the name but it doesn't work

What happens, do you get an error? 

you should get something like this:
https://ethercalc.org/=eddymulti

Import muti sheets
---

There was an import issue, but this should have fixed it https://github.com/audreyt/ethercalc/commit/acbf6ab2bd8ac873f8b8145990e5e4149b330cd3

More info here https://github.com/audreyt/ethercalc/issues/694

**Comment by petiard** [comment]
> 
> ## Edit multi sheets
> 
> > I've tried with = before the name but it doesn't work
> 
> What happens, do you get an error?
> 
> you should get something like this:
> https://ethercalc.org/=eddymulti

No error but the result is the same sheet, without the bottom (with Add/Rename/Delete).

> ## Import multi sheets
> 
> There was an import issue, but this should have fixed it [acbf6ab](https://github.com/audreyt/ethercalc/commit/acbf6ab2bd8ac873f8b8145990e5e4149b330cd3)
> 
> More info here #694
> 
> e.g. I imported this https://ethercalc.org/=a5m09d7jcc

OK, thank you, I'll try.

François

**Comment by Prillan** [comment]
This is what I fixed here: https://github.com/audreyt/ethercalc/pull/710

**Comment by eddyparkinson** [comment]
Edit multi sheets
---

Should be fixed by https://github.com/audreyt/ethercalc/pull/710

Import multi sheets
---

Looks to be broken, try the workaround suggested here  https://github.com/audreyt/ethercalc/issues/694#issuecomment-612915041
