### ISSUE TITLE
都是有谁在编辑文档

### ISSUE THREAD

**Issue by TianPuJun** [audreyt/ethercalc#718]
https://github.com/audreyt/ethercalc/issues/598
大家下午好，就像上面引用的598，我的问题是是否可以获取当前文档都是有谁在编辑，如果可以的话，该如何进行操作。

非常感谢您的协助，thank you

**Comment by eddyparkinson** [comment]
Google translates this to: 

> "Good afternoon, everyone, like the 598 (Ethercalc - Who Edited)  cited above, my question is whether anyone can edit the current document, and if so, how to proceed.
> 
> Thank you very much for your assistance"
> 

As always, pull requests are welcome. 

I don't think anyone is working on this. The closest solution to this looks to be sandstorm.

**Comment by TianPuJun** [comment]
I am using Google to translate, I think my question should be 
When using ethercalc to open a collaborated excel file, is there an API that can get the current collaborated editor of the excel file, who is editing this excel

**Comment by eddyparkinson** [comment]
No, ethercalc does not have user accounts. But the sandstorm version of ethercalc does have user accounts. You could look at sandstorm, to see if this is possible. I don't know if  the sandstorm version of ethercalc has such a feature or not.

**Comment by TianPuJun** [comment]
Your suggestion is very helpful to me, thank you very much
