### ISSUE TITLE
End of data reached (data length = " + this.length + ", asked index = " + (newIndex) + "

### ISSUE THREAD

**Issue by TianPuJun** [audreyt/ethercalc#720]
When I use put http to request the local excel file and forget to set the content in the ethercalc server file, the server reports an error. I can use postman to request normally and return OK. After using the request http request and setting the contentType, the request fails. My problem is that this is Is the format of the request data encapsulation wrong? If so, how should I modify it? Any of your assistance will be helpful to me, thank you
```
  return request({
    url: url,
    method: 'PUT',
    headers: {
      'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    },
    data: fileStream
  }, function (error, response) {
    if (error) throw new Error(error)
    console.log(response.body)
  })
```

**Comment by eddyparkinson** [comment]
The API docs are here - they include data format info

https://github.com/audreyt/ethercalc/blob/master/API.md

Closing - this, please let us know if the above resolves the issue.
