### ISSUE TITLE
Ethercalc.org is down

### ISSUE THREAD

**Issue by PhilippeBou** [audreyt/ethercalc#725]
Hi,
I'm using some calcs through Ethercalc and very happy with this. But we have someties server or  network shutdowns (502 error bad gateway...). That was the case a few minutes ago.
Can we use these solutions usually with a good level of service or do you suggest to implement our calcs on a different support?
Many thanks for your help and your solutions!!
Best regards .
Philippe Bouchet.

**Comment by johays** [comment]
I can confirm that I am having the same issue. After working on a spreadsheet for 1½ hours today, the server suddenly gave a "502 Bad Gateway / nginx/1.13.8" error. It seemed to happen just as I clicked "export to .ods", but that might also be a coincidence.

**Comment by PhilippeBou** [comment]
Hello,This issue occured several times during the past week. The service was not accessible, sometimes just trying to launch a calc.Thanks for your feedback.BR.Philippe.Le 4 juin 2020 19:07, johays <notifications@github.com> a écrit :

I can confirm that I am having the same issue. After working on a spreadsheet for 1½ hours today, the server suddenly gave a "502 Bad Gateway / nginx/1.13.8" error. It seemed to happen just as I clicked "export to .ods", but that might also be a coincidence.

**Comment by eddyparkinson** [comment]
@audreyt  looks like the server for Ethercalc.org is over loaded. Am guessing covid19 related, but I don't know.

I tried it just now. It is very slow.

**Comment by davidak** [comment]
Still, always **502 Bad Gateway.**

**Comment by davidak** [comment]
Now it works.

**Comment by davidak** [comment]
Now i get

**403 Forbidden**
openresty

**Comment by lr-17** [comment]
Bonjour, je fais suite à Davidak, j'utilise Ethercalc purement de façon pratique et professionnel, je ne connais strictement rien aux lignes de codes, c'est juste un outil collaboratif. Cependant aujourd'hui j'avais une grosse réunion avec un document Ethercalc qui avait été rempli par de nombreux professionnels, mais il m'est impossible de le récupérer car **403 Openresty**
Il faut impérativement que je récupère ce document, pouvez-vous m'aider?

**Comment by audreyt** [comment]
The publicly hosted EtherCalc domain name is now https://ethercalc.net — please change the extant .com and .org URLs to the .net domain & sorry for the inconvenience.
