### ISSUE TITLE
ethercalc.org returns 403

### ISSUE THREAD

**Issue by dietmarposselt** [audreyt/ethercalc#738]
Hi there,

It seems that ethercalc.org returns 403 for several days now. We tried from different clients with different browser.

According to https://doj.me/ethercalc.org it is down since at least three days.

Could you please have a look? Thanks!!!

Regards, Dietmar

**Comment by ocdtrekkie** [comment]
Read #725

**Comment by audreyt** [comment]
The publicly hosted EtherCalc domain name is now https://ethercalc.net — please change the extant .com and .org URLs to the .net domain & sorry for the inconvenience.
