### ISSUE TITLE
Export to xls with sheets/cells having select option

### ISSUE THREAD

**Issue by balaji-ranga** [audreyt/ethercalc#740]
Hi Team,

Facing fewissues  during export/import, please guide in the usage.
1. During export to xlsx where sheets has select function its not exporting the values properly.
2. Cross sheet reference for select is failing the moment we change the value in select the formats changing.
3. During Export/import the format to the cells like background etc.. is not retaining
4. Column level filtering for the sheet , please let know how to enable. 

We are not customizing ethercalac, we are adopting the published npm package.

**Comment by eddyparkinson** [comment]
I could do with more details, as is hard to be sure from the descriptions. But my guess is, they are all hard to fix, and some look like features that don't exist in excel. 

Feel free to add more details, as I may have miss understood. 

I expect you would need to pay a programmer for weeks to months to fix the items that are excel compatible. I am going to close this for now.
