### ISSUE TITLE
Where does the code for the matrix ethercalc widget reside?

### ISSUE THREAD

**Issue by MarkWieczorek** [audreyt/ethercalc#741]
Sorry for the dumb question, but there is a problem with the matrix ethercalc widget:

All of the links point to https://ethercalc.org/ when they should instead point to https://ethercalc.net, rending the widget inoperable.

I could easily fix this if I knew where the code for the widget was. I asked over at the matrix community, but there are so many issues/discussions that it just gets buried and no one responded.

Thanks!

**Comment by eddyparkinson** [comment]
I assume this issue: https://github.com/vector-im/element-web/issues/15074 

Yes, the domain name changed not long ago. Suggest you search the matrix code and config files. 

Sorry I don't know what matrix is.

**Comment by MarkWieczorek** [comment]
> Sorry I don't know what matrix is.

Matrix is an opensource protocol for end-2-end encrypted chat with a slack-like interface (accessed using the app *Element*). In a chat room you have the option to add bots/widgets/etc, and there is an ethercalc widget that allows you to pin a spreadsheet to the top of the room.

**Comment by jaywink** [comment]
We've fixed the hostname on the Element integration manager side, so this issue can be closed.
