### ISSUE TITLE
Looking for put API call with select options passed

### ISSUE THREAD

**Issue by balaji-ranga** [audreyt/ethercalc#744]
curl -k --include --request PUT --header "Content-Type: text/csv" --data-binary @./Downloads/testt.csv 'https://hostname/_/sittest'

Above command helps me initalize the sheet and i need to set a value in the sheet as select box. I tried sending CSV like below
s.no,Gender
1,"=Select('male','male,female')"
or
s.no,Gender
1,"Select('male','male,female')"
Nothing works. Can you please help me with any option

**Comment by eddyparkinson** [comment]
Use the API - https://ethercalc.docs.apiary.io/

`curl -H "Content-Type: application/json" -X POST -d '{"command":["set C2 formula textbox(\"fred@gmail\")"]}' http://host/_/sheetname
`
you can't add formulas via csv

**Comment by balaji-ranga** [comment]
Thanks a lot @eddyparkinson
