### ISSUE TITLE
Surligner couleur dans le tableur svp :)

### ISSUE THREAD

**Issue by Marti415** [audreyt/ethercalc#745]
Bonjour à toute l'équipe de Disroot,

merci pour votre travail spectaculaire,
merci pour votre dévouement envers notre vie privée,
merci de faire, avec une infime fraction des moyens que les GAFAM possèdent, des services : Open Sources, Libres, sures, éthiques, efficaces, de confiance, engagé pour une meilleure justice, résistante au capitalisme de données et à l’éradication de notre vie privée... fort agréables à utiliser.

Juste une suggestion : serait-ce possible d'implémenter la possibilité de surligner couleur dans votre tableur svp? Ce serait absolument génial!

Merci!

**Comment by aloisdg** [comment]
@Marti415 Disroot est un site d'hébergement de solution. Ils ne développent pas les solutions eux même. Ton poste s'adresse à une autre équipe qui n'a aucun rapport avec Disroot. La personne maintenant ce projet est de Taiwan et, au passage, Disroot est néerlandais. Evite le français en ligne. Peu de gens le parlent. L'anglais est la lingua franca.

----

OP is basically asking if it is possible to implement a way to highlight cells in ethercalc.

**Comment by eddyparkinson** [comment]
Some context would help.
  you can use colours, fonts, HTML wiki text - there are many ways.  ... Is this the type highlighting they are looking for?

**Comment by Marti415** [comment]
Eddy, you say that I can highlight on this clac?  https://calc.disroot.org/c2lvwlfrzr3a

**Comment by eddyparkinson** [comment]
I edited https://calc.disroot.org/c2lvwlfrzr3a 
e.g.
![image](https://user-images.githubusercontent.com/7961707/102834155-250c6900-4443-11eb-96ba-52910b69fbec.png)

**Comment by Marti415** [comment]
Eddy, you are a genius. You will be recongised only after your death! Hahaha!
(we say that in Québec to say that all genius don't have all  they diserve in their live).
Thank you very much! Have a nice day! :+1:  :)

**Comment by aloisdg** [comment]
@Marti415 glad it work out for you. Bonjour de Paris à nos cousins Québecois.
