### ISSUE TITLE
Ethercalc - 502 Bad Gateway nginx/1.15.12

### ISSUE THREAD

**Issue by fullmoon24** [audreyt/ethercalc#746]
when I want to access a table I created with ethercalc, I land on a page which says  : 502 Bad Gateway nginx/1.15.12

how to fix this ?

**Comment by fischerluat** [comment]
same issue here. The domain seems to have been down for several days now.

**Comment by fullmoon24** [comment]
thank you for your comment ! it reassures me in a way, it means it isn't a problem with my access only

is there anything which can be done ? how can we contact the people in charge of the domain ?

**Comment by eddyparkinson** [comment]
Use  https://ethercalc.net/    not    Ethercalc.org
---

She swapped the domain - Maybe you are using the old one.  Use https://ethercalc.net/    not    Ethercalc.org
  -- it works for me.

same issue - #725 #742

I will close - let me know if you need more help.

**Comment by ocdtrekkie** [comment]
@eddyparkinson I can corroborate that .net was giving 502s earlier today. Right now it's barely loading, it's extremely sluggish.

**Comment by eddyparkinson** [comment]
@ocdtrekkie how many seconds. For me about 15-30 seconds load times for a mostly empty sheet.
It is slower if it is the first load of the sheet since server restart. ... the volume of data and calculations is a big factor in load times.

I will reopen @audreyt

**Comment by ocdtrekkie** [comment]
I had it just not loading at all, and now it's loading again. It seems intermittent.

**Comment by AlainRnet** [comment]
We cannot open our spreadsheet and I cannot create new one : error 502 followed by a blank page (after reloading the page) and error 504 after I resend URL in the browser

**Comment by audreyt** [comment]
Confirmed. I'll work on this tomorrow and hopefully move to a more stable host this weekend.

**Comment by ozett** [comment]
at the moment "https://ethercalc.net" still has error 502-bad gateway
🤔

**Comment by matteolovalvo** [comment]
Down again for days :(

**Comment by ninjafun228** [comment]
Please, help! Again there was a problem with the work of the plate. Error 502 while loading. At the most crucial moment (if the table does not work until 08/31/2021, then I will lose 1000 dollars ... this is tough (how can I get the data out of my table?

**Comment by ninjafun228** [comment]
Developers, please check the hosting or domains. I cannot know what your problem is. But I'm losing money (and I'm very worried about that. Please help me pull the data! Why is the table so unstable? Great solution for team work, but very unstable. 
Give me back my data, how can I access it ?! If I knew it would cost me $ 1000 to use your solution, I would use alternative solutions.

**Comment by audreyt** [comment]
It's back now.

**Comment by daffodile24** [comment]
Hi @audreyt , ethercalc.net has been down for a few hours, is it possible that it will be restored soon?

**Comment by audreyt** [comment]
Hi! It's back now.

**Comment by Myriam-byte** [comment]
Hi @audreyt, ethercal.net hast been down for a few days now. Can it be restored soon? Thanks!
