### ISSUE TITLE
Keyborad shortcut CTRL+B failed to bold the text in sheet

### ISSUE THREAD

**Issue by Rn-jit** [audreyt/ethercalc#751]
Hi,
If I enter some text in a sheet and press the **CTRL+B** from the keyboard, then it fails to bold the text.
How to bold the text in sheet by pressing CTRL+B from keyboard?

**Comment by eddyparkinson** [comment]
Not supported
---
Sorry to say, it is not supported. Pull requests are welcome.

Keyboard shortcut
---

Would be good if someone added shortcuts to https://github.com/audreyt/ethercalc/wiki

Most of the code is here:
https://github.com/marcelklehr/socialcalc/blob/master/js/socialcalctableeditor.js#L191

Looks to be
 CTRL-A
 CTRL-C
 CTRL-V
 CTRL-X
 CTRL-Z
 CTRL-S
  ESC
  F2

Pull requests welcome.

**Comment by Rn-jit** [comment]
Thanks for your answer.
Can I enhance this feature in ethercalc by making some changes in the code?

**Comment by eddyparkinson** [comment]
Yes. 

Addition of  CTRL-A ... should be very similar.
https://github.com/audreyt/ethercalc/issues/368

**Comment by Rn-jit** [comment]
But there is no such similarity to add the feature CTRL-B to bold the text.

**Comment by Sr-Preet** [comment]
@eddyparkinson 
Hey Eddy,
I'm using ethercalc with redis database, I do know that whenever I'm editing a cell or changing the format to bold, values of two keys are changing
`snapshot-example`
`audit-example`

I'm having hard time to pin point the exact code which is making these changes.

The files `main.js` and `sc.js` both have the redis functions implemented are getting called by prefixing the function call with `DB.multi()`.

I'll be making use of the shortcut cases defined in `ethercalc,js` to create a new shortcut to format the cells without going to the format tab.

Can you help me regarding this?

**Comment by eddyparkinson** [comment]
Breakpoint
---
I would set a breakpoint in the browser here: 
  https://github.com/marcelklehr/socialcalc/blob/master/js/socialcalc-3.js#L1808 

then try setting a cell to bold.


ExecuteSheetCommand  
---

the function ExecuteSheetCommand  changes the text to bold 
Note you should call ScheduleSheetCommands not ExecuteSheetCommand  

if you call ScheduleSheetCommands, with the right parameters it should set the current cell to bold.

**Comment by Sr-Preet** [comment]
@eddyparkinson 
Hey eddy, I've followed up to what you've suggested and I've managed to pull this off by adding the control keys for `ctrl-b` and `ctrl-i`. And then adding the code in `static/ethercalc.js` which will be executed each time these keys are pressed.

So now I can change the text to bold/italic/normal with keyboard shortcuts rather than going to format tab.

Thanks for the help.

**Comment by eddyparkinson** [comment]
@Sr-Preet if you want to do a pull request the see https://github.com/audreyt/ethercalc/blob/master/Makefile 
... because static/ethercalc.js is auto generated by the make file. From these js files https://github.com/marcelklehr/socialcalc and ethercalc .ls files.
