### ISSUE TITLE
ethercalc.org replaced by pdfbear

### ISSUE THREAD

**Issue by PhilLAL** [audreyt/ethercalc#756]
Hi,
I see that pdfbear seems to use ethercalc.org 
Is it normal ?

**Comment by eddyparkinson** [comment]
Try:
https://ethercalc.net/

ethercalc.org is old

**Comment by ozett** [comment]
today.... 😢 
![image](https://user-images.githubusercontent.com/5937811/112748951-881c1780-8fbf-11eb-9594-3d98fad5396c.png)
