### ISSUE TITLE
ethercalc.net down?

### ISSUE THREAD

**Issue by sunny8282** [audreyt/ethercalc#758]
I can't seem to access my spreadsheet. Is the page down and is there another way I can access the spreadsheet?

**Comment by matteolovalvo** [comment]
It's down for 4 days or so, is it going to recover?

**Comment by eddyparkinson** [comment]
@audreyt looks to be down - any news?

**Comment by audreyt** [comment]
It should be back now; Linode had an automated maintenance that left the network unconnected and it's fixed.

**Comment by matteolovalvo** [comment]
Back for few hours and then again down.

**Comment by audreyt** [comment]
I've migrated EtherCalc to a new machine. The log functionality is still migrating and should come back online this weekend (or sooner).

**Comment by matteolovalvo** [comment]
It's still down

**Comment by audreyt** [comment]
Back now. The log functionality is taking a while to fully migrate. I’ll post here when it’s back up.

**Comment by matteolovalvo** [comment]
Down again, it's very very unstable

**Comment by audreyt** [comment]
Should be better now.
