### ISSUE TITLE
Ошибка 502

### ISSUE THREAD

**Issue by ninjafun228** [audreyt/ethercalc#767]
Пожалуйста  помогите! Опять возникла проблема с работой таблички. При загрузке 502 ошибка. В самый ответственный момент( если таблица не будет работать до 31.08.2021 то я потеряю 1000 долларов...это жесть( как мне вытащить данные из моей таблицы?

**Comment by ninjafun228** [comment]
Please, help! Again there was a problem with the work of the plate. Error 502 while loading. At the most crucial moment (if the table does not work until 08/31/2021, then I will lose 1000 dollars ... this is tough (how can I get the data out of my table?

**Comment by eddyparkinson** [comment]
Looks like a scam. i.e. Urgent + Money  - closing
