### ISSUE TITLE
希望能添加首行固定

### ISSUE THREAD

**Issue by woaidianqian** [audreyt/ethercalc#775]
请问能否添加首行固定功能，这样方便多人填表时查看列标签。

**Comment by help1234** [comment]
首行和首列固定功能都是有的啊，拉动蓝色的句柄就是

**Comment by woaidianqian** [comment]
> 

![image](https://user-images.githubusercontent.com/10897660/154992075-db6d9cf9-8cb0-464e-9340-5d263f9e7298.png)
请问在哪里，能帮我标注一下吗，我实在是没找到，谢谢

**Comment by woaidianqian** [comment]
> 首行和首列固定功能都是有的啊，拉动蓝色的句柄就是

https://github.com/audreyt/ethercalc/issues/775#issuecomment-1042498691
谢谢，已经找到了，实在是不太明显。

**Comment by woaidianqian** [comment]
https://github.com/audreyt/ethercalc/issues/775#issuecomment-1042498691
