### ISSUE TITLE
Adding color buttons to the top nav bar

### ISSUE THREAD

**Issue by ferrlen** [audreyt/ethercalc#780]
Ethercalc is absolutely brilliant and although it's not intended to be a substitute for GoogleSheets, it fulfills all my needs in that regard, except for one. I'm not finding a way in the GUI to style cells, and in specific, to change the color of a specific cell (like having a button to change color, or backgroundcolor, font size, weight, etc.).

Is it there and I'm missing it? I'm testing ethercalc on this site: https://ethercalc.net/

If it's not there, is it easy to add this functionality? For example, can I add a JSON file somewhere that would easily add this functionality?

Thank you!

**Comment by eddyparkinson** [comment]
Use the "Format" menu. It has a lot of format options. Most of the formatting options are available via the format menu. 

The top nav bar has paste formats, this lets you copy and paste a format to other cells.
