### ISSUE TITLE
Ethercalc.net is down

### ISSUE THREAD

**Issue by SansPseudoFix** [audreyt/ethercalc#788]
Hello!
When I try to access the website: "Unable to connect".
Checked with https://downforeveryoneorjustme.com/ethercalc.net too, to be sure.

I'm not sure if you prefer this kind of report in this repository or in https://github.com/audreyt/ethercalc.net/issues. But since there no issue in the other one, and some about it here…

**Comment by reviewher** [comment]
It is up at the moment

**Comment by SansPseudoFix** [comment]
Indeed.
