### ISSUE TITLE
References to cell values in other sheets of thd document do not work.

### ISSUE THREAD

**Issue by RainerBielefeld** [audreyt/ethercalc#805]
## STR:    
1. Open https://ethercalc.net/=4eo2j7v6l2  (Imported .ods document)
2. Try to get value "2" from Cell B2 in "sheet2" to A3 in "Tabelle1"    
The formula I use is that what I think that I should do after having read [instructions](https://github.com/audreyt/ethercalc/wiki)
Expected: Result "2"
Actual: Result is value "0"   
 
My mistake or Bug?

**Comment by eddyparkinson** [comment]
try:

='4eo2j7v6l2.2'!B2

the .2 is the sheet number

**Comment by RainerBielefeld** [comment]
Thx, yup, that does the trick!  I'll think about that later!

**Comment by RainerBielefeld** [comment]
And that's completely different to [instructions](https://github.com/audreyt/ethercalc/wiki). Can you please have a look? And update information there?
