### ISSUE TITLE
Integration with a commercial product? (license)

### ISSUE THREAD

**Issue by benbro** [audreyt/ethercalc#84]
Hi,

When integrating ethercalc with a commercial product, do I need to only release modifications to ethercalc itself or does it means that the whole product should be open sourced?
For example, a webpage with several tabs each with a different app: text editor, whiteboard and ethercalc. Do I need to release only the ethercalc modifications or the source for the text editor and whiteboard as well?

From the license it seems that as long as ethercalc is kept in a separate file and no ethercalc code (except for API calls) is used in other part of the app it should be fine but I just wanted to make sure.

Thanks

```
1.9 "Modifications" means any addition to or deletion from the substance or structure
of either the Original Code or any previous Modifications. When Covered Code is
released as a series of files, a Modification is:

A. Any addition to or deletion from the contents of a file containing Original Code
or previous Modifications.

B. Any new file that contains any part of the Original Code or previous Modifications.
```

**Comment by JohnMcLear** [comment]
@benbro I commented on this at https://github.com/audreyt/ethercalc/issues/22

**Comment by audreyt** [comment]
@JohnMcLear FYI, the 16x16 logo issue that you find issues with in `socialcalctableeditor.js` can be worked around altogether with a new editor frontend, while keeping the rest of EtherCalc (formula engine, import/export and collaboration).

I've started working on such a frontend in https://github.com/audreyt/500lines/tree/master/spreadsheet#online-demo (again in the public domain as CC0) and if folks are interested I'd be happy to offer it as an alternative frontend. Other UI frontend suggestions are welcome, too!
