### ISSUE TITLE
Error: failed to fetch from registry

### ISSUE THREAD

**Issue by liberatic** [audreyt/ethercalc#85]
I'm new to node.js, npm, and so on; but following a few instructions to install ETHERCALC on Ubuntu resulted in problems. 

Any advice will be welcome! Thanks in advance

---

/opt/ethercalc# npm i

npm http GET https://registry.npmjs.org/redis/0.8.2
npm http GET https://registry.npmjs.org/uuid-pure
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/zappajs
npm http GET https://registry.npmjs.org/cors
npm http GET https://registry.npmjs.org/LiveScript
npm http GET https://registry.npmjs.org/webworker-threads

npm ERR! Error: failed to fetch from registry: optimist
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1261:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR! You may report this log at:
npm ERR!     http://bugs.debian.org/npm
npm ERR! or use
npm ERR!     reportbug --attach /opt/ethercalc/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.2.0-60-generic
npm ERR! command "node" "/usr/bin/npm" "i"
npm ERR! cwd /opt/ethercalc
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: optimist
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/ethercalc/npm-debug.log

**Comment by shoaib1236** [comment]
i am installing in windows 8.1 and configure in php xampp. how can i install?

**Comment by shoaib1236** [comment]
i have install node.js and run command npm install -g ethercalc but it gives me registry error.

npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning ETIMEDOUT: request to https://registry.npmjs.org/ethercalc failed, reason: connect ETIMEDOUT 104.16.22.35:443

**Comment by eddyparkinson** [comment]
looks like a network error.
