### ISSUE TITLE
Access Control to specific sheets

### ISSUE THREAD

**Issue by liberatic** [audreyt/ethercalc#87]
Hi folks!

 I'm looking for a "Access Control" mecanism to restrict several ethercalc sheets in a flexible way.

 Is there exist?

 Thanks in advance

**Comment by hamdijmii1992** [comment]
@audreyt: I have a spreedsheet and I have two mode in my app that allows the user to edit the spreed on mode edit and just make a sample view(read only) on mode consultation.
Please How can I handle this situation ??

**Comment by audreyt** [comment]
https://ethercalc.org/test/view will be the read only mode.
On 2016年4月20日 週三 at 17:00 hamdijmii1992 <notifications@github.com> wrote:

> @audreyt <https://github.com/audreyt>: I have a spreedsheet and I have
> two mode in my app that allows the user to edit the spreed on mode edit and
> just make a sample view(read only) on mode consultation.
> Please How can I handle this situation ??
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/audreyt/ethercalc/issues/87#issuecomment-212338203>
>
-- 

Cheers,
Audrey

**Comment by hamdijmii1992** [comment]
Thank you very much
